### ISSUE TITLE
sslyze requires write access on startup

### ISSUE THREAD

**Issue by postmodern** [nabla-c0d3/sslyze#1]
I was attempting to install sslyze in `/usr/local` and run it as a normal user, but got this error:

<pre>
$ python sslyze.py --regular www.isecpartners.com:443 www.google.com
Traceback (most recent call last):
  File "sslyze.py", line 31, in <module>
    from plugins import PluginsFinder
ImportError: No module named plugins
</pre>

After extracting sslyze into my home directory, it worked.

<pre>
$ python sslyze.py

 REGISTERING AVAILABLE PLUGINS
 -----------------------------

  PluginHSTS
  PluginCertInfo
  PluginSessionRenegotiation
  PluginHeartbleed
  PluginCompression
  PluginOpenSSLCipherSuites
  PluginChromeSha1Deprecation
  PluginSessionResumption

  Command line error: No targets to scan.
  Use -h for help.
</pre>

**Comment by jfqd** [comment]
If installed in /usr/local on a mac it need to be run with sudo or doing a chown to the current user.

**Comment by postmodern** [comment]
Still running into this in production with sslyze installed by root into `/opt/sslyze`. Even after running it as root, so python would create the `.pyc` files, it fails to load the plugins as a normal user.

**Comment by postmodern** [comment]
Ah ignore my last comment. `unzip` appears to preserve permissions instead of setting sane default permissions. Many of the directories were missing `r-x` permissions for group/other.
