### ISSUE TITLE
xml_out in sslyze.py causes exception

### ISSUE THREAD

**Issue by zistrox** [nabla-c0d3/sslyze#100]
Today i tried the latest master and figured out that there is something wrong in line 340 in sslyze.py:
`xml_file.write(xml_final_pretty.toprettyxml(indent="  ", encoding="utf-8" ))`
after chaning to:
`xml_file.write(xml_final_pretty)`
xml output to file worked

best regards

**Comment by nabla-c0d3** [comment]
Thanks! fixed in 010ea84d7611bcd244de0b01406032d72db3b152
