### ISSUE TITLE
Timeout ignored

### ISSUE THREAD

**Issue by Gank** [nabla-c0d3/sslyze#102]
Hi guys,

Was testing the sslyze timeout and it appears to be ignored if it can't connect to the server and takes over a minute to trigger the timeout.

```
sslyze.py --timeout=5 reddit.com:44

 AVAILABLE PLUGINS
 -----------------
......

 CHECKING HOST(S) AVAILABILITY
 -----------------------------

   reddit.com:44                       => WARNING: Could not connect (timeout); discarding corresponding tasks.

 SCAN COMPLETED IN 66.24 S
```

I tested with and without the timeout argument, behaviour is the same.
Any hints of how to force a connection timeout?

Thanks!

**Comment by nabla-c0d3** [comment]
There's an exponential backoff algorithm where it will keep on trying to connect a few times (4 by default) if a timeout happened. This is why the whole thing takes 60s. You can control the number of retry attempts using --nb_retries.
