### ISSUE TITLE
sslyze fails to run plugins when only a few ciphers are accepted by the server

### ISSUE THREAD

**Issue by happyc0ding** [nabla-c0d3/sslyze#106]
To my understanding, enumerating ciphers and running the plugins is handled differently regarding the ciphers provided by the client:

utils/SSLyzeSSLConnection.py:
```python
# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=665452
sslConn.set_cipher_list('HIGH:MEDIUM:-aNULL:-eNULL:-3DES:-SRP:-PSK:-CAMELLIA')
```

plugins/PluginOpenSSLCipherSuites.py:
```python
sslClient.set_cipher_list('ALL:COMPLEMENTOFALL')
```

The comment clearly states why this is done (problem with long requests). However, if a SSL service is configured to only allow a few ciphers, i.e. 3DES, enumerating the ciphers works, but all plugins will fail with a handshake exception.

My suggestion would be to catch the handshake failure and to retry the connection with all ciphers ('ALL:COMPLEMENTOFALL') or all ciphers which have not been tried in the previous request (low, null, 3des, ...).

Thanks!

**Comment by nabla-c0d3** [comment]
Hi,
The first cipher list is only used to do a connection to see if the server is up and running.
My reasoning is that if the server doesn't support the "usual" cipher suites, no normal clients can connect to it which would seem like a bug anyway.
What do you think ? What's the use case for this server?
Thanks

**Comment by happyc0ding** [comment]
Hi,
I completely agree with you: This configuration does not make any sense. However, I see strange SSL configurations on a regular basis - and some of these services make sslyze fail and it would be nice if they didn't.
What do you think? Is it too much effort to try another handshake with a different cipher list?

Thanks.

**Comment by ikarus23** [comment]
Hey there,
I come across strange SSL configurations like this too (although they make no sense). It would be really cool if I could use `sslyze` even for these strange servers...

**Comment by nabla-c0d3** [comment]
Yeah that makes sense - will make the change.
