### ISSUE TITLE
[Request] Support for Perfect Forward Secrecy detection

### ISSUE THREAD

**Issue by benji1000** [nabla-c0d3/sslyze#109]
Hello,

would it be possible to support PFS detection? If I'm not mistaken, it would be as simple as looping through all of the accepted ciphers for each TLS protocol and look for the string "DHE", since PFS requires the use of Ephemeral Diffie-Hellman key exchange.

Thank you for your work on this project!

**Comment by nabla-c0d3** [comment]
It's already there, as you mentioned. Presenting a "curated"/easy-to-read list of SSL issues and information is not really part of SSLyze's goal, as it should only return "raw" information about the server's configuration - trying to keep things simple. 
A wrapper that parses the XML output would be better for this, and it would only take a few lines of code.
