### ISSUE TITLE
Socket timeout when test heartbleed

### ISSUE THREAD

**Issue by malaikuangren** [nabla-c0d3/sslyze#11]
All, I tried to test my site(https://192.168.2.104) if there exist vulnerability of heartbleed but got the socket time out problem. Please help to review below out put.

 CHECKING HOST(S) AVAILABILITY

---

   192.168.2.104:443                   => 192.168.2.104:443

 SCAN RESULTS FOR 192.168.2.104:443 - 192.168.2.104:443

---

Unhandled exception when processing --heartbleed:
socket.timeout - timed out

I am sure my site (https://192.168.2.104) can be reached in the network.
Is there any reason cause this exception? 

Thanks,
Joe

**Comment by six8** [comment]
Is the timeout an indication that the server is not vulnerable? This times out every time for me.

**Comment by mhuuhka** [comment]
im getting the timeout aswell. Would be nice to get an answer to earlier question.

**Comment by nabla-c0d3** [comment]
This was fixes in #217

**Comment by glestel** [comment]
With the migration to 1.1.1. I'm getting `[u'Unhandled exception while running --heartbleed:', u'timeout - timed out']` on a domain that never triggered error with previous version

**Comment by ericrange** [comment]
this "exception" is already in 1.0.0
but as @nabla-c0d3 said, you get an exception if u are not vulnerable to heartbleed.

**Comment by nabla-c0d3** [comment]
@glestel can you post or send me the domain? I am working on a better fix in the raw-tls-parsing branch so I want to try it.

**Comment by glestel** [comment]
Sent you a mail with domains of interest
