### ISSUE TITLE
Create a wrapper with easy-to-read output

### ISSUE THREAD

**Issue by nabla-c0d3** [nabla-c0d3/sslyze#111]
This is a recurring request (issue #109 , issue #83, etc.). We should have a wrapper that parses the XML output and displays easy-to-read information.

**Comment by glestel** [comment]
You can inspire from my work that parse the xml output and raise issues for bad results. It's what I do to integrate SSLyze with [Mozilla Minion](https://github.com/mozilla/minion). It's part of [Minion SSLyze Plugin](https://github.com/Wawki/minion-sslyze-plugin)

**Comment by tykkz** [comment]
I want to work on this @nabla-c0d3, what do you have in mind?

If you have any plans regarding this issue, other than "reading the XML file" & "generating one-page HTML file", I can help in the implementation.

**Comment by nabla-c0d3** [comment]
Cool! I don't have specific plans but it would be something that only returns output when there is an issue with the server's configuration. It would be different than the current output, which just kind of returns everything. 

Also, you should not use the XML file but instead directly process the `PluginResult` objects directly from Python. It will be much easier and cleaner.

**Comment by postmodern** [comment]
FYI, you can add an `<?xml-stylesheet href="file:///path/to/stylesheet.xsl" type="text/xsl"?>` directive to the XML output to automatically convert the XML into HTML when opened in a web browser. Nmap [does this](https://svn.nmap.org/nmap/docs/nmap.xsl).

**Comment by nabla-c0d3** [comment]
This is issue is no longer relevant. The CLI output was significantly improved (it usually says VULNERABLE or OK for each issue), BEAST is no longer a threat (https://blog.qualys.com/ssllabs/2013/09/10/is-beast-still-a-threat) and the best mitigation to POODLE is to disable SSL 3.0 and TLS 1.0
