### ISSUE TITLE
Client Certificate Handling does not work

### ISSUE THREAD

**Issue by clfnk** [nabla-c0d3/sslyze#113]
In the 0.12 (and trunk) version of 'nassl', the client certificate and key information is set on the SSL_CTX - after  the SSL object is created from it in 'SslClient.py'. According to the OpenSSL documentation, the properties (cert, key) are only taken into account for SSL objects subsequently created (but not for the already created SSL object that will be used in turn by sslyze). This means that specifying a client certificate does not work. 
See: https://www.openssl.org/docs/manmaster/ssl/SSL_CTX_use_certificate.html

### Approach 1
See [client-cert-approach-1-trunk-20151227.zip](https://github.com/nabla-c0d3/sslyze/files/77415/client-cert-approach-1-trunk-20151227.zip) for diff / original / patched files. Note: Files are based on trunk of 2015-12-27.

As a first idea, I thought to fix it up by adding the corresponding SSL functions to 'nassl' to be able to set the information on the SSL object instead the SSL_CTX (only 'use_private_key' in SslClient.py would change on the python level). I have tested this and it basically works. However, not all the methods present for the SSL_CTX are present for SSL in OpenSSL 1.0.2. Some methods are only present in the master version. Notably, the following are missing in 1.0.2:
- int SSL_use_certificate_chain_file(SSL *ssl, const char *file);
- void SSL_set_default_passwd_cb(SSL *s, pem_password_cb *cb);
- void SSL_set_default_passwd_cb_userdata(SSL *s, void *u);

See (master): https://www.openssl.org/docs/manmaster/ssl/SSL_CTX_use_certificate.html
See (1.0.2): https://www.openssl.org/docs/man1.0.2/ssl/SSL_CTX_use_certificate.html
See (master): https://www.openssl.org/docs/manmaster/ssl/SSL_CTX_set_default_passwd_cb.html
See (1.0.2): https://www.openssl.org/docs/man1.0.2/ssl/SSL_CTX_set_default_passwd_cb.html

I implemented the fix using certificate file (instead of chain) and trying to set the password / password handler on  the context (as before). Supplying a certificate / key now worked but only if the key was not encrypted. Although 'SSL_CTX_set_default_passwd_cb' does not mention it is not propagated to existing SSL objects, I assumed it is the case as I could not use an encrypted key. But I'm not sure that is the problem as encrypted private keys do not work with the approach described below neither.

Note that the operations not needed anymore from SSL_CTX are not removed yet.

### Approach 2 
See [client-cert-approach-2-0.12.zip](https://github.com/nabla-c0d3/sslyze/files/77419/client-cert-approach-2-0.12.zip) for diff / original / patched files. Note: Files are based on version 0.12.

I have patched the issue at the python level, basically extending the 'SslClient' constructor and all the constructors of sub-objects and their invocations. In the 'SslClient' constructor, the 'use_private_key' funtion is called after the SSL_CTX is created but before the SSL object is created from the CTX.  With this fix, supplying the client certificate / key works. But again, only if no password is set for the key. I assume there is another issue in password password handling. Unfortunately, I do not have the time now to dig further, so just as an info (as I do not have encrypted private keys in my test setup, the fix works for me).

**Comment by nabla-c0d3** [comment]
Thanks for figuring this out! I will probably go for approach 2 because being able to pass a chain (instead of a single cert) was a feature request. I'll also figure out the password issue.

**Comment by clfnk** [comment]
Great! And thanks for providing this handy tool!

**Comment by nabla-c0d3** [comment]
If you can please try the fix (you will the new nassl) and let me know if run into issues. Thanks!

**Comment by clfnk** [comment]
I have tried the fix and it works, thanks! 

Also with an encrypted key, as long as it is encrypted with a compatible cipher - not all encryption schemes worked for me, some gave an error as shown below, the first line states that the cipher seems unknown.
```error:060740A0:digital envelope routines:EVP_PBE_CipherInit:unknown cipher
error:23077073:PKCS12 routines:PKCS12_pbe_crypt:pkcs12 algor cipherinit error
error:2306A075:PKCS12 routines:PKCS12_item_decrypt_d2i:pkcs12 pbe crypt error
error:0907B00D:PEM routines:PEM_READ_BIO_PRIVATEKEY:ASN1 lib
error:140B0009:SSL routines:SSL_CTX_use_PrivateKey_file:PEM lib```

Note: With the most recent version, output is a bit restricted without specifying the client certificate/key when compared to the version before. The first sample is my old version run without client certificate/key, the second is the trunk version without a certificate/key (note that I can life with that as I have to give the certificate/key to sslyze anyway to test what I want to).

== BEFORE ==

```
AVAILABLE PLUGINS
-----------------

  PluginOpenSSLCipherSuites
  PluginChromeSha1Deprecation
  PluginCompression
  PluginSessionRenegotiation
  PluginHSTS
  PluginSessionResumption
  PluginHeartbleed
  PluginCertInfo



 CHECKING HOST(S) AVAILABILITY
 -----------------------------

   localhost:12345                     => 127.0.0.1:12345



 SCAN RESULTS FOR LOCALHOST:12345 - 127.0.0.1:12345
 --------------------------------------------------

  * Session Renegotiation:
      Client-initiated Renegotiations:   ERROR
      Secure Renegotiation:              ERROR

  * Deflate Compression:
      OK - Compression disabled

Unhandled exception when processing --heartbleed:
utils.SSLyzeSSLConnection.SSLHandshakeRejected - TLS / Unexpected EOF

  * Certificate - Content:
      SHA1 Fingerprint:                  a9774f4738926d2ce0682dee7bad510711c362e1
      Common Name:                       Web Service
      Issuer:                            Web Service
      Serial Number:                     A7E94E4BA81C6B0F542ADF72705A924BABFDBF71
      Not Before:                        Jan 11 12:54:07 2016 GMT
      Not After:                         Jan  8 12:54:07 2026 GMT
      Signature Algorithm:               sha256WithRSAEncryption
      Public Key Algorithm:              rsaEncryption
      Key Size:                          4096 bit
      Exponent:                          65537 (0x10001)

  * Certificate - Trust:
      Hostname Validation:               FAILED - Certificate does NOT match localhost
      Google CA Store (09/2015):         FAILED - Certificate is NOT Trusted: self signed certificate
      Java 6 CA Store (Update 65):       FAILED - Certificate is NOT Trusted: self signed certificate
      Microsoft CA Store (09/2015):      FAILED - Certificate is NOT Trusted: self signed certificate
      Mozilla NSS CA Store (09/2015):    FAILED - Certificate is NOT Trusted: self signed certificate
      Apple CA Store (OS X 10.10.5):     FAILED - Certificate is NOT Trusted: self signed certificate
      Certificate Chain Received:        ['Web Service']

  * Certificate - OCSP Stapling:
      NOT SUPPORTED - Server did not send back an OCSP response.

  * TLSV1_2 Cipher Suites:
      Undefined - An unexpected error happened:
                 ECDHE-RSA-AES256-GCM-SHA384         ClientCertificateRequested - Server requested a client certificate issued by one of the following CAs: '/C=CH/O=MYORG/CN=database', '/C=CH/O=MYORG/OU=SASS/CN=Web Service'.
                 ECDHE-RSA-AES128-GCM-SHA256         ClientCertificateRequested - Server requested a client certificate issued by one of the following CAs: '/C=CH/O=MYORG/CN=database', '/C=CH/O=MYORG/OU=SASS/CN=Web Service'.
                 DHE-RSA-AES256-GCM-SHA384           ClientCertificateRequested - Server requested a client certificate issued by one of the following CAs: '/C=CH/O=MYORG/CN=database', '/C=CH/O=MYORG/OU=SASS/CN=Web Service'.
                 DHE-RSA-AES128-GCM-SHA256           ClientCertificateRequested - Server requested a client certificate issued by one of the following CAs: '/C=CH/O=MYORG/CN=database', '/C=CH/O=MYORG/OU=SASS/CN=Web Service'.

  * Session Resumption:
      With Session IDs:                  ERROR (0 successful, 0 failed, 5 errors, 5 total attempts).
        ERROR #1: ClientCertificateRequested - Server requested a client certificate issued by one of the following CAs: '/C=CH/O=MYORG/CN=database', '/C=CH/O=MYORG/OU=SASS/CN=Web Service'.
        ERROR #2: ClientCertificateRequested - Server requested a client certificate issued by one of the following CAs: '/C=CH/O=MYORG/CN=database', '/C=CH/O=MYORG/OU=SASS/CN=Web Service'.
        ERROR #3: ClientCertificateRequested - Server requested a client certificate issued by one of the following CAs: '/C=CH/O=MYORG/CN=database', '/C=CH/O=MYORG/OU=SASS/CN=Web Service'.
        ERROR #4: ClientCertificateRequested - Server requested a client certificate issued by one of the following CAs: '/C=CH/O=MYORG/CN=database', '/C=CH/O=MYORG/OU=SASS/CN=Web Service'.
        ERROR #5: ClientCertificateRequested - Server requested a client certificate issued by one of the following CAs: '/C=CH/O=MYORG/CN=database', '/C=CH/O=MYORG/OU=SASS/CN=Web Service'.
      With TLS Session Tickets:          ERROR: ClientCertificateRequested - Server requested a client certificate issued by one of the following CAs: '/C=CH/O=MYORG/CN=database', '/C=CH/O=MYORG/OU=SASS/CN=Web Service'.

  * SSLV2 Cipher Suites:
      Server rejected all cipher suites.

  * TLSV1_1 Cipher Suites:
      Server rejected all cipher suites.

  * TLSV1 Cipher Suites:
      Server rejected all cipher suites.

  * SSLV3 Cipher Suites:
      Server rejected all cipher suites.
```

== NEW ==

```
AVAILABLE PLUGINS
 -----------------

  PluginHeartbleed
  PluginChromeSha1Deprecation
  PluginOpenSSLCipherSuites
  PluginSessionResumption
  PluginCertInfo
  PluginSessionRenegotiation
  PluginCompression
  PluginHSTS



 CHECKING HOST(S) AVAILABILITY
 -----------------------------

   localhost:12345                     => 127.0.0.1:12345



 SCAN RESULTS FOR LOCALHOST:12345 - 127.0.0.1:12345
 --------------------------------------------------

Unhandled exception when processing --reneg:
utils.SSLyzeSSLConnection.SSLHandshakeRejected - TLS / Unexpected EOF

Unhandled exception when processing --compression:
utils.SSLyzeSSLConnection.SSLHandshakeRejected - TLS / Unexpected EOF

Unhandled exception when processing --heartbleed:
utils.SSLyzeSSLConnection.SSLHandshakeRejected - TLS / Unexpected EOF

  * TLSV1_2 Cipher Suites:
      Server rejected all cipher suites.

Unhandled exception when processing --certinfo:
utils.SSLyzeSSLConnection.SSLHandshakeRejected - TLS / Unexpected EOF

  * SSLV2 Cipher Suites:
      Server rejected all cipher suites.

  * TLSV1_1 Cipher Suites:
      Server rejected all cipher suites.

  * Session Resumption:
      With Session IDs:                  ERROR (0 successful, 0 failed, 5 errors, 5 total attempts).
        ERROR #1: SSLHandshakeRejected - TLS / Unexpected EOF
        ERROR #2: SSLHandshakeRejected - TLS / Unexpected EOF
        ERROR #3: SSLHandshakeRejected - TLS / Unexpected EOF
        ERROR #4: SSLHandshakeRejected - TLS / Unexpected EOF
        ERROR #5: SSLHandshakeRejected - TLS / Unexpected EOF
      With TLS Session Tickets:          ERROR: SSLHandshakeRejected - TLS / Unexpected EOF

  * TLSV1 Cipher Suites:
      Server rejected all cipher suites.

  * SSLV3 Cipher Suites:
      Server rejected all cipher suites.
```

**Comment by nabla-c0d3** [comment]
Can you try the latest master and let me know if it improved the output (back to how it was) ?
Thanks!

**Comment by clfnk** [comment]
Unfortunately, the new OpenSSL base seems to break some things:

*HTTPS with client authentication leads to error*
Before (sslyze commit 7eacc67d51fe89967d000d67e4f73afebf79c83a)
=> As stated previously.

New (sslyze commit 7d6fc64fdae2a972adea4a955b7c1de3acfd510d)
```
Traceback (most recent call last):
  File "./sslyze_cli.py", line 630, in <module>
    main()
  File "./sslyze_cli.py", line 532, in main
    raise exception
_nassl.OpenSSLError:
error:1418C197:SSL routines:ssl3_shutdown:shutdown while in init
```
The error does not occur when checking HTTPS without client authentication.
I have observed the same error when attempting to check XMPP (server).

*Postgres check fails*
before (sslyze commit 7eacc67d51fe89967d000d67e4f73afebf79c83a)
By using --starttls=postgres, check went fine.

New (sslyze commit 7d6fc64fdae2a972adea4a955b7c1de3acfd510d)
```
CHECKING HOST(S) AVAILABILITY
-----------------------------

localhost:5432                      => WARNING: Postgres AUTH TLS was rejected; discarding corresponding tasks.
```

**Comment by nabla-c0d3** [comment]
It should be fixed now

**Comment by servomekanism** [comment]
@clfnk what command line arguments are you using to use the .p12 file as input, as shown in the second try?
