### ISSUE TITLE
Separate Client Initiated Renego and Secure Renego Checks

### ISSUE THREAD

**Issue by clfnk** [nabla-c0d3/sslyze#114]
When testing session negotiation with Netty (Java TCP I/O framework) the check for client initiated session renegotiation leads to an error because of how Netty handles 'unsupported client renegotiation'. The issue here is that the secure negotiation is checked but not reported because of the exception raised in the client initiated renegotiation check. I have therefore split the checks. If an exception occurs in one of the checks, it reports 'ERROR' for that part. See attached version. Maybe having two separate plugins may be preferred. 
[PluginSessionRenegotiation.zip](https://github.com/nabla-c0d3/sslyze/files/77424/PluginSessionRenegotiation.zip)

**Comment by nabla-c0d3** [comment]
Pushed some of your changes, but I need the exact exception returned by Netty so I can catch it in the plugin. Do you have the error message you've been seeing? 
Catching all exceptions and returning ERROR would hide other issues (no internet connection, server is slow, etc.). Thanks!

**Comment by clfnk** [comment]
It leads to a socket.timeout exception. Note that this exception has to be handled before the socket.error (as socket.timeout is a suberror of socket.error).

```Unhandled exception when processing --reneg:
socket.timeout - timed out```
