### ISSUE TITLE
Unhandled exception when processing --heartbleed 

### ISSUE THREAD

**Issue by reidca** [nabla-c0d3/sslyze#115]
Keep receiving the following error when testing IIS servers:

Unhandled exception when processing --heartbleed:
utils.SSLyzeSSLConnection.SSLHandshakeRejected - TCP / Received FIN

**Comment by nabla-c0d3** [comment]
Can you send me a URL so I can reproduce it?
Thanks

**Comment by nabla-c0d3** [comment]
I tried a scan on a few IIS servers with the latest sslyze and couldn't reproduce this.
