### ISSUE TITLE
Issues with moving to OpenSSL 1.1.0

### ISSUE THREAD

**Issue by nabla-c0d3** [nabla-c0d3/sslyze#116]
In OpenSSL 1.1.0, support for SSL 2.0 and export cipher suites was removed. This is good for the Internet but bad for SSLyze. We also cannot stay stuck on 1.0.2 forever as new cipher suites (ChaCha20 and Poly1305) were added 1.1.0. This might require writing a plugin to check for cipher suites and protocols that are not supported by OpenSSL.

**Comment by nabla-c0d3** [comment]
For now I will use this fork: https://github.com/PeterMosmans/openssl

**Comment by fabian-z** [comment]
Using the fork you specified instead of the official openssl 1.0.2 source, build runs fine and I get the following error on runtime (trying a regular scan):

```
[fabian@host sslyze-git]$ sslyze --regular example.org



 AVAILABLE PLUGINS
 -----------------

  SessionRenegotiationPlugin
  OpenSslCcsInjectionPlugin
  SessionResumptionPlugin
  OpenSslCipherSuitesPlugin
  CompressionPlugin
  CertificateInfoPlugin
  HstsPlugin
  FallbackScsvPlugin
  HeartbleedPlugin



 CHECKING HOST(S) AVAILABILITY
 -----------------------------

Traceback (most recent call last):
  File "/usr/bin/sslyze", line 676, in <module>
    main()
  File "/usr/bin/sslyze", line 551, in main
    raise exception
_nassl.OpenSSLError: 
error:140E0197:SSL routines:SSL_shutdown:shutdown while in init
```

Scan runs fine when compiled with https://www.openssl.org/source/old/1.0.2/openssl-1.0.2e.tar.gz.

**Comment by nabla-c0d3** [comment]
Did you try with the latest commit of the fork ? It has some fixes for SSL_Shutdown (https://github.com/PeterMosmans/openssl/commit/64193c8218540499984cd63cda41f3cd491f3f59) ?

**Comment by fabian-z** [comment]
Sure, I was using HEAD of branch 1.0.2-chacha as of yesterday and built 
with the master branches of sslyze/nassl checked out at the same time. 
The commit you pointed out must have been included in my build.

Am 06.03.2016 um 08:44 schrieb Alban Diquet:

**Comment by nabla-c0d3** [comment]
The fork causes some problems ( https://github.com/PeterMosmans/openssl/issues/37 ) so I will revert back to the official OpenSSL for now

**Comment by nabla-c0d3** [comment]
Also, OpenSSL 1.0.2g disables SSLv2 and has removed SSL2 weak ciphers, so it can't be used either.

**Comment by fabian-z** [comment]
Since I saw mentions of Windows in #139 and https://github.com/nabla-c0d3/nassl/commit/0ff01d0b7ff099c613f189804cdd81be7c325d74, I just wanted to note that this issue presents itself on Linux x86-64 for me. As mentioned above, using official OpenSSL 1.0.2e works well for me.

**Comment by PeterMosmans** [comment]
Hi, thanks for reporting the issues. I'll look into it (see https://github.com/PeterMosmans/openssl/issues/37 for more information).
@fabian-z have you tried the *latest* build of the vanilla OpenSSL version (1.0.2e is not the latest version and doesn't align with the fork) ? They should have similar results.

**Comment by fabian-z** [comment]
@PeterMosmans I just tried a build with official OpenSSL 1.0.2f, which seems to be the latest version on https://www.openssl.org/source/old/1.0.2/. This test build does not show the ```error:140E0197:SSL routines:SSL_shutdown:shutdown while in init``` error, so I think it is specific to your fork.

Anyways, @nabla-c0d3 requested that discussion of this issue shall continue in #139.

**Comment by itlabitto** [comment]
Any alternatives for adding modern ciphers? dumb question, any option for using 2 different version of OpenSSL? Tx.

**Comment by ericrange** [comment]
Maybe its possible to combine other approaches.
https://github.com/mjol/TLScan/blob/master/TLScan3.py

Use the "old" openssl (nassl) for things like Heartbleed and "no" openssl to scan ciphers.

**Comment by nabla-c0d3** [comment]
That's the plan - I started this work some time ago on the following branch in nassl https://github.com/nabla-c0d3/nassl/tree/double-trouble

**Comment by nabla-c0d3** [comment]
Closing this as a duplicate of #211
