### ISSUE TITLE
no attribute 'get_error_txt'

### ISSUE THREAD

**Issue by janderse** [nabla-c0d3/sslyze#117]
I'm trying to run the latest bleeding edge sslyze to get the fix for issue #113, because the host I'm scanning always asks for a certificate.

Pulled down the code, ran setup.py build on both Windows and Mac OS X.  Same error on both:

AVAILABLE PLUGINS
 -----------------

  PluginHSTS
  PluginCompression
  PluginSessionRenegotiation
  PluginChromeSha1Deprecation
  PluginHeartbleed
  PluginSessionResumption
  PluginCertInfo
  PluginOpenSSLCipherSuites

 CHECKING HOST(S) AVAILABILITY
 -----------------------------
Traceback (most recent call last):
  File "./sslyze.py", line 348, in <module>
    main()
  File "./sslyze.py", line 244, in main
    print ServersConnectivityTester.get_printable_result(targets_OK, targets_ERR)
  File "/Users/jonathana/sslyze2/utils/ServersConnectivityTester.py", line 184, in get_printable_result
    result_str += exception.get_error_txt()
AttributeError: 'exceptions.TypeError' object has no attribute 'get_error_txt'

**Comment by nabla-c0d3** [comment]
Can you send me the host's URL (via email)?

**Comment by janderse** [comment]
Unfortunately I can't provide the URL since it is a proprietary server that is not on the public internet.  But I'll see if I can get it to reproduce on another server.

**Comment by janderse** [comment]
The error seems to occur for any host.  For example:
./sslyze.py --regular google.com



 AVAILABLE PLUGINS
 -----------------

  PluginHSTS
  PluginCompression
  PluginChromeSha1Deprecation
  PluginSessionRenegotiation
  PluginCertInfo
  PluginOpenSSLCipherSuites
  PluginSessionResumption
  PluginHeartbleed



 CHECKING HOST(S) AVAILABILITY
 -----------------------------
Traceback (most recent call last):
  File "./sslyze.py", line 348, in <module>
    main()
  File "./sslyze.py", line 244, in main
    print ServersConnectivityTester.get_printable_result(targets_OK, targets_ERR)
  File "/Users/jonathana/sslyze2/utils/ServersConnectivityTester.py", line 184, in get_printable_result
    result_str += exception.get_error_txt()
AttributeError: 'exceptions.TypeError' object has no attribute 'get_error_txt'

Repro steps:
git clone https://github.com/nabla-c0d3/sslyze.git sslyze2
cd sslyze2
python setup.py build
python sslyze.py --regular google.com

I get this on Mac OS X 10.9.2 running Python 2.7.10, and also Windows 7 Enterprise SP1 64-bit running Python 2.7.10.  Do you see the same thing using these repro steps?

**Comment by nabla-c0d3** [comment]
You are probably using nassl 0.12 which is not compatible with bleeding edge SSLyze. If you want to do some testing, please build nassl bleeding first; it should be straightforward on a Linux or OS X system.
