### ISSUE TITLE
TLS Fallback SCSV Bug when analyzing F5 Loadbalancer Instances in v0.13.3

### ISSUE THREAD

**Issue by RedTechie** [nabla-c0d3/sslyze#119]
When running the new --fallback flag attribute angainst an F5 loadbalancer device that supports TLS_FALLBACK_SCSV you get the following:

Unhandled exception when processing --fallback:
SSLHandshakeRejected - TLS / Alert handshake failure

Command being executed:
sslyze_cli.exe --regular --hsts --certinfo_full www.f5.com:443

**Comment by nabla-c0d3** [comment]
It looks like F5 is not returning the right TLS alert (it should be "inappropriate fallback")... Not the first time they're doing things their way. I'll think about how to handle this.

**Comment by RedTechie** [comment]
Great thanks! It looks like SSLLabs.com shows when F5 devices have it enabled. Though granted no idea how they are going about their testing.
