### ISSUE TITLE
[Request] Support Server Cipher Order List

### ISSUE THREAD

**Issue by StephenShamakian** [nabla-c0d3/sslyze#120]
It would be awesome if the accepted ciphers for each protocol were listed in the order the server accepts them. That's very useful when debugging cipher handshake issues with clients as one will know what cipher order the server prefers.

**Comment by tykkz** [comment]
I want to work on this request.

Some servers obey the client side cipher suite order and select the first one from the list offered by the client. But some other servers prefer to select the cipher based on their own selection list (prefer to use -arguably- better ciphers). For example; Google has its own selection order for ciphers and omits the order from the client.

Therefore, the first thing to do is to check whether the server has its own cipher suite preference order or not. I think the following method will help us in this matter:
- We select two ciphers (e.g. _cipherA_ and _cipherB_) from the `accepted_cipher_list` and initiate two SSL connections using these ciphers (one connection with _cipherA_-_cipherB_ as the client order and another connection with _cipherB_-_cipherA_ as the client order).
- If the server obeys the client order, then it would select the first cipher from these two connection requests. If not, then the server will select either the _cipherA_ or _cipherB_ for both connection requests, based on its preference list.
- This way, we will know whether the server keeps its own preference list or not.

If this works out for you @nabla-c0d3, then I will do the implementation and send a PR.

Btw, I am also thinking on the best method to sort the `accepted_cipher_list` according to the server side cipher preference list. I will write here when I find a reasonable solution.

**Comment by nabla-c0d3** [comment]
Yes this sounds good - let's start with what you described and add to the result to the output as something like this:

    Cipher suite preference: Server order / Client order

Sorting the `accepted_cipher_list` seems very tricky if the server uses its own order so I don't think it's worth implementing it.

**Comment by tykkz** [comment]
I am almost done with the implementation. I would be very glad if you can assign this Github issue to me @nabla-c0d3? My instructor wants to make sure that I am the only person working on this feature request. Thank you!

Now, I would like to point out the modifications that I've done, before sending a PR:

1. Only modified the `OpenSslCipherSuitesPlugin` plugin to add this feature.
2. Introduced an option  named as `--check_server_preference` that triggers this feature. (If you want, I can remove this option and check for "cipher suite preference" at every run of sslyze.)
3. Added `openssl_cipher_name` to the `AcceptedCipherSuite` class. (I need this to create two SSL connections that I have mentioned earlier. It's costly to find the openssl name from `OPENSSL_TO_RFC_NAMES_MAPPING ` dictionary.)
4. Printed the result in the way you requested. It's before the prefered cipher. You can see the sample output below.

If this works out for you, I will send the pull request in a few days.

![test](https://cloud.githubusercontent.com/assets/365377/20322885/5617c0d8-ab83-11e6-9c4e-4b6edad95644.png)

**Comment by nabla-c0d3** [comment]
Awesome!
To answer your question, there is no need to add `--check_server_preference`, let's just always check (to avoid making the command line even more complex).
For some reason GitHub isn't letting me assign this issue to you (your name does not show up in the Assignees list), but I think it will be possible once you open the pull request?
Thanks!
