### ISSUE TITLE
api_sample get into an infinite loop on windows

### ISSUE THREAD

**Issue by tjanssl** [nabla-c0d3/sslyze#127]
On linux it works like a charm:
![sslyze_linux](https://cloud.githubusercontent.com/assets/13731394/12843967/74ce9052-cbf4-11e5-855a-be886865167d.PNG)
but on windows it gets into an infinite loop:
![sslize_win](https://cloud.githubusercontent.com/assets/13731394/12843966/74cd01d8-cbf4-11e5-885c-8efe3bb78373.PNG)

**Comment by nabla-c0d3** [comment]
Thanks

**Comment by tjanssl** [comment]
Hi,

now I've got an error while runnig 
`python api_sample.py` 

the error message:

> AttributeError: 'PluginRaisedExceptionResult' object has no attribute 'accepted_cipher_list'

if I try to run 
`python sslyze_cli.py 192.168.1.249 --tlsv1_2`

I've go an error
`
Unhandled exception when processing --tlsv1_2:
TypeError - Invalid session
`

With the version  0.12 it was working
Any suggestions?
Thanks in advance
