### ISSUE TITLE
[Bug] Hard exception when scanning some SSL sites

### ISSUE THREAD

**Issue by RedTechie** [nabla-c0d3/sslyze#129]
When scanning a SSL site on a product from CA called Layer7 I keep getting a nasty exception result from sslyze. I have tried it with the DNS alias also with no difference. Is there a way I can perform a search with more verbose logging to help isolate the issue?

Version 0.13.3:
` AVAILABLE PLUGINS
 -----------------

  CompressionPlugin
  SessionResumptionPlugin
  OpenSslCcsInjectionPlugin
  SessionRenegotiationPlugin
  HstsPlugin
  HeartbleedPlugin
  CertificateInfoPlugin
  FallbackScsvPlugin
  OpenSslCipherSuitesPlugin

 CHECKING HOST(S) AVAILABILITY
 -----------------------------

Traceback (most recent call last):
  File "sslyze_cli.py", line 630, in <module>
  File "sslyze_cli.py", line 532, in main
_nassl.OpenSSLError:
error:1418C197:SSL routines:ssl3_shutdown:shutdown while in init`

Version 0.12:
`

 AVAILABLE PLUGINS
 -----------------

  PluginHeartbleed
  PluginCertInfo
  PluginCompression
  PluginChromeSha1Deprecation
  PluginSessionResumption
  PluginSessionRenegotiation
  PluginOpenSSLCipherSuites
  PluginHSTS

 CHECKING HOST(S) AVAILABILITY
 -----------------------------

   167.69.70.101:443                   => 167.69.70.101:443

 SCAN RESULTS FOR 167.69.70.101:443 - 167.69.70.101:443
 ------------------------------------------------------

Unhandled exception when processing --compression: 
exceptions.AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'

Unhandled exception when processing --reneg: 
exceptions.AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'

  * OpenSSL Heartbleed:
      OK - Not vulnerable to Heartbleed  

Unhandled exception when processing --certinfo: 
exceptions.AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'

  * SSLV2 Cipher Suites:
      Server rejected all cipher suites.

  * TLSV1_2 Cipher Suites:
      Undefined - An unexpected error happened: 
                 RC4-SHA                             AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 RC4-MD5                             AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 EDH-RSA-DES-CBC3-SHA                AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 ECDHE-RSA-RC4-SHA                   AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 ECDHE-RSA-DES-CBC3-SHA              AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 ECDHE-RSA-AES256-SHA384             AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 ECDHE-RSA-AES256-SHA                AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 ECDHE-RSA-AES256-GCM-SHA384         AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 ECDHE-RSA-AES128-SHA256             AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 ECDHE-RSA-AES128-SHA                AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 ECDHE-RSA-AES128-GCM-SHA256         AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 DHE-RSA-AES256-SHA                  AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 DHE-RSA-AES256-GCM-SHA384           AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 DHE-RSA-AES128-SHA                  AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 DHE-RSA-AES128-GCM-SHA256           AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 DES-CBC3-SHA                        AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 AES256-SHA                          AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 AES256-GCM-SHA384                   AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 AES128-SHA                          AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 AES128-GCM-SHA256                   AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'

  * Session Resumption:
      With Session IDs:                  ERROR (0 successful, 0 failed, 5 errors, 5 total attempts).
        ERROR #1: AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
        ERROR #2: AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
        ERROR #3: AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
        ERROR #4: AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
        ERROR #5: AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
      With TLS Session Tickets:          ERROR: AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'

  * TLSV1_1 Cipher Suites:
      Undefined - An unexpected error happened: 
                 RC4-SHA                             AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 RC4-MD5                             AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 EDH-RSA-DES-CBC3-SHA                AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 EDH-RSA-DES-CBC-SHA                 AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 ECDHE-RSA-RC4-SHA                   AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 ECDHE-RSA-DES-CBC3-SHA              AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 ECDHE-RSA-AES256-SHA                AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 ECDHE-RSA-AES128-SHA                AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 DHE-RSA-AES256-SHA                  AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 DHE-RSA-AES128-SHA                  AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 DES-CBC3-SHA                        AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 DES-CBC-SHA                         AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 AES256-SHA                          AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 AES128-SHA                          AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'

  * TLSV1 Cipher Suites:
      Undefined - An unexpected error happened: 
                 SEED-SHA                            OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 NULL-SHA                            OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 NULL-MD5                            OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 IDEA-CBC-SHA                        OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 EXP-RC4-MD5                         OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 EXP-RC2-CBC-MD5                     OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 EXP-EDH-RSA-DES-CBC-SHA             OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 EXP-EDH-DSS-DES-CBC-SHA             OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 EXP-DES-CBC-SHA                     OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 EXP-ADH-RC4-MD5                     OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 EXP-ADH-DES-CBC-SHA                 OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 EDH-DSS-DES-CBC3-SHA                OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 EDH-DSS-DES-CBC-SHA                 OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 ECDHE-RSA-NULL-SHA                  OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 ECDHE-ECDSA-RC4-SHA                 OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 ECDHE-ECDSA-NULL-SHA                OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 ECDHE-ECDSA-DES-CBC3-SHA            OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 ECDHE-ECDSA-AES256-SHA              OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 ECDHE-ECDSA-AES128-SHA              OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 ECDH-RSA-RC4-SHA                    OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 ECDH-RSA-NULL-SHA                   OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 ECDH-RSA-DES-CBC3-SHA               OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 ECDH-RSA-AES256-SHA                 OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 ECDH-RSA-AES128-SHA                 OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 ECDH-ECDSA-RC4-SHA                  OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 ECDH-ECDSA-NULL-SHA                 OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 ECDH-ECDSA-DES-CBC3-SHA             OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 ECDH-ECDSA-AES256-SHA               OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 ECDH-ECDSA-AES128-SHA               OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 DHE-RSA-SEED-SHA                    OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 DHE-RSA-CAMELLIA256-SHA             OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 DHE-RSA-CAMELLIA128-SHA             OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 DHE-DSS-SEED-SHA                    OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 DHE-DSS-CAMELLIA256-SHA             OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 DHE-DSS-CAMELLIA128-SHA             OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 DHE-DSS-AES256-SHA                  OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 DHE-DSS-AES128-SHA                  OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 DH-RSA-SEED-SHA                     OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 DH-RSA-DES-CBC3-SHA                 OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 DH-RSA-DES-CBC-SHA                  OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 DH-RSA-CAMELLIA256-SHA              OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 DH-RSA-CAMELLIA128-SHA              OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 DH-RSA-AES256-SHA                   OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 DH-RSA-AES128-SHA                   OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 DH-DSS-SEED-SHA                     OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 DH-DSS-DES-CBC3-SHA                 OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 DH-DSS-DES-CBC-SHA                  OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 DH-DSS-CAMELLIA256-SHA              OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 DH-DSS-CAMELLIA128-SHA              OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 DH-DSS-AES256-SHA                   OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 DH-DSS-AES128-SHA                   OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 CAMELLIA256-SHA                     OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 CAMELLIA128-SHA                     OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 AECDH-RC4-SHA                       OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 AECDH-NULL-SHA                      OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 AECDH-DES-CBC3-SHA                  OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 AECDH-AES256-SHA                    OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 AECDH-AES128-SHA                    OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 ADH-SEED-SHA                        OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 ADH-RC4-MD5                         OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 ADH-DES-CBC3-SHA                    OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 ADH-DES-CBC-SHA                     OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 ADH-CAMELLIA256-SHA                 OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 ADH-CAMELLIA128-SHA                 OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 ADH-AES256-SHA                      OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 ADH-AES128-SHA                      OpenSSLError - 
error:14094417:SSL routines:ssl3_read_bytes:sslv3 alert illegal parameter
                 RC4-SHA                             AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 RC4-MD5                             AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 EDH-RSA-DES-CBC3-SHA                AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 EDH-RSA-DES-CBC-SHA                 AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 ECDHE-RSA-RC4-SHA                   AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 ECDHE-RSA-DES-CBC3-SHA              AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 ECDHE-RSA-AES256-SHA                AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 ECDHE-RSA-AES128-SHA                AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 DHE-RSA-AES256-SHA                  AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 DHE-RSA-AES128-SHA                  AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 DES-CBC3-SHA                        AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 DES-CBC-SHA                         AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 AES256-SHA                          AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'
                 AES128-SHA                          AttributeError - 'HTTPSConnection' object has no attribute 'get_client_ca_list'

  * SSLV3 Cipher Suites:
      Server rejected all cipher suites.

 SCAN COMPLETED IN 27.53 S
 -------------------------

**Comment by nabla-c0d3** [comment]
Can you try with the master branch ? This might be a duplicate of a bug I fixed recently.

**Comment by RedTechie** [comment]
Having issues building the python to exe and also running it natively as python. Can't use pip either as our proxy is blocking its access. Curious when is the next release with the latest fixes?

**Comment by nabla-c0d3** [comment]
I am waiting for a few more bugs to surface so I can fix them, but it should be soon.

**Comment by nabla-c0d3** [comment]
It's released now - let me know if it fixed the bug.

**Comment by RedTechie** [comment]
Thanks! Will test it tomorrow and report back.

**Comment by RedTechie** [comment]
Still errors out:

`
sslyze_cli.exe --regular 167.69.70.101



 AVAILABLE PLUGINS
 -----------------

  SessionRenegotiationPlugin
  HstsPlugin
  HeartbleedPlugin
  CertificateInfoPlugin
  FallbackScsvPlugin
  OpenSslCipherSuitesPlugin
  SessionResumptionPlugin
  CompressionPlugin
  OpenSslCcsInjectionPlugin



 CHECKING HOST(S) AVAILABILITY
 -----------------------------

Traceback (most recent call last):
  File "sslyze_cli.py", line 675, in <module>
  File "sslyze_cli.py", line 551, in main
_nassl.OpenSSLError:
error:1418C197:SSL routines:ssl3_shutdown:shutdown while in init`

**Comment by fabian-z** [comment]
I see this behaviour when compiling with the suggested [openssl fork](https://github.com/PeterMosmans/openssl/) instead of the [official 1.0.2e sources](https://www.openssl.org/source/old/1.0.2/openssl-1.0.2e.tar.gz). (Wrote it up in #116 before seeing this issue.)
Maybe you could try compiling from source with the original openssl to see if that fixes your problem?
If you need some pointers on the build process, you can get an idea from my [sslyze-git PKGBUILD](https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=sslyze-git)

**Comment by nabla-c0d3** [comment]
Thanks for looking into this; closing this issue as a duplicate of #139.
