### ISSUE TITLE
api_sample fails on windows 64

### ISSUE THREAD

**Issue by tjanssl** [nabla-c0d3/sslyze#131]
Hi,

now I've got an error while runnig 
`python api_sample.py` 

the error message:

> AttributeError: 'PluginRaisedExceptionResult' object has no attribute 'accepted_cipher_list'

if I try to run 
`python sslyze_cli.py 192.168.1.249 --tlsv1_2`

I've go an error
`
Unhandled exception when processing --tlsv1_2:
TypeError - Invalid session
`

With the version  0.12 it was working
Any suggestions?
Thanks in advance

**Comment by nabla-c0d3** [comment]
What kind of server are you scanning ? Are you using client certificates ?

**Comment by tjanssl** [comment]
Anyways if I try to scan any host I got the same results:
![sslize_windows](https://cloud.githubusercontent.com/assets/13731394/13015605/e21cd1ce-d1b1-11e5-8619-60e9dcbba415.PNG)

**Comment by nabla-c0d3** [comment]
I am unable to reproduce this; which version of Windows are you using ? Are you running the 32 bits or 64 bit Python interpreter ?

**Comment by tjanssl** [comment]
Windows 7 64 bit with Python 2.7.9 64bit

**Comment by tjanssl** [comment]
The problem is with the nassl.
For the command python run_tests.py it thorws error
![nassl](https://cloud.githubusercontent.com/assets/13731394/13468140/3f95ea5c-e099-11e5-9ac4-750cb1598866.PNG)

**Comment by nabla-c0d3** [comment]
Fixed in https://github.com/nabla-c0d3/nassl/commit/86472251002da685871f40e2ed13537f252268e8#diff-f52ec599d1b6e820081949c345efa3a1L548 and nassl 0.13.4.
