### ISSUE TITLE
Test for Google CA Store may not be what sslyze intended

### ISSUE THREAD

**Issue by konklone** [nabla-c0d3/sslyze#135]
I tested out `sslyze` on a server I help administer which uses a certificate from Let's Encrypt, and it was registered as trusted by every CA store except for Google's:

```
  * Certificate - Trust:
      Hostname Validation:               OK - Subject Alternative Name matches 18f.gsa.gov
      Mozilla NSS CA Store (02/2016):    OK - Certificate is trusted
      Microsoft CA Store (02/2016):      OK - Certificate is trusted
      Java 6 CA Store (Update 65):       OK - Certificate is trusted
      Apple CA Store (OS X 10.11.3):     OK - Certificate is trusted
      Google CA Store (02/2016):         FAILED - Certificate is NOT Trusted: unable to get local issuer certificate
```

I dug into `catt` and [it looks like](https://github.com/nabla-c0d3/catt/blob/master/sslyze.md#google) you're pulling from https://pki.google.com/roots.pem for the `Google CA Store`.

On the [Google PKI FAQ](https://pki.google.com/faq.html), this root file is referenced as a store of certificates to use when connecting to _Google services_:

![image](https://cloud.githubusercontent.com/assets/4592/13211728/0923c6ac-d909-11e5-86b8-d2a7865f4334.png)

In other words, unlike the other root stores used by `sslyze`, this root store is not relevant to determining whether a certificate is trusted by a particular platform. This explains why it does not include Identrust, Let's Encrypt's cross-signer, yet Let's Encrypt certs are accepted just fine on Chrome and Android.

My understanding of Google's [root certificate program policies](https://www.chromium.org/Home/chromium-security/root-ca-policy#TOC-Root-Certificate-Programs) is that Chrome typically defers to the underlying OS for a root store. 

For Android, they link to their bug tracker, and some searching around shows that they [generally](https://code.google.com/p/android/issues/detail?id=59811&can=1&q=root%20certificate&colspec=ID%20Status%20Priority%20Owner%20Summary%20Stars%20Reporter%20Opened) make Mozilla review [a prerequisite](https://code.google.com/p/android/issues/detail?id=60439&can=1&q=root%20certificate&colspec=ID%20Status%20Priority%20Owner%20Summary%20Stars%20Reporter%20Opened), and then follow [undisclosed internal policies and private discretion](https://code.google.com/p/android/issues/detail?id=57624&can=1&q=root%20certificate&colspec=ID%20Status%20Priority%20Owner%20Summary%20Stars%20Reporter%20Opened) on whether to accept a CA.

[This 2013 comment](https://code.google.com/p/android/issues/detail?id=57624#c3) has a Google team member placing the AOSP certificate store at `libcore/luni/src/main/files/cacerts`. However, when I checked out [libcore from source](https://android.googlesource.com/platform/libcore/), the `libcore/luni/src/main` directory didn't have a `files/` directory.

Going to [libcore2](https://android.googlesource.com/platform/libcore2/) did have this directory, and it listed the following filenames:

```
$ ls
00673b5b.0  2fa87019.0  594f1775.0  81b9768f.0  aeb67534.0  ddc328ff.0
03e16f6c.0  2fb1850a.0  5a3f0ff8.0  8470719d.0  b0f3e76e.0  e48193cf.0
08aef7bb.0  33815e15.0  5a5372fc.0  84cba82f.0  b7db1890.0  e60bf0c0.0
0d188d89.0  343eb6cb.0  5cf9d536.0  85cde254.0  bc3f2570.0  e775ed2d.0
10531352.0  399e7759.0  5e4e69e7.0  86212b19.0  bcdd5959.0  e7b8d656.0
111e6273.0  3a3b02ce.0  60afe812.0  87753b0d.0  bda4cc84.0  e8651083.0
1155c94b.0  3ad48a91.0  635ccfd5.0  882de061.0  bdacca6f.0  ea169617.0
119afc2e.0  3c58f906.0  67495436.0  895cad1a.0  bf64f35b.0  eb375c3e.0
11a09b38.0  3c860d51.0  69105f4f.0  89c02a45.0  c215bc69.0  ed049835.0
12d55845.0  3d441de8.0  6adf0799.0  8f7b96c4.0  c33a80d4.0  ed524cf5.0
17b51fe6.0  3e7271e8.0  6e8bf996.0  9339512a.0  c3a6a9ad.0  ee7cd6fb.0
1920cacb.0  418595b9.0  6fcc125d.0  95aff9e3.0  c527e4ab.0  f4996e82.0
1dac3003.0  455f1b52.0  72f369af.0  9685a493.0  c7e2a638.0  f58a60fe.0
1dbdda5b.0  46b2fd3b.0  72fa7371.0  9772ca32.0  c8763593.0  f61bff45.0
1dcd6f4c.0  48478734.0  74c26bd0.0  9d6523ce.0  ccc52f49.0  f80cc7f6.0
1df5ec47.0  4d654d1d.0  75680d2e.0  9dbefe7b.0  cdaebb72.0  fac084d7.0
1e1eab7c.0  4e18c148.0  7651b327.0  9f533518.0  cf701eeb.0  facacbc6.0
1e8e7201.0  4fbd6bfa.0  76579174.0  a0bc6fbb.0  d16a5865.0  fb126c6d.0
1eb37bdf.0  5021a0a2.0  7672ac4b.0  a15b3b6b.0  d537fba6.0  fde84897.0
219d9499.0  5046c355.0  7999be0d.0  a3896b44.0  d59297b8.0  ff783690.0
23f4c490.0  524d9b43.0  7a481e66.0  a7605362.0  d64f06f3.0
27af790d.0  56b8a0b6.0  7a819ef2.0  a7d2cf64.0  d777342d.0
2afc57aa.0  57692373.0  7d3cd826.0  ab5346f4.0  d8274e24.0
2e8714cb.0  58a44af1.0  7d453d8f.0  add67345.0  dbc54cab.0
```

A `README.cacerts` file in that directory gave the following documentation:

```
The filenames in the cacerts directory are in the format of <hash>.<n>
where "hash" is the subject hash produced by:

    openssl x509 -subject_hash -in filename

and the "n" is a unique integer identifier starting at 0 to deal
with collisions. See OpenSSL's c_rehash manpage for details.
```

In any case -- whether you think the above Android store is worth including, I think `sslyze` should consider removing the current Google CA Store from the certificate checks, as it is not like the other CA stores `sslyze` uses to evaluate platform support.

**Comment by konklone** [comment]
(Also, as Google notes, Android gets customized by manufacturers around the world and there's no guarantee that being included in the AOSP root store will get you into all Android phones. But that's basically the same situation as the Mozilla root store and ordinary Linux, so it's probably fine to go with.)

**Comment by nabla-c0d3** [comment]
Good catch and analysis - thanks! I'll remove it.

**Comment by pzb** [comment]
Note that Android seems to have moved the trust anchors here: https://android.googlesource.com/platform/system/ca-certificates/+/master

**Comment by nabla-c0d3** [comment]
It might be useful to add the Android "stock" trust store.

**Comment by konklone** [comment]
It looks like Google has made the CA Store standard across Android (through its Compatibility Document), as of Android N (Nougat):

https://android-developers.blogspot.com/2016/07/changes-to-trusted-certificate.html

They link to https://android.googlesource.com/platform/system/ca-certificates/ as the official location.

**Comment by nabla-c0d3** [comment]
Yeah I saw - it makes having the AOSP trust store in SSLyze a lot more useful.
