### ISSUE TITLE
IOError - BIO_write() failed

### ISSUE THREAD

**Issue by clviper** [nabla-c0d3/sslyze#136]
Hi there.

I am using the latest version available.

When running python sslyze_cli.py --regular <particularIp> I am getting:

**Unhandled exception when processing --tlsv1:
IOError - BIO_write() failed

Unhandled exception when processing --sslv3:
IOError - BIO_write() failed**

Any ideas of what this error is?

Thank you.

**Comment by nabla-c0d3** [comment]
Why platform are you using? Windows ?

**Comment by clviper** [comment]
No. Debian x64 (Kali).
Em 24/02/2016 7:52 da tarde, "Alban Diquet" <notifications@github.com>
escreveu:

**Comment by nabla-c0d3** [comment]
Can be reproduced by running:

    python sslyze_cli.py --hsts billing.mayngames.com
