### ISSUE TITLE
Import useful code/concepts from certlint and the crt.sh service?

### ISSUE THREAD

**Issue by bknowles** [nabla-c0d3/sslyze#137]
Folks,

Got this in the most recent Fiesty Duck TLS news from the folks at SSLabs:

> Peter Bowen from Amazon developed the tool certlint to check for several common errors in X.509 certificates. The source code is available on Github and the tool has been integrated into the crt.sh service, a web interface that provides access to the Certificate Transparency logs. Certlint identified several hundred errors and several thousand warnings in valid certificates.

Don't know if this would be useful to you, but thought I'd point it out and let you take a look at it to see if there was anything of interest.

**Comment by nabla-c0d3** [comment]
Hi,
Thanks for the link - I hadn't heard of this project and it is very interesting. However, SSLyze is about finding configuration issues affecting SSL servers; finding errors within X509 certificates, while very related to SSL issues, is a whole different (and complex) beast. Hence it is better to have that in a separate tool.
Thanks!
