### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by blkperl** [nabla-c0d3/sslyze#138]
The readme is unclear what versions of python are supported

**Comment by nabla-c0d3** [comment]
It is Python 2.7 - Python3 support is not on the roadmap.

**Comment by tuler** [comment]
Can you give a hint on what needs to be done to support python 3?

**Comment by nabla-c0d3** [comment]
The biggest part is the C extension, which needs to be ported to Python 3: https://github.com/nabla-c0d3/nassl

**Comment by tuler** [comment]
Development is under way at https://github.com/siteblindado/nassl/tree/python3

**Comment by tuler** [comment]
It's compiling without errors or warnings.
But tests are not passing yet.

**Comment by garrettr** [comment]
@nabla-c0d3 Would you be opposed to maintaining sslyze for Python 3, if the initial work of porting it were done by external contributors? @tuler seems to be making progress on their branch. If so, could we reopen this issue (or open a new issue) to track integration into upstream?

I'm also happy to help with the transition in any way that I can.

**Comment by tuler** [comment]
Our first goal is to get it to work (to pass all tests).
Then we'll review the changes to make them as little as possible and compatible with both 2 and 3.

**Comment by nabla-c0d3** [comment]
If the work of porting is done, I can try maintaining sslyze/nassl for Python 3. Nassl is especially a concern because Python 3 support doubles the number of builds/platforms I need to validate every time I make a release, but I'm willing to give it a try.

**Comment by garrettr** [comment]
@tuler Any progress on the port to Python 3?

**Comment by ericrange** [comment]
we need python 3! :(

**Comment by nabla-c0d3** [comment]
I've completed Python 3 support for the nassl C extension ( https://github.com/nabla-c0d3/nassl/pull/48 ). SSLyze is next... 
I will most likely only support Python 3.6 on macOS and Linux (not Windows until I fully drop Python 2 support, which could be very soon).

**Comment by tuler** [comment]
Great news! We didn't have enough time to work on it :-(

**Comment by ericrange** [comment]
what does that mean? python 3 project canceled?

**Comment by nabla-c0d3** [comment]
It's ongoing, you can see the progress in the Python3 branch: https://github.com/nabla-c0d3/sslyze/tree/python3

**Comment by gabimaxi** [comment]
What would be the status of the conversion, is it possible to run some test (testing purposes only). thank you

**Comment by nabla-c0d3** [comment]
It is very close to being done. Once I release the new version of nassl and merge the python3 branch into master (probably today) you will be able to test it,

**Comment by gabimaxi** [comment]
That is great, much appreciated your work on this. Thank you.

**Comment by nabla-c0d3** [comment]
It's on master now.

**Comment by nabla-c0d3** [comment]
It's released.
