### ISSUE TITLE
Skip client cert request in 0.12

### ISSUE THREAD

**Issue by burgerzoid** [nabla-c0d3/sslyze#141]
Thanks for sslyze, it has proved to be very useful. 

Am failing to get full cipher info when the server requests a client cert in 0.12. Unfortunately at the present time am not able to update to 0.13 which appears to deal with this situation.

Have applied https://github.com/ralphdolmans/nassl/commit/45bfb71602d40dfd673a3e9c92b6d71fe32a1434 which fixes a typo in SslClient.py. 

Now get output like the following when client cert is requested: 

* SSLV3 Cipher Suites:
Undefined - An unexpected error happened:
RC4-SHA    
ClientCertificateRequested - Server requested a client certificate issued by one of the following CAs:

Can see in 0.13 where it re-connects when the server requests a client cert but one is not provided. But is not clear to me how to make equivalent changes in 0.12. 

Can anyone provide any info on what needs to be done to deal with optional client certs in 0.12? I realise this won't be a priority, being an older version, but would appreciate any assistance.

**Comment by nabla-c0d3** [comment]
Hi,
What prevents you from updating? I did several changes/commits in v0.13 to handle this specific scenario.

**Comment by burgerzoid** [comment]
Hello, the python 2.7 dependency prevents us from updating.

Our relevant servers are Centos 6 with python 2.6 which version 0.12 runs on. It is not feasible to either install python 2.7 or upgrade servers at this stage.

Am just looking for some pointers as to where in 0.12 changes are required to deal with or ignore optional client cert requests. Any assistance much appreciated.

**Comment by nabla-c0d3** [comment]
It is surprising because v0.12 was for Python 2.7 only. How did you get it to run on 2.6? Regardless, the fixes for client certificate handling are both in https://github.com/nabla-c0d3/nassl and sslyze and in several separate commits. I don't think I use anything that's specific to 2.7, so your best bet would be to compile nassl for 2.6 (which should be easy on Linux) and use the current version of SSLyze.
