### ISSUE TITLE
Apache Trafficserver

### ISSUE THREAD

**Issue by szepeviktor** [nabla-c0d3/sslyze#143]
Is it possible to assess the cert of a forward web proxy listening on 8080?

**Comment by nabla-c0d3** [comment]
Yes, look at the --https_tunnel command

**Comment by szepeviktor** [comment]
@nabla-c0d3 I meant to assess of a proxy server itself.
Later I've realized ATS has to be told [to listen with ssl](https://trafficserver.readthedocs.org/en/latest/admin-guide/files/records.config.en.html#proxy-config-http-server-ports), then it works without any options.
