### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by sqqqs** [nabla-c0d3/sslyze#145]
Win10x64, Python 2.7.10 (Activestate).

```
sslyze_cli.py --regular www.yahoo.com:443 www.google.com
......
  * SSLV2 Cipher Suites:
      Server rejected all cipher suites.



Traceback (most recent call last):
  File "C:\Script\SSLyze\sslyze_cli.py", line 678, in <module>
    main()
  File "C:\Script\SSLyze\sslyze_cli.py", line 588, in main
    print _format_txt_target_result(server_info, result_list)
  File "C:\Script\SSLyze\sslyze_cli.py", line 442, in _format_txt_target_result
    target_result_str += line + '\n'
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcf in position 22: ordinal not in range(128)
```
What's wrong with encodings?

**Comment by sqqqs** [comment]
Update.
If
`sslyze_cli.py --regular www.google.com`
then the execution is without error.

If
`sslyze_cli.py --regular www.yahoo.com:443`
then the execution is with UnicodeDecodeError.

**Comment by nabla-c0d3** [comment]
Hello,
I am unable to reproduce this when scanning `www.yahoo.com:443`; where are you scanning this host from ?
Thanks!

**Comment by sqqqs** [comment]
Hello,

> where are you scanning

What do you want me to say? Country? ISP? DNS? Windows code page?
May be Ukraine. System code page for non-unicode program - Windows 1251.

> I am unable to reproduce this when scanning

Around 10% of cases, yahoo scanning works without error. Try several times to start the scan.
Here's a video with this bug: https://youtu.be/pwsSLZq_ZMk

**Comment by nabla-c0d3** [comment]
I am still unable to reproduce this so I tried to commit a "blind" fix based on what I think the problem is. Can you test the current master branch to see if the fix solved that issue ? Thanks!

**Comment by sqqqs** [comment]
Your patch did not help :(

I added the following lines

```
#! / Usr / bin / env python2.7
# - * - Coding: - * utf-8 -
import json
import os
import sys
reload (sys)
sys.setdefaultencoding ( 'cp1251')

from sslyze import __version__, PROJECT_URL
```
Now everything is working correctly, but it's a bad decision.
