### ISSUE TITLE
Too many connections

### ISSUE THREAD

**Issue by szepeviktor** [nabla-c0d3/sslyze#146]
Courier-MTA says: `esmtpd-ssl: Maximum connection limit reached `

Is there a way limit connections to - for example - 1?

**Comment by nabla-c0d3** [comment]
Hi,
No that's not possible right now. Do you know that the limit is for Courier-MTA ? Can you try setting `DEFAULT_MAX_PROCESSES_NB ` and `DEFAULT_PROCESSES_PER_HOSTNAME_NB ` to 1 in this file: https://github.com/nabla-c0d3/sslyze/blob/master/sslyze/plugins_process_pool.py#L15 .
Thanks!

**Comment by szepeviktor** [comment]
> Do you know what the limit is for Courier-MTA ?

It was 4/IP. I've raised that to 40 and the sslyze ran well.
Thanks.

ps. Later I've found your constants.
