### ISSUE TITLE
Certificate leaf EV not set to true

### ISSUE THREAD

**Issue by marcvdm** [nabla-c0d3/sslyze#147]
when i run sslyze with `--json_out=-` it wil send 'is_leaf_certificate_ev' with the result. The problem is that is is always false. 

`slyze_cli.py www.mozilla.org --certinfo_basic --json_out=-`

returns
`"is_leaf_certificate_ev": false,`

but `2.16.840.1.114412.2.1` is in the store
https://github.com/nabla-c0d3/sslyze/blob/master/sslyze/plugins/certificate_info_plugin.py#L48
```
"X509v3 Certificate Policies": {
    "CPS": [
        "https://www.digicert.com/CPS"
    ],
    "Policy": [
        "2.16.840.1.114412.2.1",
        "2.23.140.1.1"
    ]
}
```

Maybe the comparison function is not working correctly or the export! (not a python developer)

**Comment by nabla-c0d3** [comment]
Good catch... Fixed in https://github.com/nabla-c0d3/sslyze/commit/83ec8d9f63c4b1a41930e90c9953c342757bb5fb
Thanks!
