### ISSUE TITLE
false negative with SMTP servers with mandatory TLS/SSL and mutual auth

### ISSUE THREAD

**Issue by monotoy** [nabla-c0d3/sslyze#148]
running 

python sslyze_cli.py --starttls=smtp --sslv2 --sslv3 --hide_rejected_ciphers mx.example.com

will result in 
- SSLV2 Cipher Suites:
    Server rejected all cipher suites.

when the server requires TLS and a client certificate, even though the server actually supports SSLv2.

**Comment by nabla-c0d3** [comment]
Do you know of a public server which I can use to reproduce this issue? You could email the hostname to me if that's the case. Otherwise it will be difficult for me to troubleshoot this issue.
Thanks!
