### ISSUE TITLE
How to get "long" SSL Cipher Suite Names

### ISSUE THREAD

**Issue by mr-gosh** [nabla-c0d3/sslyze#15]
at the moment sslyze exports or prints only the shortened cipher suite names, which is a bit difficult to parse...
Perhaps it would be helpful to integrate an export option for long cipher suite names, or is something like that already possible?

I found this discription on the openssl site:

https://www.openssl.org/docs/apps/ciphers.html#CIPHER_SUITE_NAMES

**Comment by nabla-c0d3** [comment]
I will just switch to canonical cipher suite names, as described in issue #66
