### ISSUE TITLE
Error "Unhandled exception when processing --sslv3:" when using sslyze_cli.py

### ISSUE THREAD

**Issue by clviper** [nabla-c0d3/sslyze#151]
Hi there.

I receive the following error while using sslyze_cli.py --regular on a particular host:

"Unhandled exception when processing --sslv3:
SslError - Connection was shut down by peer"

If I use the --sslv3 parameter only, the test succeeds.

I am using python 2.7.9 and sslyze 0.13.5.

Thank you.

**Comment by nabla-c0d3** [comment]
The server is not able to handle the many connections initiated when running --regular. In that scenario it is better to run each commands separately.
