### ISSUE TITLE
Certificate - Trust

### ISSUE THREAD

**Issue by leebaird** [nabla-c0d3/sslyze#152]
GoDaddy certs are showing up a FAILED.

`  * Certificate - Trust:
      Hostname Validation:               OK - Subject Alternative Name matches
      Google CA Store (09/2015):         FAILED - Certificate is NOT Trusted: unable to get local issuer certificate
      Java 6 CA Store (Update 65):       FAILED - Certificate is NOT Trusted: unable to get local issuer certificate
      Microsoft CA Store (09/2015):      FAILED - Certificate is NOT Trusted: unable to get local issuer certificate
      Apple CA Store (OS X 10.10.5):     FAILED - Certificate is NOT Trusted: unable to get local issuer certificate
      Mozilla NSS CA Store (09/2015):    FAILED - Certificate is NOT Trusted: unable to get local issuer certificate
`

**Comment by nabla-c0d3** [comment]
The certificate seems trusted when running:

    $ python sslyze_cli.py --certinfo_basic www.godaddy.com
