### ISSUE TITLE
SHA-1 signature check is too strict

### ISSUE THREAD

**Issue by rdegraaf** [nabla-c0d3/sslyze#155]
Hello,

The check for SHA-1-based signatures in a certificate chain is currently unnecessarily strict: it fails if the self-signed root certificate is signed using SHA-1.  The signature on a root certificate is irrelevant; root certificates are trusted based on their identity, not based on their signatures.  Even Google still uses a root certificate signed using SHA-1.  See https://www.entrust.com/need-sha-2-signed-root-certificates/ for some more details and commentary.

**Comment by nabla-c0d3** [comment]
The check already ensures that if the certificate is signed with SHA1, it must not be in the (Mozilla) trust store ( https://github.com/nabla-c0d3/sslyze/blob/master/sslyze/plugins/certificate_info_plugin.py#L352 ). 

Do you have any examples of SSLyze reporting the wrong result? Google is special because multiple certificate chains can be built (via cross-signing); based on the trust store used, the SHA-1-signed CA can sometimes be an intermediate. You can also see this on SSL Labs: https://www.ssllabs.com/ssltest/analyze.html?d=www.google.com&s=2607%3af8b0%3a4005%3a805%3a0%3a0%3a0%3a2004&hideResults=on.

**Comment by rdegraaf** [comment]
I cloned the latest sslyze and nassl sources and scanned Google just now and got a SHA1 error:

    [degraaf@ancalagon sslyze]$ python2.7 sslyze_cli.py  --certinfo_basic www.google.com

     AVAILABLE PLUGINS
     -----------------
    
      OpenSslCipherSuitesPlugin
      CertificateInfoPlugin
      HeartbleedPlugin
      FallbackScsvPlugin
      CompressionPlugin
      SessionRenegotiationPlugin
      HstsPlugin
      OpenSslCcsInjectionPlugin
      SessionResumptionPlugin
    
    
    
     CHECKING HOST(S) AVAILABILITY
     -----------------------------
    
       www.google.com:443                       => 172.217.2.228 
    
    
    
     SCAN RESULTS FOR WWW.GOOGLE.COM:443 - 172.217.2.228:443
     -------------------------------------------------------
    
      * Certificate Basic Information:
          SHA1 Fingerprint:                  40f3a50148e1ee529704e0c3dd89aadad2b95649
          Common Name:                       www.google.com
          Issuer:                            Google Internet Authority G2
          Serial Number:                     2AA409FFF5BF940B
          Not Before:                        Jun 16 08:36:55 2016 GMT
          Not After:                         Sep  8 08:29:00 2016 GMT
          Signature Algorithm:               sha256WithRSAEncryption
          Public Key Algorithm:              rsaEncryption
          Key Size:                          2048 bit
          Exponent:                          65537 (0x10001)
          X509v3 Subject Alternative Name:   {'DNS': ['www.google.com']}
    
      * Certificate - Trust:
          Hostname Validation:               OK - Subject Alternative Name matches www.google.com
          Mozilla NSS CA Store (02/2016):    OK - Certificate is trusted
          Microsoft CA Store (02/2016):      OK - Certificate is trusted
          Apple CA Store (OS X 10.11.3):     OK - Certificate is trusted
          Java 6 CA Store (Update 65):       OK - Certificate is trusted
          AOSP CA Store (N Preview 2):       OK - Certificate is trusted
          Weak Signature:                    INSECURE - SHA1-signed certificate in the chain
          Certificate Chain Received:        www.google.com --> Google Internet Authority G2 --> GeoTrust Global CA
          Certificate Chain Order:           OK - Order is valid
    
      * Certificate - OCSP Stapling:
                                         NOT SUPPORTED - Server did not send back an OCSP response.
    
    
    
     SCAN COMPLETED IN 0.37 S
     ------------------------

Looking at their certificate in Firefox, the leaf ("www.google.com") is signed using "PKCS #1 SHA-256 With RSA Encryption".  So is the intermediate CA ("Google Internet Authority G2").  Only the root CA ("GeoTrust Global CA") is signed using "PKCS #1 SHA-1 With RSA Encryption".  As a root CA, it is self-signed.

**Comment by nabla-c0d3** [comment]
The GeoTrust Global CA is not self-signed; it is signed by the legacy Equifax CA certificate that will expire in 2018. Hence, there is a certificate chain where GeoTrust Global CA is not the root certificate. Still, I think SSLyze should report the same thing as Firefox (since it uses the same trust store).

**Comment by rdegraaf** [comment]
Right you are... I don't know how I missed that.  So maybe the correct thing to do would be to ignore SHA-1 signatures on trusted CA certificates?

**Comment by nabla-c0d3** [comment]
Yes - this is what the next version will do.
Thanks!
