### ISSUE TITLE
--ca_file returns an error

### ISSUE THREAD

**Issue by niphlod** [nabla-c0d3/sslyze#156]
on 0.13.5 worked fine, while in 0.13.6 I get 

ERROR: OpenSSLError - 
error:02001002:system library:fopen:No such file or directory
error:2006D080:BIO routines:BIO_new_file:no such file
error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib

I'm using the binary release on windows, placed my CA under data\trust_stores along with the others and passing --ca_file data\trust_stores\myca.pem as an option: is the syntax changed ? I tried passing the complete path and it throws the same exception

**Comment by nabla-c0d3** [comment]
I am unable to reproduce this and --ca_file works fine on my machine. Are you sure the file actually exists?
