### ISSUE TITLE
Re-add sslyze.py for backwards compatibility

### ISSUE THREAD

**Issue by postmodern** [nabla-c0d3/sslyze#158]
I noticed `sslyze.py` was renamed back to `sslyze_cli.py`. Until you hit 1.0.0, it might be a good idea to continue to support `sslyze.py`? It's also a bit redundant to suffix a CLI util with `_cli`.

**Comment by nabla-c0d3** [comment]
Yeah - it is not great that it broke backward compatibility, but the name `sslyze.py` would clash with the `sslyze` module/folder (newly added in 0.13 for using SSLyze directly from Python).
