### ISSUE TITLE
Microsoft root store

### ISSUE THREAD

**Issue by hojemo** [nabla-c0d3/sslyze#16]
Hello!
I find  sslyze to be an excellent tool, however I get strange results regarding the Microsoft CA store support. When I test www.verisign.com sslyze says that the SSL certificate on the site is not supported by the Microsoft root store (it says that the certificate has expired). Can the microsoft.pem file somehow be updated in order to rectify this? 

Here is the output I get for www.verisign.com :

 * Certificate - Trust:
      Hostname Validation:               OK - Subject Alternative Name matches
      "Mozilla NSS - 08/2014" CA Store:  OK - Certificate is trusted, Extended Validation
      "Microsoft - 08/2014" CA Store:    FAILED - Certificate is NOT Trusted: certificate has expired
      "Apple - OS X 10.9.4" CA Store:    OK - Certificate is trusted
      "Java 6 - Update 65" CA Store:     OK - Certificate is trusted
      Certificate Chain Received:        ['www.verisign.com', 'VeriSign Class 3 Extended Validation SSL SGC CA', 'VeriSign Class 3 Public Primary Certification Authority - G5']

Best wishes,
Thomas Höjemo

**Comment by nabla-c0d3** [comment]
This was fixed in v0.11
