### ISSUE TITLE
Error when scanning long list of hosts

### ISSUE THREAD

**Issue by unamuno** [nabla-c0d3/sslyze#160]
Hey, 
I'm using __Ubuntu 14.04 LTS__ with __Python 2.7.6__ and __sslyze 0.13.6__ the latest one I got from pip.
I used --targets_in to scan a large number (870) hosts. But after 130 to 150 hosts sslyze troughs  an exception. I tried to find the host that caused the error but sslyze always fails  at different hosts. Smaler parts of the host list is no problem.

```
File "/usr/local/bin/sslyze_cli.py", line 677, in <module>
    main()
  File "/usr/local/bin/sslyze_cli.py", line 587, in main
    print _format_txt_target_result(server_info, result_list)
  File "/usr/local/bin/sslyze_cli.py", line 440, in _format_txt_target_result
    for line in plugin_result.as_text():
  File "/usr/local/lib/python2.7/dist-packages/sslyze/plugins/certificate_info_plugin.py", line 305, in as_text
    text_output.extend(self._get_certificate_text())
  File "/usr/local/lib/python2.7/dist-packages/sslyze/plugins/certificate_info_plugin.py", line 510, in _get_certificate_text
    issuer_name = unicode(cert_dict['issuer'], 'utf-8')
TypeError: coercing to Unicode: need string or buffer, dict found
```

**Comment by unamuno** [comment]
I found a work around. It's much slower.

```
while read p; do 
sslyze_cli.py $p --certinfo_basic 
done < hosts.txt
```

The error is still occuring but all hosts were scanned.

**Comment by nabla-c0d3** [comment]
Thanks for the report - do you have a specific hostname that is causing this issue?

**Comment by unamuno** [comment]
Nothing special. Just a-z and 1-9

**Comment by nabla-c0d3** [comment]
I meant the full hostname so I can reproduce the issue by scanning it. It is most likely some kind of utf8 character returned somewhere (probably the server's certificate).
Thanks!

**Comment by unamuno** [comment]
Sorry, you can't reach the servers from the internet.

**Comment by nabla-c0d3** [comment]
Ok - can find you one that triggers the bug and post the output?

**Comment by unamuno** [comment]
I tried but single hosts don't generate the bug, only when I used a list.

**Comment by nabla-c0d3** [comment]
This was caused by certificates with no Common Names in the Issuer field; it should work now but let me know if you still see this issue.
Thanks!

**Comment by unamuno** [comment]
Great tested 846 hosts. Everything works now! Thanks. :+1: :)
