### ISSUE TITLE
IPv6 hostnames and IPs not working

### ISSUE THREAD

**Issue by bcrab** [nabla-c0d3/sslyze#161]
IPv6 hostname lookup does not work:

$ sslyze_cli.py ipv6.google.com
...
 CHECKING HOST(S) AVAILABILITY
 -----------------------------

   ipv6.google.com                     => WARNING: Could not resolve ipv6.google.com; discarding corresponding tasks.

Also fails with direct IPv6 address:
$ host ipv6.google.com
ipv6.google.com is an alias for ipv6.l.google.com.
ipv6.l.google.com has IPv6 address 2607:f8b0:400a:808::200e
$ sslyze_cli.py [2607:f8b0:400a:808::200e]:443
...
 CHECKING HOST(S) AVAILABILITY
 -----------------------------

   [2607:f8b0:400a:808::200e]:443      => WARNING: Could not resolve 2607:f8b0:400a:808::200e; discarding corresponding tasks.

I noted that server_connectivity.py:118 uses socket.gethostbyname(), which appears to be related to  https://github.com/nabla-c0d3/sslyze/commit/6ebf51f803170681efbddf2704651b2cd0f2fc5e

My hacky workaround until it is fixed properly:
change sslyze/server_connectivity.py:118 to
                self.ip_address = socket.getaddrinfo(self.hostname, None)[0][4][0]

**Comment by nabla-c0d3** [comment]
Thanks!
