### ISSUE TITLE
--https_tunnel not working without name resolution

### ISSUE THREAD

**Issue by gituser2k16** [nabla-c0d3/sslyze#164]
Since 0.13.x releases proxy connecting stopped working, if the client isn't able to resolve the target domain. With 0.12 everything is working as expected the client connects to the proxy an is able to scan the target domain.

When I put the target domain to the hosts-file no matter wich ip it starts working again.
In my understanding of a proxy there is no need for the client to resolve the target by it self.

**Comment by nabla-c0d3** [comment]
Thanks!
