### ISSUE TITLE
OSError during installing via pip

### ISSUE THREAD

**Issue by nottheend** [nabla-c0d3/sslyze#165]
Error encountered while installing ssylze with pip in Fedora.
Tried to install after cloning like this as recommended:
pip install -r requirements.txt --target ./lib

But in the installing process the Error message appears:

`Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 357, in run
    for item in os.listdir(lib_dir):
OSError: [Errno 2] File or directory not found: '/tmp/tmpXXXXXX/lib/python'
`

The problem is, that it searches in "/tmp/tmpXXXXXX/lib/python" but indeed the correct location is "/tmp/tmpXXXXXX/lib64/python"

**Comment by nottheend** [comment]
I just saw that the issue came up already.

This topic is the same as [#39 in nassl](https://github.com/nabla-c0d3/nassl/issues/39)

**Comment by nabla-c0d3** [comment]
As far as I know this is a problem with your pip/python installation (perhaps a conflict between Python 32 and 64 bits?). SSLyze does nothing special in its setup.py that could lead to this error.

**Comment by nottheend** [comment]
It is correct, there was a problem with the python installation.

This site for centOS was helping to resolve the issue:
http://toomuchdata.com/2014/02/16/how-to-install-python-on-centos/

Thanks.
