### ISSUE TITLE
Could not connect

### ISSUE THREAD

**Issue by stoennies** [nabla-c0d3/sslyze#172]
Hi,

thanks for the tool! I have a problem. When testing some servers with

`sslyze_cli.exe --regular --starttls=smtp domain`

the tool sometimes fails with a time out. But when I test the same domain with e.g. `https://tls.imirhil.fr/smtp` the domain can be tested. An example would be ekir-lka.de with the mailserver mail.ekir-lka.de

An error or not?

**Comment by nabla-c0d3** [comment]
You cannot use `--regular` for non-HTTPS servers. Try instead `--starttls=smtp --certinfo_basic`?

**Comment by stoennies** [comment]
I'm sorry to ask again...
Now I'm working in a nother network and tried your approch: `sslyze --starttls=smtp --certinfo_basic` and I get an `Connection rejected`. So still not working. And now for ALL servers, e.g. mx.noris.net
I am working under windows in the console and no proxy active.
