### ISSUE TITLE
0.14.0 JSON output changes

### ISSUE THREAD

**Issue by Gank** [nabla-c0d3/sslyze#173]
Same command output differs from version 0.13.6 to 0.14.0.

`
sslyze_cli.py --certinfo_full www.google.com --json_out=google.json`

In version 0.14.0 this will produce a 1.7 MB json file.
In version 0.13.6 it produced a 35 KB json file.

It seems that the path_validation_result_list is now listing all the certificates for every truststore under, 

```
  "path_validation_result_list": [
                        {
                            "is_certificate_trusted": true, 
                            "trust_store": {
                                "_certificate_dict": {
```

Is this the new expected behaviour?

Thanks for this tool.

**Comment by nabla-c0d3** [comment]
It wasn't - thanks!
