### ISSUE TITLE
sslyze does not set user-agent

### ISSUE THREAD

**Issue by hvnsweeting** [nabla-c0d3/sslyze#176]
all HTTP clients set their user-agent, so when a connection is created, from server side we have an idea what is connecting. But for sslyze, it does not set any user-agent, so in NGINX log, we get message like this:

```
Sep 14 07:25:48 my-master nginx: https://fml.vn:443/- 10.1.1.1:- "GET / HTTP/1.0" 0.000 67:555 200 "-" "-" "-"
```

which took us a while to indicate who made the connection to the server.

Is there any reason that makes sslyze not set user-agent? should it add a value or allow user to set user-agent themselves?

**Comment by nabla-c0d3** [comment]
The user agent should now have SSLyze in it.

**Comment by zlaoz** [comment]
Still getting "-" as agent using version 1.2.0
