### ISSUE TITLE
JSON output: unhandy key

### ISSUE THREAD

**Issue by nottheend** [nabla-c0d3/sslyze#178]
Creation of a specific key probably fails.

The relevant keys are placed under `_certificate_dict`

complete path:

- `accepted_targets[0]->`
- `commands_results->`
- `certinfo_basic->`
- `path_validation_result_list[0]->`
- `trust_store->`
- `_certificate_dict`

Example for _one single_ specific key is:
`"commonNameCybertrust Global RootorganizationNameCybertrust, Inc"`

expected:
`"commonName" : "Cybertrust Global Root",`
`"organizationName" : "Cybertrust, Inc"`

**Comment by nabla-c0d3** [comment]
That key is getting removed ( #173 ).
