### ISSUE TITLE
parse_http_response "not defined" error with https_tunnel (0.14.1)

### ISSUE THREAD

**Issue by gtanuel** [nabla-c0d3/sslyze#180]
ssl_connection.py line 139 still uses the old parse_http_response() rather than the new HttpResponseParser.parse(), producing "not defined" error when https_tunnel is used.

**Comment by bratkartoffel** [comment]
Same here, tested versions:
0.14.1
0.14.0
0.13.6
0.13.5
0.13.4
0.13.3
0.13.2 (could not test as no .exe available / found)
0.13.1 (could not test as no .exe available / found)

Last working version for me is the 0.12 release.

**Comment by nabla-c0d3** [comment]
This should only affect 0.14.1 - will fix it soon.
