### ISSUE TITLE
starttls for postgres is not working

### ISSUE THREAD

**Issue by AsmaeBni** [nabla-c0d3/sslyze#182]
I tried to scan a postgres database version :9.3.14 with the flag --starttls=postgres enabled but I get the warning 'Postgres AUTH TLS was rejected' although the traffic capture that the database server replies to the request.
This was fixed localy in my machine doing this change in line '472' file 'ssl_connection.py':
- START_TLS_OK = 'S' 
- instead of
-  START_TLS_OK = 'Start TLS request accepted.'
- This is documented here: https://www.postgresql.org/docs/9.3/static/protocol-flow.html#AEN99579 postgres server replies with 'S' when its willing to support SSL

**Comment by nabla-c0d3** [comment]
Thanks! It should work now.
