### ISSUE TITLE
incorrect input interpretation

### ISSUE THREAD

**Issue by nottheend** [nabla-c0d3/sslyze#183]
**scenario**
Entering an input url starting with `https://` leads to a `'Not a valid host:port'` message, test is arborted.
Message originates from [sslyze/server_connectivity.py#L347](https://github.com/nabla-c0d3/sslyze/blob/master/sslyze/server_connectivity.py#L347).

**expectation**
Prefix `https` is interpreted as port `443`.

**estimated problem**
Searching for the appearance of the **first** `':'` in `server_str`.
In this case it would be the second.
Splitting of `server_str` takes place for [IPv4 in #L380](https://github.com/nabla-c0d3/sslyze/blob/master/sslyze/server_connectivity.py#L380) and for [IPv6 in #L401](https://github.com/nabla-c0d3/sslyze/blob/master/sslyze/server_connectivity.py#L401).

**Comment by nabla-c0d3** [comment]
This is by design: SSLyze is an SSL/TLS scanner and is not specific to HTTPS (as it supports other protocols). Hence the "input" is a host:port, not a URL.

**Comment by nottheend** [comment]
Ok, thanks.
