### ISSUE TITLE
Sslyze cli parser error

### ISSUE THREAD

**Issue by asana12** [nabla-c0d3/sslyze#197]
This:

`sslyze --regular www.yahoo.com

 AVAILABLE PLUGINS
 -----------------

  SessionResumptionPlugin
  OpenSslCipherSuitesPlugin
  FallbackScsvPlugin
  HeartbleedPlugin
  CompressionPlugin
  OpenSslCcsInjectionPlugin
  HttpHeadersPlugin
  CertificateInfoPlugin
  SessionRenegotiationPlugin

 CHECKING HOST(S) AVAILABILITY
 -----------------------------

Traceback (most recent call last):
  File "/usr/local/bin/sslyze", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/sslyze/__main__.py", line 98, in main
    failed_scan = FailedServerScan(tentative_server_info.server_string, exception)
  File "/usr/local/lib/python2.7/dist-packages/sslyze/cli/__init__.py", line 18, in __init__
    raise connection_exception
AttributeError: 'int' object has no attribute 'value'
`
Thanks.

**Comment by ericrange** [comment]
cant reproduce that. make sure u installed sslyze with all necessary deps.
e.g. gcc, python-dev, ...

**Comment by asana12** [comment]
All of the requirements are installed.
pip2 install sslyze

**Comment by asana12** [comment]
`sslyze --regular www.yahoo.com

AVAILABLE PLUGINS

SessionResumptionPlugin
OpenSslCipherSuitesPlugin
FallbackScsvPlugin
HeartbleedPlugin
CompressionPlugin
OpenSslCcsInjectionPlugin
HttpHeadersPlugin
CertificateInfoPlugin
SessionRenegotiationPlugin

CHECKING HOST(S) AVAILABILITY

Traceback (most recent call last):
File "/usr/local/bin/sslyze", line 11, in 
sys.exit(main())
File "/usr/local/lib/python2.7/dist-packages/sslyze/main.py", line 98, in main
failed_scan = FailedServerScan(tentative_server_info.server_string, exception)
File "/usr/local/lib/python2.7/dist-packages/sslyze/cli/init.py", line 18, in init
raise connection_exception
AttributeError: 'int' object has no attribute 'value'`

**Comment by asana12** [comment]
The problem is still continuing. I'm waiting for your help.

**Comment by ericrange** [comment]
this is not reproducible. seems there is something wrong with your env.
try it on another host.
