### ISSUE TITLE
Please add sslyze to pypi 

### ISSUE THREAD

**Issue by dbaxa** [nabla-c0d3/sslyze#2]
Please add sslyze to pypi so that we can simply `pip install sslyze` to install sslyze.

**Comment by hummus** [comment]
could you have nassl and sslyze as separate packages? I tried to do this on my two forks but I know windows compat is an issue. I'd be willing to look at that more(and osx) if you think this direction could allow for eventual pypi support.

**Comment by nabla-c0d3** [comment]
I don't mind having them as separate packages as they already have their own repos. However, I think building nassl from scratch is a non-starter as it needs to statically link a very specific version of OpenSSL and zlib.

**Comment by nabla-c0d3** [comment]
https://pypi.python.org/pypi/SSLyze
