### ISSUE TITLE
Cannot build certification chain using custom certificate autority 

### ISSUE THREAD

**Issue by glestel** [nabla-c0d3/sslyze#205]
This might be a corner case but I'll try to elaborate.

For our intranet we have a custom Certificate Autority but SSLyze seems to have trouble building the certificate chain.
The added CA manage to validate the certificate, but SSLyze fail to build the trust chain : 
```
Custom --ca_file CA Store (N/A):   OK - Certificate is trusted
Java 7 CA Store (Update 79):       FAILED - Certificate is NOT Trusted: self signed certificate in certificate chain
```
```
Verified Chain:                    ERROR - Could not build verified chain (certificate untrusted?)
Received Chain Contains Anchor:    ERROR - Could not build verified chain (certificate untrusted?)
Received Chain Order:              FAILED - Certificate chain out of order!
Verified Chain contains SHA1:      ERROR - Could not build verified chain (certificate untrusted?)
```
I thought that it might be linked to the custom ca_file so I tried overriding the Mozilla CA with our Custom CA (in sslyze files), it works for validation but I get the same results : 
```
Certificate - Trust:
      Hostname Validation:               OK - Subject Alternative Name matches app.ecorp.tld
      Mozilla CA Store (09/2016):        OK - Certificate is trusted
      Java 7 CA Store (Update 79):       FAILED - Certificate is NOT Trusted: self signed certificate in certificate chain
```
```
Verified Chain:                    ERROR - Could not build verified chain (certificate untrusted?)
Received Chain Contains Anchor:    ERROR - Could not build verified chain (certificate untrusted?)
Received Chain Order:              FAILED - Certificate chain out of order!
Verified Chain contains SHA1:      ERROR - Could not build verified chain (certificate untrusted?)
```
Is this a know bug ? As it's linked to our internal CA, let me know if you need my help for further testing

**Comment by nabla-c0d3** [comment]
This is already fixed on master; will close this issue when I release 1.1.0.

**Comment by mmclean636jr** [comment]
Is there a projected release date for 1.1.0?

**Comment by ericrange** [comment]
+1

**Comment by nabla-c0d3** [comment]
It's released.

**Comment by glestel** [comment]
I've come to the same error with the 1.1.0 and it's because of the certificate chain that is sent in incorrect order (sslyze didn't manage to `build_verified_certificate_chain()` after careful debugging). 
However the custom CA does validate the server certificate (with sslyze or directly with openssl), so I am wondering how the certificate could be trusted if there's an issue with the certificate chain ? (I know it's relative to the way openssl works but I did not manage to find an explication on the web)
