### ISSUE TITLE
json output: "hostname_validation_result" incorrect

### ISSUE THREAD

**Issue by nottheend** [nabla-c0d3/sslyze#206]
The output json-file produced with option _--json_out=result.json_
results in an empty pair of curly braces:
`accepted_targets[0]->commands_results->certinfo->hostname_validation_result="{}"`

The result is being shown correctly on cli:
`Hostname Validation:               OK - Subject Alternative Name matches`

**Comment by nabla-c0d3** [comment]
This is already fixed on master; will close this issue when I release 1.1.0.

**Comment by nottheend** [comment]
Thanks
