### ISSUE TITLE
Support for TLS1.3 and newer TLS features and ciphers

### ISSUE THREAD

**Issue by ericrange** [nabla-c0d3/sslyze#211]
Nginx now supports TLS1.3
Maybe Sslyze should be able to scan this as well?

**Comment by nabla-c0d3** [comment]
I will add experimental support for TLS 1.3 by extending https://github.com/nabla-c0d3/tls_parser , instead of leveraging OpenSSL (which right now cannot be upgraded due to #116 )

**Comment by nabla-c0d3** [comment]
The plan is now to embed another version of OpenSSL that supports TLS 1.3, as described in #116.
