### ISSUE TITLE
Infinite hang on some domains (even with short timeout)

### ISSUE THREAD

**Issue by konklone** [nabla-c0d3/sslyze#217]
This command hangs forever for me, on Debian using sslyze 1.1.0:

```
sslyze --regular empowhr.gov
```

Adding a `--timeout=1` flag doesn't help, either. It's not clear why it's hanging. https://empowhr.gov responds and loads quickly in Chrome.

**Comment by ericrange** [comment]
perhabs the same issue as #213

**Comment by konklone** [comment]
Looks like expanding `--regular` to its full set of flags, and then removing `--heartbleed`, was enough to fix this. Unclear why the Heartbleed scan might be hanging indefinitely on certain domains.

**Comment by dylanjbarth** [comment]
I am still able to replicate this issue with 1.3.4. @nabla-c0d3 just sent you an email with a domain to try.

**Comment by nabla-c0d3** [comment]
@dylanjbarth the issue you are running into is #286 ; the server you sent me dies under the number of concurrent connections initiated by SSLyze. It will be fixed in the next release if you use `--slow_connection` when running the tool.
