### ISSUE TITLE
XML schema inconsistencies

### ISSUE THREAD

**Issue by postmodern** [nabla-c0d3/sslyze#22]
I noticed various inconsistencies in the XML schema. Some attributes have the format of `Foo_Bar` while others are `fooBar` (ex: `<keyExchange>`). Also, it seems like `<cipherSuite>` maybe should be named `<cipher>`? Certain text values appear to be compound values (ex: `sha256WithRSAEncryption` and `TLS / No ciphers available`). I'm not sure how open you are to changing the XML schema, now that users are consuming it.

**Comment by nabla-c0d3** [comment]
I think this is fixed? The only <foo_bar> elements are tlsv1_1 and tlsv1_2, because they are supposed to mirror the command line options (--tlsv1_1 and --tlsv1_2).
