### ISSUE TITLE
XML: why does verifiedCertificateChain always appear under the last pathValidation element?

### ISSUE THREAD

**Issue by postmodern** [nabla-c0d3/sslyze#221]
I noticed that the `<verifiedCertificateChain />` and additional `<certificate />` XML elements would always be nested under the last `<pathValidation />` (typically the Mozilla truststore) of a `<target />`. Is this intentional or an artifact of the XML output?

**Comment by nabla-c0d3** [comment]
It will appear in one of the `pathValidation` nodes, with a preference for Mozilla's. If there is no `verifiedCertificateChain`, it means that the chain could not be built using any of the trust stores.
