### ISSUE TITLE
XML: position attribute missing from certificate elements

### ISSUE THREAD

**Issue by postmodern** [nabla-c0d3/sslyze#223]
The `position` attribute never seems to be set on `<certificate />` elements. In the past this attribute would indicate the `leaf` certificate. Is the leaf certificate now the first or last `<certificate />` within a `<verifiedCertificateChain />` element?

**Comment by nabla-c0d3** [comment]
I have removed the position attribute because it's ambiguous in most cases. The received and verified chains XML nodes now follow the same order as what the documentation states.
