### ISSUE TITLE
Error installing SSLyze in Debian

### ISSUE THREAD

**Issue by qwartz** [nabla-c0d3/sslyze#234]
I am trying to install **sslyze** in Debian, but when I run `pip install sslyze` it gives me the following error: 

` [1]    11334 segmentation fault  pip install sslyze`

Any idea what it might be?

**Comment by nabla-c0d3** [comment]
This looks an issue with your `pip` installation.

**Comment by qwartz** [comment]
Thanks, I'm going to reinstall `pip`, to see if it works!

**Comment by qwartz** [comment]
I was right, I have reinstalled `pip` and it worked!

---
**solution:** `[1] 11334 segmentation fault pip install sslyze`
- Reinstall `pip`:

Uninstall `python-pip`:
`sudo apt remove --purge python-pip`

Update system:
`sudo apt update; apt upgrade; apt autoremove`

Install required packages:
`sudo apt install python-dev build-essential `

Install `python-pip`:
sudo apt install python-pip

Update `pip` to the latest version:
`sudo pip install --upgrade pip`

Install `SSLyze`:
`sudo pip install --upgrade SSLyze`

---

@nabla-c0d3 Thank you for your project!
