### ISSUE TITLE
Heartbleed Unhandled exception - 72 is not a valid TlsRecordTypeByte

### ISSUE THREAD

**Issue by MikeLund** [nabla-c0d3/sslyze#236]
Just got version 1.1.2 via Homebrew on macOS Sierra. Running `sslyze --regular www.cloudflare.com:443` gives this error:

```
 * OpenSSL Heartbleed:
Unhandled exception while running --heartbleed:
ValueError - 72 is not a valid TlsRecordTypeByte
```

It doesn't seem to happen for all sites. If I test against Google for example, it says "OK - Not vulnerable to Heartbleed". But test against some site proxied by Cloudflare, or my own site running on nginx, and it gives the above error.

Hope this helps!

**Comment by nabla-c0d3** [comment]
Hello,
I am not able to reproduce this. Can you try with what's on master instead of the version on Homebrew?
Thanks

**Comment by MikeLund** [comment]
Thanks, but did you try with the version on Homebrew?
Unsure when I will have time to mess with pip to try version on master, so would be good to know if it's just a possible error with Homebrew's build.

**Comment by nabla-c0d3** [comment]
I tried with homebrew and I am still unable to reproduce this.

**Comment by MikeLund** [comment]
Hi again, sorry for delay getting back on this.

I have figured out it must be something my ISP is doing. If I use any VPN, sslyze tests Heartbleed fine. But if I test with my normal IP, it always gives the TlsRecordTypeByte error.

Do you know the best way I can debug this/help you out? I tried running http://rehmann.co/projects/heartbeat/ssltest.py - worked on my VPN (`Received alert!`), but on my normal IP it gave `Sending heartbeat request...
Unexpected EOF receiving record header - server closed connection`.



PS: as I said in my first post, `sslyze --heartbleed` says `OK - Not vulnerable to Heartbleed` when I test with my IP on Google. But if I run the script I linked above against Google (or any other site) using my IP, I get the same EOF error.
So for some reason sslyze is thinking the response I get from Google is okay, but the response from Cloudflare isn't okay. But this also makes no sense, because my ISP must be dropping the HB payload or something??? 😕

**Comment by nabla-c0d3** [comment]
It could be that you are hitting a different Cloudflare IP/server based on where you are connecting from. What is the IP address that you see when it fails?

**Comment by MikeLund** [comment]
Forgot to mention, already checked that; I made sure it tested against the same IP (198.41.215.162) all the different times. So I'm almost 100% sure it must be something sneaky my ISP is doing regarding the HB payload.

**Comment by jvolli** [comment]
Hi, I'm getting a similar error when trying to test "sslyze --regular webmail.vocons.de":
 * OpenSSL Heartbleed:
Unhandled exception while running --heartbleed:
ValueError - 11 is not a valid TlsRecordTypeByte
...
 * OpenSSL CCS Injection:
Unhandled exception while running --openssl_ccs:
ValueError - 11 is not a valid TlsRecordTypeByte

Maybe you can reproduce with this site? Thanks in advance, Juergen

**Comment by nabla-c0d3** [comment]
Thanks, I am now able to reproduce it.

**Comment by nabla-c0d3** [comment]
Thanks, I am now able to reproduce it.
