### ISSUE TITLE
certinfo not in xml anymore

### ISSUE THREAD

**Issue by BenjaminHae** [nabla-c0d3/sslyze#237]
I think since [this commit](https://github.com/nabla-c0d3/sslyze/commit/0472293940a2902ec842a55ad4028e1a718a870a) information about the certificate like issuer, subject, validity and publicKeyInfo is gone from the xml output.

I'd be really happy if they'd come back.

Thanks for your work on this tool! I really appreciate it.

**Comment by nabla-c0d3** [comment]
What prevents you from parsing the PEM certificate in the language you're using to process the XML output?

**Comment by BenjaminHae** [comment]
Nothing. But it seems pointless to duplicate something that's already available.

I mostly keep the xml files of hosts I scanned as I thought they contained all/more information of/than the text output. I just expected that the xml file contained all information of the text output ( yes I know technically it is in the pem, but I hope you get my point )
