### ISSUE TITLE
SSLyze uses the system's OpenSSL on some Linux distros

### ISSUE THREAD

**Issue by Jackeriss** [nabla-c0d3/sslyze#241]
system environments:
Linux version: 2.6.32-5-amd64 (Debian 2.6.32-48squeeze6)(gcc version 4.3.5 (Debian 4.3.5-4) )
openssl version: 1.0.1e
python version: python3.6.2
using SynchronousScanner
installed by pip3

**Comment by nabla-c0d3** [comment]
Did you build nassl yourself?

**Comment by Jackeriss** [comment]
@nabla-c0d3 no I didn't

**Comment by Jackeriss** [comment]
@nabla-c0d3 I have tested my code on many platforms. The Segmentation fault only occurs on Debian(I tried Debian6 and Debian7). But not on Mac OS El Capitan or CentOS 6.8.

**Comment by Jackeriss** [comment]
Problem solved by updating openssl to openssl 1.0.2l

**Comment by nabla-c0d3** [comment]
Re-opening this as SSLyze should never use the system's OpenSSL library - it embeds its own custom version of OpenSSL.

**Comment by nabla-c0d3** [comment]
@Jackeriss just to confirm, all you did was `pip install sslyze` ?

**Comment by Jackeriss** [comment]
@nabla-c0d3 Yes.

**Comment by nabla-c0d3** [comment]
Nassl now has binary wheels for Linux ( https://legacy.pypi.io/pypi/nassl ) - @Jackeriss can you try:

```
pip uninstall nassl sslyze
pip install sslyze
```
And let me know if SSLyze is working correctly? Thanks!
