### ISSUE TITLE
Windows .exe file for latest release

### ISSUE THREAD

**Issue by 19anand90** [nabla-c0d3/sslyze#242]
There is no .exe format available for latest release. Is there any plan to release it?

**Comment by nottheend** [comment]
Work in progress: updating sslyze to Python 3.6 for Windows. See here: #240

**Comment by nabla-c0d3** [comment]
This is fixed in 1.1.3 https://github.com/nabla-c0d3/sslyze/releases/tag/1.1.3

**Comment by nottheend** [comment]
Nice!
