### ISSUE TITLE
nassl requirement issue with latest (1.1.3) SSLyze release

### ISSUE THREAD

**Issue by JCount** [nabla-c0d3/sslyze#243]
Currently, the tag for the `1.1.3` `SSLyze` release has 2 irreconcilable version dependencies on `nassl`. `setup.py` contains the requirement ['nassl>=0.16.0,<0.17.0'](https://github.com/nabla-c0d3/sslyze/blob/1.1.3/setup.py#L17) while `requirements.txt` has the requirement ['nassl>=0.17.0,<0.18.0'](https://github.com/nabla-c0d3/sslyze/blob/1.1.3/requirements.txt#L1).

If I blindly patch `setup.py` to support the newer version of `nassl` it _seems_ to work, but I think it is best to report the issue here.

**Comment by nabla-c0d3** [comment]
Good catch, thanks!
