### ISSUE TITLE
Incorrect DNS values stored in XML output

### ISSUE THREAD

**Issue by kiran-dp** [nabla-c0d3/sslyze#244]
Hi,

I've certificate where user accidentally adds tab to DNS name entry and sslyze fails hostnameValidation test, but DNS entries in XML output indicate its false positive.

Taken from sslyze/plugins/certificate_info_plugin.py: print str(certificate_chain[0].as_dict)
'X509v3 Subject Alternative Name': {'DNS': ['www.myserver.com\t']}

json output does preserve '\t':

           "X509v3 Subject Alternative Name": {
                 "DNS": [
                      "www.myserver.com\t"
                  ]
            }

But XML output, it doesn't preserve '\t':

          <X509v3SubjectAlternativeName>
            <DNS>
              <listEntry>www.myserver.com</listEntry>
            </DNS>

Would it be possible to write DNS names to XML output as found in actual cert? Was looking for code which writes subject alt name to XML, but didn't find it, maybe 'extensions' output is coming from some other libraries? One way for me to solve this issue by switching to json output, but we are heavily invested in using XML form. It would be ideal to have same output for json, xml or stdout formats.

Thanks,
-Kiran

**Comment by nabla-c0d3** [comment]
Hello,
I no longer manually parse the DNS entries specifically because of this. They may contain characters that don't work well with XML; this is why it was removed from the XML output in newer versions of SSLyze. My advice is to parse the PEM certificate with the programming language you are using, and then process it directly.

**Comment by kiran-dp** [comment]
Went ahead with parsing DNS entries using Openssl module in Ruby. 
Do you meant newer version won't have extensions information in XML output at all? if thats the case we can close this issue.

**Comment by nabla-c0d3** [comment]
The certificate details (such as extensions) have been removed from the XML output for a few versions actually... parsing it yourself is a better approach as XML is not good for that. Closing this issue.
