### ISSUE TITLE
Certificate not marked as EV when using as_text() from certificate_info_plugin

### ISSUE THREAD

**Issue by itlabitto** [nabla-c0d3/sslyze#245]
Impacts the --regular output: each certificate store presents "OK - Certificate is trusted" even when checking Mozilla, when it should add the extra info "Extended Validation".
Tested a fix by re-using the lines that check the EV at as_xml(), edited from line 367 and commented out the part after the "and" (it doesn't seem necessary to check the EV, at least as_xml() doesn't use it)

From line 367:
```
if 'Mozilla' in path_result.trust_store.name:
    if self.is_leaf_certificate_ev: # and TrustStoresRepository.get_main() == path_result.trust_store:
        ev_txt = ', Extended Validation'
path_txt = 'OK - Certificate is trusted{}'.format(ev_txt)
```

Regards,
gabimaxi

**Comment by nabla-c0d3** [comment]
Thanks!
