### ISSUE TITLE
Incorrect JSON serialization of Python Enums

### ISSUE THREAD

**Issue by youngec** [nabla-c0d3/sslyze#246]
Since the latest release (1.1.4), I have been unable to properly deserialize the JSON output of sslyze due to OpenSslVersionEnum values not being serialized as JSON strings. Instead, they appear as unquoted literals as follows:

```JSON
"server_info": {
    "client_auth_requirement": "DISABLED",
    "highest_ssl_version_supported": OpenSslVersionEnum.TLSV1_2,
},
```

To reproduce, issue the following command on any target: `sslyze --regular --json_out repro.json [target]`.

Regardless, thanks for such an invaluable tool!

**Comment by nabla-c0d3** [comment]
Thanks for the report
