### ISSUE TITLE
Certificate no marked as Revoked

### ISSUE THREAD

**Issue by itlabitto** [nabla-c0d3/sslyze#247]
The output does Not mark certificate as revoked when testing with domain revoked.badssl.com which does not use OCSP Stapling (I couldn't find a domain with revoked cert and OCSP stapling enabled)
I don't know what is the alternative for checking if certificate is revoked while there is no OCSP stapling.

It would be nice a dedicated flag at Certificate Information > Trust > "Is certificate valid" with output: Valid, Expired, Revoked
And also on each Certificate Store,  "FAILED - Certificate is NOT Trusted: certificate is revoked"

**Comment by nabla-c0d3** [comment]
Hello,
I don't think I will add support for anything but OCSP stapling. Both CRLs and regular OCSP are a bit messy and most browsers ignore them.

**Comment by itlabitto** [comment]
I would check OCSP and show that cert is revoked. It would be good to advise users to take care of it when revoked. User may have some hours to get a new one till CRL is published and avoid a bigger impact. 
By my experience, they usually realize when is late and have many end users complaining, then rush to get a new one. 
I will check if the cryptography library has something working, I used to get the CRL and OCSP url so far.

**Comment by itlabitto** [comment]
hmmm, I see. The mess is when you have missing intermediate certificates in the chain.
What about building a repository (store) of intermediate certificates where to append each intermediate that you find when you test the certificates. It will help for having a local copy of the intermediate for checkign CRL/OCSP. In Windows MMC you can find a folder for Trusted intermediate certificates, kind of play this role.
Having an intermediate certificate store may help to provide extra functionalities, like providing the intermediate to the user when detecting the missing intermediates.
Talking about cert stores, I added a Private Root CA store in a local test, where I can add a Private Root manually. It helps to have a dedicated output when testing certs under private CA, while trusted stores of different platforms show the 'untrusted' as expected.

**Comment by nabla-c0d3** [comment]
Thanks for the suggestions!

A missing intermediate is a configuration error in the server's config, and it is the expected behavior for SSLyze to fail to validate the chain when this happens. The server operator must include all needed certificates instead of relying on browsers to fix it for them.

As for adding support for OCSP  or CRL, I have no plan in doing this as it is a lot of work, and OCSP stapling seems to be the way forward anyway.
