### ISSUE TITLE
Cipher Suite "...CHACHA20_POLY1305..." missing but showing on ssllabs

### ISSUE THREAD

**Issue by itlabitto** [nabla-c0d3/sslyze#248]
I tested the cipher suite "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (0xcca8)", while not showing on the sslyze accepted ciphers, it is identified on ssllabs results. Any ideas?

**Comment by nabla-c0d3** [comment]
SSLyze only supports the "old" (pre-RFC) CHACHA20 cipher suites. The new ones will be supported once #116 has been addressed.

**Comment by itlabitto** [comment]
Thank you, sorry for duplicating it. Regards,

**Comment by nabla-c0d3** [comment]
No problem
