### ISSUE TITLE
OpenVPN

### ISSUE THREAD

**Issue by ericrange** [nabla-c0d3/sslyze#249]
Hi,

will there be an option to scan openvpn ciphers?

**Comment by nabla-c0d3** [comment]
Hello,
What is the OpenVPN protocol like? Pure TLS or maybe StartTLS?

**Comment by ericrange** [comment]
I did not find anything about StartTLS for OpenVPN. I think its pure TLS but not sure :/
https://openvpn.net/index.php/open-source/documentation/security-overview.html

**Comment by nabla-c0d3** [comment]
This seems out of scope for SSLyze.
