### ISSUE TITLE
[Plugin proposition]Checking for http to https redirect

### ISSUE THREAD

**Issue by glestel** [nabla-c0d3/sslyze#250]
Hi,

For a full assessment of the TLS configuration of ours servers, I have to check for active redirection from HTTP to HTTPS. It would be easier if sslyze could give this information in its report rather than having a side report and handling several reports for one target.
Would you be interested if I made this test available with a CheckHttpRedirectionPlugin ?

**Comment by nabla-c0d3** [comment]
Sure, that would be useful. Thanks!
