### ISSUE TITLE
Feature Request: Expose remote OpenSSL version

### ISSUE THREAD

**Issue by TheFiZi** [nabla-c0d3/sslyze#253]
Don't know if this is possible but it would be great if this tool could also determine if the remote side was using OpenSSL and what version of OpenSSL.

**Comment by nabla-c0d3** [comment]
Hello,
While this would be useful, there is no simple way to detect the version of OpenSSL and fingerprinting it falls outside of the goals I have for SSLyze.
Hope this makes sense... Thanks!
