### ISSUE TITLE
Could not find .egg-info directory in install record for sslyze while installing

### ISSUE THREAD

**Issue by vaibhavmule** [nabla-c0d3/sslyze#255]
`(venv)➜  pip install sslyze`
Using Python3.4
> Downloading/unpacking sslyze
>   Downloading SSLyze-1.1.5.tar.gz (1.1MB): 1.1MB downloaded
>   Running setup.py (path:/home/vaibhav/learning/ssl/venv/build/sslyze/setup.py) egg_info for package sslyze
> Downloading/unpacking nassl>=0.17.0,<0.18.0 (from sslyze)
>   Downloading nassl-0.17.0.zip (15.6MB): 15.6MB downloaded
>   Running setup.py (path:/home/vaibhav/learning/ssl/venv/build/nassl/setup.py) egg_info for package nassl
> Downloading/unpacking cryptography==1.9 (from sslyze)
>   Downloading cryptography-1.9.tar.gz (409kB): 409kB downloaded
>   Running setup.py (path:/home/vaibhav/learning/ssl/venv/build/cryptography/setup.py) egg_info for package cryptography
>     no previously-included directories found matching 'docs/_build'
>     warning: no previously-included files matching '*' found under directory 'vectors'
> Downloading/unpacking tls-parser==1.1.0 (from sslyze)
>   Downloading tls_parser-1.1.0.tar.gz
>   Running setup.py (path:/home/vaibhav/learning/ssl/venv/build/tls-parser/setup.py) egg_info for package tls-parser
> Downloading/unpacking idna>=2.1 (from cryptography==1.9->sslyze)
>   Downloading idna-2.6-py2.py3-none-any.whl (56kB): 56kB downloaded
> Downloading/unpacking asn1crypto>=0.21.0 (from cryptography==1.9->sslyze)
>   Downloading asn1crypto-0.23.0-py2.py3-none-any.whl (99kB): 99kB downloaded
> Downloading/unpacking six>=1.4.1 (from cryptography==1.9->sslyze)
>   Downloading six-1.11.0-py2.py3-none-any.whl
> Downloading/unpacking cffi>=1.7 (from cryptography==1.9->sslyze)
>   Downloading cffi-1.11.2.tar.gz (435kB): 435kB downloaded
>   Running setup.py (path:/home/vaibhav/learning/ssl/venv/build/cffi/setup.py) egg_info for package cffi
> Downloading/unpacking pycparser (from cffi>=1.7->cryptography==1.9->sslyze)
>   Downloading pycparser-2.18.tar.gz (245kB): 245kB downloaded
>   Running setup.py (path:/home/vaibhav/learning/ssl/venv/build/pycparser/setup.py) egg_info for package pycparser
>     warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
>     warning: no previously-included files matching 'lextab.*' found under directory 'tests'
>     warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
>     warning: no previously-included files matching 'lextab.*' found under directory 'examples'
> Installing collected packages: sslyze, nassl, cryptography, tls-parser, idna, asn1crypto, six, cffi, pycparser
>   Running setup.py install for sslyze
>     Installing sslyze script to /home/vaibhav/learning/ssl/venv/bin
>   Could not find .egg-info directory in install record for sslyze
>   Running setup.py install for nassl
>     building 'nassl._nassl' extension
>     x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -Ibin/openssl/include -Inassl/_nassl -I/usr/include/python3.4m -I/home/vaibhav/learning/ssl/venv/include/python3.4m -c nassl/_nassl/nassl.c -o build/temp.linux-x86_64-3.4/nassl/_nassl/nassl.o -Wall
>     x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -Ibin/openssl/include -Inassl/_nassl -I/usr/include/python3.4m -I/home/vaibhav/learning/ssl/venv/include/python3.4m -c nassl/_nassl/nassl_SSL_CTX.c -o build/temp.linux-x86_64-3.4/nassl/_nassl/nassl_SSL_CTX.o -Wall
>     x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -Ibin/openssl/include -Inassl/_nassl -I/usr/include/python3.4m -I/home/vaibhav/learning/ssl/venv/include/python3.4m -c nassl/_nassl/nassl_SSL.c -o build/temp.linux-x86_64-3.4/nassl/_nassl/nassl_SSL.o -Wall
>     x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -Ibin/openssl/include -Inassl/_nassl -I/usr/include/python3.4m -I/home/vaibhav/learning/ssl/venv/include/python3.4m -c nassl/_nassl/nassl_X509.c -o build/temp.linux-x86_64-3.4/nassl/_nassl/nassl_X509.o -Wall
>     x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -Ibin/openssl/include -Inassl/_nassl -I/usr/include/python3.4m -I/home/vaibhav/learning/ssl/venv/include/python3.4m -c nassl/_nassl/nassl_errors.c -o build/temp.linux-x86_64-3.4/nassl/_nassl/nassl_errors.o -Wall
>     x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -Ibin/openssl/include -Inassl/_nassl -I/usr/include/python3.4m -I/home/vaibhav/learning/ssl/venv/include/python3.4m -c nassl/_nassl/nassl_BIO.c -o build/temp.linux-x86_64-3.4/nassl/_nassl/nassl_BIO.o -Wall
>     x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -Ibin/openssl/include -Inassl/_nassl -I/usr/include/python3.4m -I/home/vaibhav/learning/ssl/venv/include/python3.4m -c nassl/_nassl/nassl_X509_EXTENSION.c -o build/temp.linux-x86_64-3.4/nassl/_nassl/nassl_X509_EXTENSION.o -Wall
>     x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -Ibin/openssl/include -Inassl/_nassl -I/usr/include/python3.4m -I/home/vaibhav/learning/ssl/venv/include/python3.4m -c nassl/_nassl/nassl_X509_NAME_ENTRY.c -o build/temp.linux-x86_64-3.4/nassl/_nassl/nassl_X509_NAME_ENTRY.o -Wall
>     x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -Ibin/openssl/include -Inassl/_nassl -I/usr/include/python3.4m -I/home/vaibhav/learning/ssl/venv/include/python3.4m -c nassl/_nassl/nassl_SSL_SESSION.c -o build/temp.linux-x86_64-3.4/nassl/_nassl/nassl_SSL_SESSION.o -Wall
>     x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -Ibin/openssl/include -Inassl/_nassl -I/usr/include/python3.4m -I/home/vaibhav/learning/ssl/venv/include/python3.4m -c nassl/_nassl/openssl_utils.c -o build/temp.linux-x86_64-3.4/nassl/_nassl/openssl_utils.o -Wall
>     x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -Ibin/openssl/include -Inassl/_nassl -I/usr/include/python3.4m -I/home/vaibhav/learning/ssl/venv/include/python3.4m -c nassl/_nassl/nassl_OCSP_RESPONSE.c -o build/temp.linux-x86_64-3.4/nassl/_nassl/nassl_OCSP_RESPONSE.o -Wall
>     x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -Ibin/openssl/include -Inassl/_nassl -I/usr/include/python3.4m -I/home/vaibhav/learning/ssl/venv/include/python3.4m -c nassl/_nassl/python_utils.c -o build/temp.linux-x86_64-3.4/nassl/_nassl/python_utils.o -Wall
>     x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.4/nassl/_nassl/nassl.o build/temp.linux-x86_64-3.4/nassl/_nassl/nassl_SSL_CTX.o build/temp.linux-x86_64-3.4/nassl/_nassl/nassl_SSL.o build/temp.linux-x86_64-3.4/nassl/_nassl/nassl_X509.o build/temp.linux-x86_64-3.4/nassl/_nassl/nassl_errors.o build/temp.linux-x86_64-3.4/nassl/_nassl/nassl_BIO.o build/temp.linux-x86_64-3.4/nassl/_nassl/nassl_X509_EXTENSION.o build/temp.linux-x86_64-3.4/nassl/_nassl/nassl_X509_NAME_ENTRY.o build/temp.linux-x86_64-3.4/nassl/_nassl/nassl_SSL_SESSION.o build/temp.linux-x86_64-3.4/nassl/_nassl/openssl_utils.o build/temp.linux-x86_64-3.4/nassl/_nassl/nassl_OCSP_RESPONSE.o build/temp.linux-x86_64-3.4/nassl/_nassl/python_utils.o /home/vaibhav/learning/ssl/venv/build/nassl/bin/openssl/linux64/libssl.a /home/vaibhav/learning/ssl/venv/build/nassl/bin/openssl/linux64/libcrypto.a /home/vaibhav/learning/ssl/venv/build/nassl/bin/zlib/linux64/libz.a -o build/lib.linux-x86_64-3.4/nassl/_nassl.cpython-34m.so
>   Could not find .egg-info directory in install record for nassl>=0.17.0,<0.18.0 (from sslyze)
>   Running setup.py install for cryptography
>     
>     Installed /home/vaibhav/learning/ssl/venv/build/cryptography/.eggs/cffi-1.11.2-py3.4-linux-x86_64.egg
>     Searching for pycparser
>     Reading https://pypi.python.org/simple/pycparser/
>     Downloading https://pypi.python.org/packages/8c/2d/aad7f16146f4197a11f8e91fb81df177adcc2073d36a17b1491fd09df6ed/pycparser-2.18.tar.gz#md5=72370da54358202a60130e223d488136
>     Best match: pycparser 2.18
>     Processing pycparser-2.18.tar.gz
>     Writing /tmp/easy_install-w3q5u846/pycparser-2.18/setup.cfg
>     Running pycparser-2.18/setup.py -q bdist_egg --dist-dir /tmp/easy_install-w3q5u846/pycparser-2.18/egg-dist-tmp-yom7u3g2
>     warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
>     warning: no previously-included files matching 'lextab.*' found under directory 'tests'
>     warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
>     warning: no previously-included files matching 'lextab.*' found under directory 'examples'
>     zip_safe flag not set; analyzing archive contents...
>     pycparser.ply.__pycache__.lex.cpython-34: module references __file__
>     pycparser.ply.__pycache__.lex.cpython-34: module MAY be using inspect.getsourcefile
>     pycparser.ply.__pycache__.yacc.cpython-34: module references __file__
>     pycparser.ply.__pycache__.yacc.cpython-34: module MAY be using inspect.getsourcefile
>     pycparser.ply.__pycache__.yacc.cpython-34: module MAY be using inspect.stack
>     pycparser.ply.__pycache__.ygen.cpython-34: module references __file__
>     Extracting pycparser-2.18-py3.4.egg to /home/vaibhav/learning/ssl/venv/build/cryptography/.eggs
>     
>     Installed /home/vaibhav/learning/ssl/venv/build/cryptography/.eggs/pycparser-2.18-py3.4.egg
>     no previously-included directories found matching 'docs/_build'
>     warning: no previously-included files matching '*' found under directory 'vectors'
>     generating cffi module 'build/temp.linux-x86_64-3.4/_padding.c'
>     generating cffi module 'build/temp.linux-x86_64-3.4/_constant_time.c'
>     generating cffi module 'build/temp.linux-x86_64-3.4/_openssl.c'
>     building '_openssl' extension
>     x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.4m -I/home/vaibhav/learning/ssl/venv/include/python3.4m -c build/temp.linux-x86_64-3.4/_openssl.c -o build/temp.linux-x86_64-3.4/build/temp.linux-x86_64-3.4/_openssl.o
>     x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.4/build/temp.linux-x86_64-3.4/_openssl.o -lssl -lcrypto -o build/lib.linux-x86_64-3.4/cryptography/hazmat/bindings/_openssl.abi3.so
>     building '_constant_time' extension
>     x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.4m -I/home/vaibhav/learning/ssl/venv/include/python3.4m -c build/temp.linux-x86_64-3.4/_constant_time.c -o build/temp.linux-x86_64-3.4/build/temp.linux-x86_64-3.4/_constant_time.o
>     x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.4/build/temp.linux-x86_64-3.4/_constant_time.o -o build/lib.linux-x86_64-3.4/cryptography/hazmat/bindings/_constant_time.abi3.so
>     building '_padding' extension
>     x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.4m -I/home/vaibhav/learning/ssl/venv/include/python3.4m -c build/temp.linux-x86_64-3.4/_padding.c -o build/temp.linux-x86_64-3.4/build/temp.linux-x86_64-3.4/_padding.o
>     x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.4/build/temp.linux-x86_64-3.4/_padding.o -o build/lib.linux-x86_64-3.4/cryptography/hazmat/bindings/_padding.abi3.so
>   Could not find .egg-info directory in install record for cryptography==1.9 (from sslyze)
>   Running setup.py install for tls-parser
>   Could not find .egg-info directory in install record for tls-parser==1.1.0 (from sslyze)
>   Running setup.py install for cffi
>     building '_cffi_backend' extension
>     x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/python3.4m -I/home/vaibhav/learning/ssl/venv/include/python3.4m -c c/_cffi_backend.c -o build/temp.linux-x86_64-3.4/c/_cffi_backend.o
>     x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.4/c/_cffi_backend.o -lffi -o build/lib.linux-x86_64-3.4/_cffi_backend.cpython-34m.so
>   Could not find .egg-info directory in install record for cffi>=1.7 (from cryptography==1.9->sslyze)
>   Running setup.py install for pycparser
>     warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
>     warning: no previously-included files matching 'lextab.*' found under directory 'tests'
>     warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
>     warning: no previously-included files matching 'lextab.*' found under directory 'examples'
>     Build the lexing/parsing tables
>   Could not find .egg-info directory in install record for pycparser (from cffi>=1.7->cryptography==1.9->sslyze)
> Successfully installed sslyze nassl cryptography tls-parser idna asn1crypto six cffi pycparser
> Cleaning up...
> 

When run the file with example on Readme.md. I get following error.

> Traceback (most recent call last):
>   File "example.py", line 1, in <module>
>     from sslyze.server_connectivity import ServerConnectivityInfo
>   File "/home/vaibhav/learning/ssl/venv/lib/python3.4/site-packages/sslyze/server_connectivity.py", line 10, in <module>
>     from typing import Iterable
> ImportError: No module named 'typing'

**Comment by nabla-c0d3** [comment]
It looks like you did not run `pip install --upgrade setuptools` first.
