### ISSUE TITLE
Incorrect certificate serial number

### ISSUE THREAD

**Issue by itlabitto** [nabla-c0d3/sslyze#260]
I am trying to figure out from where the Serial Number is obtained, the serial printed on the --regular output is Not the one displayed at "Certificate > Details tab > Serial number"

Printed serial seems to come from:  certificate_info_plugin.py
`def _get_basic_certificate_text(self):
<Line 600> self._format_field('Serial Number:', certificate.serial_number)`

The SSLyze serial seems to match "some serial number" obtained with the cryptography library, I tested this example and get the same number: https://cryptography.io/en/latest/x509/reference/

Then used openssl to get the serial and it seems to show the correct one displayed on the certificate: openssl x509 -in mycert.crt -noout -serial
Other checkers also detect the one obtained with openssl.

**Comment by nabla-c0d3** [comment]
Hello,
As you noticed, SSLyze relies on the cryptography module to extract the serial number; if this number is wrong, it is most likely a bug in cryptography .
