### ISSUE TITLE
Update cryptography to latest version

### ISSUE THREAD

**Issue by nabla-c0d3** [nabla-c0d3/sslyze#262]
https://cryptography.io/en/latest/changelog/#v2-1-3

**Comment by egyptiankarim** [comment]
Are there major incompatibilities preventing us from just bumping up `requirements.txt`? Recent changes to pyOpenSSL may have just raised the importance on this, no? From [pyOpenSSL](https://pypi.python.org/pypi/pyOpenSSL):

> Release Information
> 
> 17.5.0 (2017-11-30)
> Backward-incompatible changes:
> The minimum cryptography version is now 2.1.4.
