### ISSUE TITLE
Unittest error ImportError: No module named 'nassl' when using run_tests.py

### ISSUE THREAD

**Issue by itlabitto** [nabla-c0d3/sslyze#266]
Executing the run_tests.py produce the error, solution is to add the path to lib like in api_sample.py:
import os
sys.path.insert(1, os.path.join(os.path.dirname(os.path.abspath(__file__)), 'lib'))

**Comment by nabla-c0d3** [comment]
SSLyze no longer relies on the `./lib`folder (as it is not very "Python-esque"). I tested just now and the script seems to work fine.
