### ISSUE TITLE
Unittest test_sslv2_enabled "WARNING: can't open config file: /usr/local/ssl/openssl.cnf\n"

### ISSUE THREAD

**Issue by itlabitto** [nabla-c0d3/sslyze#267]
Running the test sslv2_enabled get this output:
```
test_sslv2_enabled (plugin_tests.test_openssl_cipher_suites_plugin.OpenSslCipherSuitesPluginTestCase) ... WARNING:root:s_server output: b"WARNING: can't open config file: /usr/local/ssl/openssl.cnf\n"
WARNING:root:s_server output: b'Using default temp DH parameters\n'
WARNING:root:s_server output: b'Using default temp ECDH parameters\n'
WARNING:root:s_server output: b'ACCEPT\n'
ok
```
Copied my local openssl.cnf file resolved the part "WARNING: can't open config file: /usr/local/ssl/openssl.cnf\n", but not the other 3 warnings.
Tested SSLyze against a server with SSLv2 enabled, it is detected correctly.

Test seems to pass ok, is needed any particular openssl.cnf file?
Do I need to import any root on local store?

**Comment by nabla-c0d3** [comment]
It's a warning from the OpenSSL binary at https://github.com/nabla-c0d3/sslyze/tree/master/tests/plugin_tests/openssl_server . We can safely ignore it.
