### ISSUE TITLE
Is it is legal to scan someone else's website?

### ISSUE THREAD

**Issue by vaibhavmule** [nabla-c0d3/sslyze#269]
All the plugin or scanner in sslyze,
 is it  ethical to scan without the consent of website owner?

**Comment by ericrange** [comment]
what do you mean? is it ethical to scan a persons clothes or behaviour to get an impression of that person? you dont steal  anything. you dont hack anything. you just watch what features are enabled.
all browsers or other type of software do "nearly" the same thing as sslyze.
a browser needs to know which ciphers or features the server supports and afterswards use this to communicate with it.

**Comment by ericrange** [comment]
so, actually you asked "if its ethical to visit a website without the consent of website owner?"
i think, yes^^

**Comment by vaibhavmule** [comment]
I get your point. I was just curious because I was looking at https://law.stackexchange.com/questions/2033/legality-of-scanning-a-site-with-ssllabs-ssl-server-test-in-order-to-find-and-re

**Comment by ericrange** [comment]
good point. in general, i do not really understand the law at this point. (either in us, uk or germany).
various bots are scanning all websites they can find to inject remote scripts or etc.
there is nobody who cares... it is just like "the web is like it is"...
but if you want to detect vulnerabitlities to tell the organisation (maybe they book your services to prevent this vulnerabilities) this is strictly prohibited...
bad guys: who cares???
good guys: legal proceedings :D

**Comment by vaibhavmule** [comment]
Okay, This I feel resolved my issues and Thanks.
