### ISSUE TITLE
ROBOT attack (Return of Bleichenbacher's Oracle Threat)

### ISSUE THREAD

**Issue by ericrange** [nabla-c0d3/sslyze#270]
Maybe as a new plugin?
https://github.com/robotattackorg/robot-detect/blob/master/robot-detect

**Comment by nabla-c0d3** [comment]
Yes, I need to adapt the test script.

**Comment by ericrange** [comment]
I sent you a vulnerable server per mail

**Comment by ericrange** [comment]
but please dont use the address in public tests

**Comment by nabla-c0d3** [comment]
Cool! That will be very helpful!!

**Comment by glestel** [comment]
I have access to domains hosted by Semi vulnerable and Totally vulnerable F5, I can check if the test works if you release it on an early branch, if it can helps

**Comment by nabla-c0d3** [comment]
@glestel I have pushed a first implementation (needs to be cleaned etc) to the branch - can you try it out on your servers?
Thanks!

**Comment by nabla-c0d3** [comment]
This was released as part of 1.3.0

**Comment by nabla-c0d3** [comment]
@ericrange the test server was very helpful

**Comment by glestel** [comment]
Thanks for the works. However it's giving me false negatives on my targets (hosted by some F5), but both testssl.sh and the robot-detect script are giving me a vulnerable status.
I've notified that the sslyze scan runs very quickly compared to others tools. Could it be linked to the fact that I'm running sslyze with python 2.7 ?

**Comment by nabla-c0d3** [comment]
Do you have domain names that you could email me?

**Comment by nabla-c0d3** [comment]
And can you try with Python 3 ?

**Comment by glestel** [comment]
I'll try with python 3.
Sent you a mail with a supposed vulnerable domain

**Comment by nabla-c0d3** [comment]
It should be fixed for the domain you sent me in v1.3.1 that I just released.

**Comment by glestel** [comment]
It's working fine with your bug fix, thank you !
