### ISSUE TITLE
Support multiple Java trust stores

### ISSUE THREAD

**Issue by myniva** [nabla-c0d3/sslyze#273]
While I agree that Java 7 is most likely the Java version which is widest spread, there are still a lot of applications running on Java 6. Beside that, Java 8 & Java 9 have been released as well.

It would be helpful to have support for trust stores of more than one Java version.

**Comment by nabla-c0d3** [comment]
The `--ca_file` can be used to test another trust store. Supporting every Java version is too specific for most users.
