### ISSUE TITLE
Any plans for adding BEAST, CRIME, POODLE, Lucky13 and Shellshock these plugins?

### ISSUE THREAD

**Issue by vaibhavmule** [nabla-c0d3/sslyze#275]

**Comment by nabla-c0d3** [comment]
CRIME already has a plugin, BEAST and Lucky13 can be checked via the cipher suite plugin and shellshock affects bash so it's not in scope for SSLyze.

**Comment by vaibhavmule** [comment]
Okay, Thanks Alban.
