### ISSUE TITLE
Crashes while checking certain servers

### ISSUE THREAD

**Issue by SQ-SEN** [nabla-c0d3/sslyze#279]
sslyze crashes with a segmentation fault when checking certain servers.

Example:
sslyze --regular portal.stadtwerke-schwetzingen.de:443

Version: 1.2.0 Windows pre build exe from release tab running in 64bit Cygwin bash shell. 

Sorry I didn't find time to setup the dev environment to test 1.31. :(

**Comment by nabla-c0d3** [comment]
Hello,
Sorry I don't support Cygwin and older versions of SSLyze - try using Python 3.6 for Windows and SSLyze 1.3.1?
