### ISSUE TITLE
Scan command failed: [' * Certificate Information:', 'Unhandled exception while running --certinfo:', "TypeError - object of type 'UnrecognizedExtension' has no len()"]

### ISSUE THREAD

**Issue by ericrange** [nabla-c0d3/sslyze#281]
Is this a known bug?

**Comment by ericrange** [comment]
On a 5 min old ubuntu (16.04) machine: for reproduction
![image](https://user-images.githubusercontent.com/1785416/34784331-403e9af6-f62e-11e7-91d3-8853a9aab6cc.png)

**Comment by ericrange** [comment]
This is what i did after vm setup:
apt update && apt upgrade -Y
apt-get install python3-pip
apt-get install python3-setuptools
apt-get install python3-dev
apt-get install libffi-dev
apt-get install libssl-dev
apt-get install libmpc-dev  
apt-get install libgmp3-dev
pip3 install gmpy2
python3 setup.py install
python3 __main__.py

**Comment by ericrange** [comment]
ok... if i do the same on debian... its works... mh :/

**Comment by glestel** [comment]
I got this also on my ubuntu if I install sslyze with a `sudo pip install` (I know, bad practice). But creating a new virtualenv with forced download, it works.
Might be a compatibility issue with old dependencies

**Comment by nabla-c0d3** [comment]
Always make sure to run `pip install -r requirements.txt --upgrade` first. Your error seems to be caused by an outdated version of the `cryptography` module.
