### ISSUE TITLE
Ciphers always randomly time out

### ISSUE THREAD

**Issue by koczkatamas** [nabla-c0d3/sslyze#286]
I simply cannot configure sslyze not to time out on almost every run.

Could you recommend a configuration which works reliably?

Currently I run it the following way: `sslyze-1_3_2\sslyze --timeout=120 --nb_retries=50 --json_out=result_tresorit.com.json --regular tresorit.com`

OSes I tested with: 
- Windows Server 2016 (1607) with latest updates (natively, not in WSL), VM: ~always times out
- Windows 10 (1709) with latest updates (16299.192), physical machine: times out on every second run

Run #1:
```
 * ROBOT Attack:
                                          OK - Not vulnerable

 * TLSV1 Cipher Suites:
     Undefined - An unexpected error happened:
        TLS_DH_RSA_WITH_AES_256_CBC_SHA                   timeout - timed out
        TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA             timeout - timed out

 * TLSV1_1 Cipher Suites:
     Undefined - An unexpected error happened:
        TLS_ECDH_anon_WITH_AES_256_CBC_SHA                timeout - timed out
        TLS_DH_RSA_WITH_CAMELLIA_256_CBC_SHA              timeout - timed out
        TLS_DH_DSS_WITH_CAMELLIA_256_CBC_SHA              timeout - timed out
        TLS_DHE_DSS_WITH_AES_256_CBC_SHA                  timeout - timed out
```

Run #2:
```
 * ROBOT Attack:
                                          UNKNOWN - Received inconsistent results

 * TLSV1_2 Cipher Suites:
     Undefined - An unexpected error happened:
        TLS_DH_anon_WITH_AES_256_GCM_SHA384               timeout - timed out
        TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA             timeout - timed out
```

Run #3:
```
 * ROBOT Attack:
                                          OK - Not vulnerable

 * SSLV3 Cipher Suites:
      Server rejected all cipher suites.
     Undefined - An unexpected error happened:
        TLS_DHE_RSA_WITH_AES_256_CBC_SHA                  timeout - timed out
```

Run #4:
```
 * ROBOT Attack:
                                          OK - Not vulnerable

 * SSLV3 Cipher Suites:
      Server rejected all cipher suites.
     Undefined - An unexpected error happened:
        TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA             timeout - timed out
        TLS_DHE_DSS_WITH_AES_256_CBC_SHA                  timeout - timed out
        TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA                 timeout - timed out

 * TLSV1_2 Cipher Suites:
     Undefined - An unexpected error happened:
        TLS_RSA_WITH_SEED_CBC_SHA                         timeout - timed out
        TLS_DHE_RSA_WITH_AES_128_GCM_SHA256               timeout - timed out
        RSA_WITH_AES_256_CCM                              timeout - timed out
```

It looks totally random which cipher fails and which not. Also the ROBOT Attack check is not stable. And it finishes fast (in 18-20 seconds), I am pretty sure it does not retry 50 times or it does too fast, it does not matter at all.

Any idea why does this happen?

I started to dig deeper (aka started monitoring the requests with Wireshark), but I only saw that some connections were not closed properly, and kept alive until the process finished, but they are NOT the same connections which are timed out. So this can only cause problem if there is some active connection per host limit somewhere...

Older `sslyze` version (sadly I don't know which one) worked reliably, but now I wanted to update to the latest (1.3.2).

**Comment by nabla-c0d3** [comment]
Does it work better if you only run one scan command (such as `--tlsv1`) ?
If yes it means that the server cannot handle all the concurrent connections, in which case I might need to add a new flag for this.

**Comment by koczkatamas** [comment]
I tried to run `sslyze-1_3_2\sslyze --timeout=120 --nb_retries=50 --json_out=result_tresorit.com.json --tlsv1 tresorit.com` and I got on the first try:

```
 SCAN RESULTS FOR TRESORIT.COM:443 - 191.235.160.13
 --------------------------------------------------

 * TLSV1 Cipher Suites:
     Preferred:
        TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA                ECDH-256 bits  256 bits
     Accepted:
        TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA                ECDH-256 bits  256 bits
        TLS_RSA_WITH_AES_256_CBC_SHA                      -              256 bits
        TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA                ECDH-256 bits  128 bits
        TLS_RSA_WITH_AES_128_CBC_SHA                      -              128 bits
     Undefined - An unexpected error happened:
        TLS_RSA_WITH_CAMELLIA_256_CBC_SHA                 timeout - timed out
        TLS_ECDH_anon_WITH_NULL_SHA                       timeout - timed out
        TLS_ECDH_RSA_WITH_NULL_SHA                        timeout - timed out
        TLS_ECDH_RSA_WITH_AES_128_CBC_SHA                 timeout - timed out
        TLS_ECDH_ECDSA_WITH_NULL_SHA                      timeout - timed out
     Rejected:
        TLS_RSA_WITH_SEED_CBC_SHA                         TCP / Received FIN
        TLS_RSA_WITH_RC4_128_SHA                          TCP / Received FIN
        TLS_RSA_WITH_RC4_128_MD5                          TCP / Received FIN
...
```

Second try:

```
   Undefined - An unexpected error happened:
        TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA             timeout - timed out
        TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA                 timeout - timed out
```

Third try:
```
     Undefined - An unexpected error happened:
        TLS_DH_RSA_WITH_AES_128_CBC_SHA                   timeout - timed out
        TLS_DH_DSS_WITH_AES_128_CBC_SHA                   timeout - timed out
```

I tried to track down the issue with Wireshark, for example on one try the `TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA` cipher failed. Usually `sslyze` makes ~124 request for a full test (only one domain, `--tlsv1`) and this failed request was the 61st TCP connection (so there were a ton of good connections before and after this one), and even with `--nb_retries=50` and `--timeout=120` it finished in `19.33` seconds, while only tried to test the `TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA` cipher once. Although as you can see on the screenshot below that test failed miserably on TCP level:

![image](https://user-images.githubusercontent.com/2608082/35563934-c02ea8ca-05b8-11e8-9f0e-1f951282c4d7.png)

So I think the retry logic does not work correctly. (Or I misunderstood the purpose of the `nb_retries` parameter).

I attached the whole Wireshark capture: [sslyze_time_out_issue.zip](https://github.com/nabla-c0d3/sslyze/files/1677471/sslyze_time_out_issue.zip)

The website is a standard Azure Web App (hosting only static pages): https://azure.microsoft.com/en-us/services/app-service/web/

**Comment by nabla-c0d3** [comment]
Can you send me a hostname so I can test this myself? Thanks!

**Comment by koczkatamas** [comment]
Yeah sure, it's `tresorit.com`.

You can find the exactly command line I used for my tests in my previous comments.

**Comment by koczkatamas** [comment]
Hmmm, I tried to run on my current internet (which is a more robust one than I used previously), and here it does not time out.

So I presume the server itself can handle the test / traffic, the problem if you are on an unreliable network then and a request times out because the network and then `sslyze` does not try it again somehow. So maybe the retry logic does not work if the timeout (exception?) comes at the wrong time.

I will try to debug it out what code path runs when the exception happens when I will be on the unreliable network again.

**Comment by nabla-c0d3** [comment]
Yeah SSLyze requires a fast Internet connection, and not even the number of retries of timeouts can really help. I could add an option to have it use less resources if the connection (or the server) is slow,

**Comment by koczkatamas** [comment]
I think the main priority should be make the retry work.

I haven't got the time to track it down why sslyze doesn't try it again if the connection times out once. Do you have any idea?

If the retry logic would work then I think it would be possible to run the test without errors (it would finish I little slower I presume, but that's okay).

**Comment by nabla-c0d3** [comment]
Once it's released, please try `--slow_connection` and let me know if it worked. I removed `--nb_retries` and `--timeout` because they don't work very well and are a bit too complex. They're still available tho when using the Python API.

**Comment by nabla-c0d3** [comment]
Yes it mainly affects the `ConcurrentScanner` (hence the change with `--slow_connection`, but some servers that are really limited in resources can't handle the cipher suites scan (even with the `SynchronousScanner`), which is why I reduced the number of threads in my commit above (which makes a cipher suite scan open less concurrent connections).

As for `--slow-connection`, yes your understanding is correct.
