### ISSUE TITLE
Distrusted Symantec CAs

### ISSUE THREAD

**Issue by rosenhagen** [nabla-c0d3/sslyze#288]
Hello,

I set out to batch-check if our customers are affected by the upcoming changes in Google Chrome and Firefox regarding Symantec's certificates (https://blog.chromium.org/2018/02/a-secure-web-is-here-to-stay.html). To my surprise, I'm having quite a hard time doing that. 

As far as I understand:
- The average webmaster maybe does not necessarily know which brands belong to Symantec (Thawte, RapidSSL and GeoTrust).
- Right at the moment, the affected certificates are still in the trust stores. So obviously, sslyze will tell me that my certificate is OK, even when in some weeks my website will be effectively down for certain browsers.

I guess many websites will miss a lot of users on the day when this hits. So I'm wondering how could I check for this issue in advance?

As far as I understand: If I had a trust store that already reflects the upcoming changes in Chrome / Firefox I could use that with sslyze. For example, would it be possible to filter the affected cerfificates out when doing a "--update_trust_stores"? 

For example, Google Chrome seems to have a hardcoded list in the source to issue warnings in the browser console, but I have no clue how to make this usable.

**Comment by nabla-c0d3** [comment]
The right approach is to extend CertificateInfoPluginto to use the server's verified certificate chain, and then look at the CA certificate to see if it is Symantec. Then, the plugin can check the date when the leaf certificate was issued and return the right information to the user on when the certificate will stop working. 
The code is there basically: https://github.com/nabla-c0d3/sslyze/blob/master/sslyze/plugins/certificate_info_plugin.py#L302

I would definitely merge a pull request that provides this functionality!
