### ISSUE TITLE
Unable to get authenticated into the target website with a client-side certificate

### ISSUE THREAD

**Issue by h-rueda** [nabla-c0d3/sslyze#289]
Command used:

`sslyze <host>:443 --cert <certificate in PEM format> --key <key in PEM format withou password>`

Output:
`WARNING: Server REQUIRED client authentication, specific plugins will fail.`

Tested with versions 1.3.2 and 1.3.4

**Comment by nabla-c0d3** [comment]
Hello and thanks for the report. I will first have to setup a test server with client authentication so that I can reproduce this.

**Comment by nabla-c0d3** [comment]
It should be fixed in v1.4.0.
