### ISSUE TITLE
Unhandled exception while running --reneg

### ISSUE THREAD

**Issue by jammasterj89** [nabla-c0d3/sslyze#290]
Hi,

Running the latest sslyze v1.3.4 against a Jetty server that has its renegotiation setting set to [false](https://www.eclipse.org/jetty/documentation/current/configuring-ssl.html) and I get the following error:

> Unhandled exception while running --reneg:
> OpenSSLError - error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error

This is from Ubuntu and Kali Linux using OpenSSL version 1.1.0e.

Thanks for the awesome tool!

**Comment by nabla-c0d3** [comment]
Thanks for the report.
