### ISSUE TITLE
What is the best way to add a private CA to sslyze?

### ISSUE THREAD

**Issue by marcb** [nabla-c0d3/sslyze#291]
In corporate environments there is often private CAs. Is there any documentation on how to load an additional CA?

**Comment by glestel** [comment]
Convert your root CA to .pem and then when you call sslyze : 
`sslyze --certinfo --ca_file=Path/To/CA.pem test.evil.corp`

**Comment by marcb** [comment]
Thanks! I'll give it ago.

**Comment by nabla-c0d3** [comment]
Thanks @glestel =)
