### ISSUE TITLE
Unhandled exception while running --certinfo

### ISSUE THREAD

**Issue by hackerabhinavverma** [nabla-c0d3/sslyze#293]
I Was getting this error after updating the sslyze recently. Before i was getting proper result for certificate information 

can you please look  into this 

> sslyze --certinfo www.facebook.com
> 
>  AVAILABLE PLUGINS
>  -----------------
> 
>   HeartbleedPlugin
>   SessionRenegotiationPlugin
>   RobotPlugin
>   HttpHeadersPlugin
>   CertificateInfoPlugin
>   FallbackScsvPlugin
>   OpenSslCcsInjectionPlugin
>   CompressionPlugin
>   OpenSslCipherSuitesPlugin
>   SessionResumptionPlugin
> 
> 
> 
>  CHECKING HOST(S) AVAILABILITY
>  -----------------------------
> 
>    www.facebook.com:443                       => 157.240.16.35 
> 
> 
>  SCAN RESULTS FOR WWW.FACEBOOK.COM:443 - 157.240.16.35
>  -----------------------------------------------------
> 
>  * Certificate Information:
> Unhandled exception while running --certinfo:
> TypeError - object of type 'UnrecognizedExtension' has no len()
> 
> 
>  SCAN COMPLETED IN 0.28 S
>  ------------------------

**Comment by nabla-c0d3** [comment]
How did you install and SSLyze and which system are you on? Your `cryptography` Python library is outdated.

**Comment by hackerabhinavverma** [comment]
I am using MAC OS, I have check my python library it is updated to version 2.1.4 and i have installed the sslyze with the help of brew. I didnt had this problem with the older release of sslyze. but getting this in this version.

Below is the terminal snip of python cyptography, sslyze and python version


> abhinav:~ averma5$ pip show cryptography
> **Name: cryptography
> Version: 2.1.4**
> Summary: cryptography is a package which provides cryptographic recipes and primitives to Python developers.
> Home-page: https://github.com/pyca/cryptography
> Author: The cryptography developers
> Author-email: cryptography-dev@python.org
> License: BSD or Apache License, Version 2.0
> Location: /Library/Python/2.7/site-packages
> Requires: six, cffi, enum34, idna, asn1crypto, ipaddress
> abhinav:~ averma5$ brew install sslyze --update
> Warning: **sslyze 1.3.4 is already installed**
> abhinav:~ averma5$ python --version
> **Python 2.7.10**

**Comment by hackerabhinavverma** [comment]
Resolved Used below commands.

> sudo pip wheel sslyze
> sudo pip install SSLyze-1.3.4-py2-none-any.whl
> sudo python -m sslyze --update_trust_stores

Thank You for support :)

**Comment by nabla-c0d3** [comment]
Sure
