### ISSUE TITLE
Unhandled exception while running --certinfo

### ISSUE THREAD

**Issue by jammasterj89** [nabla-c0d3/sslyze#297]
I've just upgraded sslyze on Ubuntu 16.04 to 1.3.4 via "pip install sslyze --upgrade", and now I am seeing the following error:

> * Certificate Information:
> Unhandled exception while running --certinfo:
> IOError - [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist packages/sslyze/plugins/utils/trust_store/pem_files/java.yaml'

Now that java.yaml is indeed missing on my system. However, I've installed 1.3.4 on Kali Linux via pip and I do not see that error, but the java.yaml file doesn't exist on that system either.

Thanks for the awesome tool!

**Comment by nabla-c0d3** [comment]
This seems to be a problem with your environment. There is no reference to `java.yaml` anywhere in SSLyze or trust_store_observatory,
