### ISSUE TITLE
Allow IP addresses with proxy settings

### ISSUE THREAD

**Issue by sclikaflon** [nabla-c0d3/sslyze#298]
In class `ServerConnectivityInfo`, parameter `ip_address` should be allowed and used even if `http_tunneling_settings` is supplied.

Example situation: MyCompany has a service myservice.com that resolves to two IP addresses, and MyCompany's sysadmin would like to sslyze both servers independently from his office network, which can only happen through the company's proxy.

**Comment by nabla-c0d3** [comment]
Hello,
As far as I know there is no mechanism to pass an IP address to use to a CONNECT proxy; the proxy will always do DNS resolution itself, based on URL's hostname. It's not a limitation in SSLyze but in how proxies work.
One workaround in your example would be to pass an IP address as the `hostname`; this will force the proxy to connect using this IP address.
