### ISSUE TITLE
Does not work with proxies anymore

### ISSUE THREAD

**Issue by sclikaflon** [nabla-c0d3/sslyze#299]
Hi,

The last version doesn't work with proxy settings anymore, as it tries a DNS resolution instead of letting the proxy do so.

https://github.com/nabla-c0d3/sslyze/blob/7cbea873a73922d16dd6e76bcd57f4497046711d/sslyze/server_connectivity_tester.py#L190

Thanks for your great tool !

**Comment by nabla-c0d3** [comment]
Thanks for the report
