### ISSUE TITLE
SSLyze reports an unhandled exception scanning a site

### ISSUE THREAD

**Issue by hjcoumans** [nabla-c0d3/sslyze#302]
Maybe related to my other error report, this site triggers an unhandled exception running a 'regular' scan.

Reproducible: Not permanent: 2/3 had the unhandled exception at the session renegotiation, 1/3 didn't while the ROBOT result was UNKNOWN (didn't look much further)

The same 2.4 version is used that got installed using the 2 pip commands from the README.md file on Kali in a VirtualBox VM (W10 host)
Unedited output of the command:

root@kali:~# sslyze --regular anamidp.services.uu.nl

 AVAILABLE PLUGINS
 -----------------

  OpenSslCipherSuitesPlugin
  HttpHeadersPlugin
  SessionRenegotiationPlugin
  CertificateInfoPlugin
  RobotPlugin
  FallbackScsvPlugin
  OpenSslCcsInjectionPlugin
  HeartbleedPlugin
  CompressionPlugin
  SessionResumptionPlugin

 CHECKING HOST(S) AVAILABILITY
 -----------------------------

   anamidp.services.uu.nl:443                       => 131.211.10.62 

 SCAN RESULTS FOR ANAMIDP.SERVICES.UU.NL:443 - 131.211.10.62
 -----------------------------------------------------------

 * ROBOT Attack:
                                          VULNERABLE - Strong oracle, a real attack is possible

 * SSLV2 Cipher Suites:
      Server rejected all cipher suites.
     Undefined - An unexpected error happened:
        SSL_CK_RC4_128_WITH_MD5                           timeout - timed out                                         
        SSL_CK_RC2_128_CBC_EXPORT40_WITH_MD5              timeout - timed out                                         
        SSL_CK_DES_64_CBC_WITH_MD5                        timeout - timed out                                         

 * Downgrade Attacks:
       TLS_FALLBACK_SCSV:                 OK - Supported

 * OpenSSL Heartbleed:
                                          OK - Not vulnerable to Heartbleed

 * TLSV1_2 Cipher Suites:
     Preferred:
        TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384             ECDH-256 bits  256 bits      HTTP 403 Forbidden                                          
     Accepted:
        TLS_RSA_WITH_AES_256_CBC_SHA256                   -              256 bits      HTTP 403 Forbidden                                          
        TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384             ECDH-256 bits  256 bits      HTTP 403 Forbidden                                          
        TLS_DHE_RSA_WITH_AES_256_CBC_SHA256               DH-2048 bits   256 bits      HTTP 403 Forbidden                                          
        TLS_DHE_RSA_WITH_AES_256_CBC_SHA                  DH-2048 bits   256 bits      HTTP 403 Forbidden                                          
        TLS_DHE_RSA_WITH_AES_256_GCM_SHA384               DH-2048 bits   256 bits      HTTP 403 Forbidden                                          
        TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384             ECDH-256 bits  256 bits      HTTP 403 Forbidden                                          
        TLS_RSA_WITH_AES_256_CBC_SHA                      -              256 bits      HTTP 403 Forbidden                                          
        TLS_RSA_WITH_AES_256_GCM_SHA384                   -              256 bits      HTTP 403 Forbidden                                          
        TLS_DHE_RSA_WITH_AES_128_CBC_SHA256               DH-2048 bits   128 bits      HTTP 403 Forbidden                                          
        TLS_RSA_WITH_AES_128_CBC_SHA256                   -              128 bits      HTTP 403 Forbidden                                          
        TLS_DHE_RSA_WITH_AES_128_GCM_SHA256               DH-2048 bits   128 bits      HTTP 403 Forbidden                                          
        TLS_RSA_WITH_AES_128_GCM_SHA256                   -              128 bits      HTTP 403 Forbidden                                          
        TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256             ECDH-256 bits  128 bits      HTTP 403 Forbidden                                          
        TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256             ECDH-256 bits  128 bits      HTTP 403 Forbidden                                          
        TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA                 -              112 bits      HTTP 403 Forbidden                                          
        TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA               ECDH-256 bits  112 bits      HTTP 403 Forbidden                                          
     Undefined - An unexpected error happened:
        TLS_RSA_WITH_NULL_SHA256                          timeout - timed out                                         
        TLS_ECDHE_RSA_WITH_CAMELLIA_256_CBC_SHA384        OpenSSLError - error:1409441A:SSL routines:ssl3_read_bytes:tlsv1 alert decode error

        TLS_ECDHE_RSA_WITH_CAMELLIA_128_CBC_SHA256        OpenSSLError - error:1409441A:SSL routines:ssl3_read_bytes:tlsv1 alert decode error

        TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256     OpenSSLError - error:1409441A:SSL routines:ssl3_read_bytes:tlsv1 alert decode error

        TLS_ECDHE_ECDSA_WITH_CAMELLIA_256_CBC_SHA384      OpenSSLError - error:1409441A:SSL routines:ssl3_read_bytes:tlsv1 alert decode error

        TLS_ECDHE_ECDSA_WITH_CAMELLIA_128_CBC_SHA256      OpenSSLError - error:1409441A:SSL routines:ssl3_read_bytes:tlsv1 alert decode error

        TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384           timeout - timed out                                         
        ECDHE_ECDSA_WITH_AES_256_CCM_8                    OpenSSLError - error:1409441A:SSL routines:ssl3_read_bytes:tlsv1 alert decode error

        ECDHE_ECDSA_WITH_AES_256_CCM                      OpenSSLError - error:1409441A:SSL routines:ssl3_read_bytes:tlsv1 alert decode error

        ECDHE_ECDSA_WITH_AES_128_CCM_8                    timeout - timed out                                         
        ECDHE_ECDSA_WITH_AES_128_CCM                      OpenSSLError - error:1409441A:SSL routines:ssl3_read_bytes:tlsv1 alert decode error

 * Deflate Compression:
                                          OK - Compression disabled

 * Resumption Support:
      With Session IDs:                  OK - Supported (5 successful, 0 failed, 0 errors, 5 total attempts).
      With TLS Tickets:                  NOT SUPPORTED - TLS ticket not assigned.

 * TLSV1_3 Cipher Suites:
      Server rejected all cipher suites.
     Undefined - An unexpected error happened:
        TLS_CHACHA20_POLY1305_SHA256                      OpenSSLError - error:1409441A:SSL routines:ssl3_read_bytes:tlsv1 alert decode error

        TLS_AES_128_CCM_8_SHA256                          OpenSSLError - error:1409441A:SSL routines:ssl3_read_bytes:tlsv1 alert decode error

 * TLSV1 Cipher Suites:
     Preferred:
        TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA               ECDH-256 bits  112 bits      HTTP 403 Forbidden                                          
     Accepted:
        TLS_DHE_RSA_WITH_AES_256_CBC_SHA                  DH-2048 bits   256 bits      HTTP 403 Forbidden                                          
        TLS_RSA_WITH_AES_256_CBC_SHA                      -              256 bits      HTTP 403 Forbidden                                          
        TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA                 DH-2048 bits   112 bits      HTTP 403 Forbidden                                          
        TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA               ECDH-256 bits  112 bits      HTTP 403 Forbidden                                          
     Undefined - An unexpected error happened:
        TLS_RSA_WITH_IDEA_CBC_SHA                         timeout - timed out                                         
        TLS_RSA_WITH_3DES_EDE_CBC_SHA                     timeout - timed out                                         
        TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA               timeout - timed out                                         
        TLS_DH_anon_WITH_3DES_EDE_CBC_SHA                 timeout - timed out                                         
        TLS_DH_RSA_WITH_3DES_EDE_CBC_SHA                  timeout - timed out                                         
        TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA                 timeout - timed out                                         

 * Session Renegotiation:
Unhandled exception while running --reneg:
error - [Errno 104] Connection reset by peer

 * SSLV3 Cipher Suites:
      Server rejected all cipher suites.
     Undefined - An unexpected error happened:
        TLS_DH_anon_WITH_CAMELLIA_256_CBC_SHA             timeout - timed out                                         
        TLS_DHE_DSS_WITH_AES_256_CBC_SHA                  timeout - timed out                                         

 * OpenSSL CCS Injection:
                                          OK - Not vulnerable to OpenSSL CCS injection

 * Certificate Information:
     Content
       SHA1 Fingerprint:                  5cc6fed316d35d3e30470eff0624da516392fe1c
       Common Name:                       vip-accept.idp.its.uu.nl
       Issuer:                            TERENA SSL High Assurance CA 3
       Serial Number:                     10384425167131740573929358682805792372
       Not Before:                        2017-10-25 00:00:00
       Not After:                         2019-09-25 12:00:00
       Signature Algorithm:               sha256
       Public Key Algorithm:              RSA
       Key Size:                          4096
       Exponent:                          65537 (0x10001)
       DNS Subject Alternative Names:     [u'vip-accept.idp.its.uu.nl', u'anamidp.services.uu.nl', u'apassword.services.uu.nl', u'amysolisid.uu.nl', u'auserportal.services.uu.nl']

     Trust
       Hostname Validation:               OK - Certificate matches anamidp.services.uu.nl
       Android CA Store (8.1.0_r7):       OK - Certificate is trusted
       iOS CA Store (11):                 OK - Certificate is trusted
       macOS CA Store (High Sierra):      OK - Certificate is trusted
       Mozilla CA Store (2018-01-14):     OK - Certificate is trusted, Extended Validation
       Windows CA Store (2017-12-28):     OK - Certificate is trusted
       Received Chain:                    vip-accept.idp.its.uu.nl --> TERENA SSL High Assurance CA 3
       Verified Chain:                    vip-accept.idp.its.uu.nl --> TERENA SSL High Assurance CA 3 --> DigiCert High Assurance EV Root CA
       Received Chain Contains Anchor:    OK - Anchor certificate not sent
       Received Chain Order:              OK - Order is valid
       Verified Chain contains SHA1:      OK - No SHA1-signed certificate in the verified certificate chain

     Extensions
       OCSP Must-Staple:                  NOT SUPPORTED - Extension not found
       Certificate Transparency:          OK - 4 SCTs included

     OCSP Stapling
                                          NOT SUPPORTED - Server did not send back an OCSP response

 * TLSV1_1 Cipher Suites:
     Preferred:
        TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA               ECDH-256 bits  112 bits      HTTP 403 Forbidden                                          
     Accepted:
        TLS_RSA_WITH_AES_256_CBC_SHA                      -              256 bits      HTTP 403 Forbidden                                          
        TLS_DHE_RSA_WITH_AES_256_CBC_SHA                  DH-2048 bits   256 bits      HTTP 403 Forbidden                                          
        TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA               ECDH-256 bits  112 bits      HTTP 403 Forbidden                                          
        TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA                 DH-2048 bits   112 bits      HTTP 403 Forbidden                                          
     Undefined - An unexpected error happened:
        TLS_RSA_WITH_3DES_EDE_CBC_SHA                     timeout - timed out                                         
        TLS_ECDH_anon_WITH_AES_256_CBC_SHA                timeout - timed out                                         
        TLS_ECDHE_RSA_WITH_RC4_128_SHA                    timeout - timed out                                         
        TLS_DH_anon_WITH_SEED_CBC_SHA                     timeout - timed out                                         
        TLS_DH_anon_WITH_RC4_128_MD5                      timeout - timed out                                         
        TLS_DH_anon_EXPORT_WITH_RC4_40_MD5                timeout - timed out                                         
        TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA             timeout - timed out                                         
        TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA                 timeout - timed out                                         

 SCAN COMPLETED IN 66.42 S
 -------------------------

**Comment by nabla-c0d3** [comment]
Thanks for the report
