### ISSUE TITLE
Installation or execution from windows 7  PC

### ISSUE THREAD

**Issue by MarAlb2** [nabla-c0d3/sslyze#307]
Hi all, 

I try to install sslyze on a windows 7 PC

at first instance I try to use compiled version but it is not executed due to wrong python refences. I see this error trace 

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Security>dir
 Volume in drive C is System
 Volume Serial Number is 9209-0643

 Directory of C:\Security

03/21/2018  10:13 AM    <DIR>          .
03/21/2018  10:13 AM    <DIR>          ..
03/19/2018  04:05 AM    <DIR>          asn1crypto
03/11/2018  02:20 AM    <DIR>          cffi
03/19/2018  04:05 AM    <DIR>          collections
03/19/2018  04:05 AM    <DIR>          concurrent
03/19/2018  04:05 AM    <DIR>          cryptography
03/19/2018  04:05 AM    <DIR>          ctypes
11/25/2017  06:34 AM    <DIR>          distutils
03/19/2018  04:05 AM    <DIR>          email
03/19/2018  04:05 AM    <DIR>          encodings
11/25/2017  06:34 AM    <DIR>          html
03/19/2018  04:05 AM    <DIR>          http
03/19/2018  04:05 AM    <DIR>          idna
03/19/2018  04:05 AM    <DIR>          importlib
03/19/2018  04:05 AM    <DIR>          json
03/19/2018  04:05 AM    <DIR>          lib2to3
11/25/2017  06:34 AM    <DIR>          logging
03/19/2018  04:05 AM    <DIR>          multiprocessing
03/19/2018  04:05 AM    <DIR>          nassl
03/19/2018  04:05 AM    <DIR>          pem_files
11/25/2017  06:34 AM    <DIR>          pkg_resources
03/19/2018  04:05 AM    <DIR>          pycparser
03/19/2018  04:05 AM    <DIR>          pydoc_data
10/04/2017  02:28 AM           164,504 pyexpat.pyd
10/04/2017  02:27 AM         3,297,944 python36.dll
03/19/2018  04:05 AM           966,746 python36.zip
10/04/2017  02:28 AM            23,704 select.pyd
11/25/2017  06:34 AM    <DIR>          setuptools
03/19/2018  04:05 AM    <DIR>          sslyze
08/13/2017  01:40 AM            16,384 sslyze.exe
03/19/2018  04:05 AM    <DIR>          tls_parser
10/04/2017  02:27 AM           896,152 unicodedata.pyd
11/25/2017  06:34 AM    <DIR>          unittest
03/19/2018  04:05 AM    <DIR>          urllib
06/10/2016  07:46 AM            83,784 VCRUNTIME140.dll
03/19/2018  04:05 AM    <DIR>          xml
11/25/2017  06:34 AM    <DIR>          xmlrpc
10/04/2017  02:27 AM            78,488 _bz2.pyd
03/21/2018  10:18 AM                 0 _cffi_backend.cp36-win32.pyd
10/04/2017  02:27 AM           102,040 _ctypes.pyd
10/04/2017  02:27 AM           216,728 _decimal.pyd
10/04/2017  02:28 AM           163,992 _elementtree.pyd
10/04/2017  02:29 AM         1,121,432 _hashlib.pyd
10/04/2017  02:28 AM           183,960 _lzma.pyd
10/04/2017  02:28 AM            25,752 _multiprocessing.pyd
10/04/2017  02:28 AM            62,104 _socket.pyd
10/04/2017  02:29 AM         1,459,864 _ssl.pyd
              17 File(s)      8,863,578 bytes
              31 Dir(s)  129,479,225,344 bytes free

C:\Security>sslyze.exe --regular www.google.it
Traceback (most recent call last):
  File "D:\Python36-32\lib\site-packages\cx_Freeze\initscripts\__startup__.py",
line 14, in run
  File "D:\Python36-32\lib\site-packages\cx_Freeze\initscripts\Console.py", line
 26, in run
  File "sslyze\__main__.py", line 10, in <module>
  File "D:\GitHub\sslyze\sslyze\plugins\plugin_base.py", line 12, in <module>
  File "D:\GitHub\sslyze\sslyze\server_connectivity_info.py", line 6, in <module
>
  File "D:\Python36-32\lib\site-packages\nassl\ssl_client.py", line 7, in <modul
e>
ImportError: DLL load failed: %1 is not a valid Win32 application.

At second step I try to download ZIP code and compile it on my local PC in this way

C:\Security\compile>C:\Users\ma\PycharmProjects\training\venv\Scripts\pyth
on.exe setup_cx_freeze.py build_exe
Traceback (most recent call last):
  File "setup_cx_freeze.py", line 7, in <module>
    from cx_Freeze import setup, Executable
ModuleNotFoundError: No module named 'cx_Freeze'

C:\Security\compile>C:\Users\ma\PycharmProjects\training\venv\Scripts\pyth
on.exe setup_cx_freeze.py build_exe
Traceback (most recent call last):
  File "setup_cx_freeze.py", line 7, in <module>
    from cx_Freeze import setup, Executable
ModuleNotFoundError: No module named 'cx_Freeze'

C:\Security\compile>

I try to search cx_Freeze but it is not availabe in code or in python 3.6 libraries

How can I solve?

T&R
M.

**Comment by nottheend** [comment]
A virtual Python environment may help. It's possible to use the right versions then.
Like Anaconda on Windows

**Comment by nabla-c0d3** [comment]
If you have Python 3.6 you can do 

    Pip install sslyze

You don’t need to build the tool.
