### ISSUE TITLE
AttributeError: 'ConnectionResetError' object has no attribute 'server_info'

### ISSUE THREAD

**Issue by postmodern** [nabla-c0d3/sslyze#310]
sslyze 1.4.1 still cannot handle the ConnectionResetError and hangs. This happens roughly 8/10 times.

## Steps to Reproduce

<pre>
$ virtualenv -p python3 env
$ pip3 install sslyze==1.4.1
$ sslyze --regular --xml_out test_sslyze.xml sip.bmrn.com:4443 sip.bmrn.com:5061
...
CHECKING HOST(S) AVAILABILITY
-----------------------------

   sip.bmrn.com:4443                      => 12.201.116.24   WARNING: Server requested optional client authentication
Traceback (most recent call last):
  File "/home/postmodern/env/bin/sslyze", line 11, in <module>
    sys.exit(main())
  File "/home/postmodern/env/lib/python3.6/site-packages/sslyze/__main__.py", line 92, in main
    output_hub.server_connectivity_test_failed(connectivity_exception)
  File "/home/postmodern/env/lib/python3.6/site-packages/sslyze/cli/output_hub.py", line 52, in server_connectivity_test_failed
    out_generator.server_connectivity_test_failed(connectivity_error)
  File "/home/postmodern/env/lib/python3.6/site-packages/sslyze/cli/console_output.py", line 51, in server_connectivity_test_failed
  
  self._file_to.write(self.SERVER_ERROR_FORMAT.format(host=connectivity_error.server_info.hostname,
AttributeError: 'ConnectionResetError' object has no attribute 'server_info'
</pre>

## Expected Result

Exits with optional error code

## Actual Result

Hangs indefinitely

## Additional Info

    $ python3 --version
    Python 3.6.4

**Comment by nabla-c0d3** [comment]
Fixed in https://github.com/nabla-c0d3/nassl/commit/9095e41b889794c1421ca3de6349f481ddc7e3ac

**Comment by visum-hal** [comment]
ETA on nassl 1.1.3?

**Comment by postmodern** [comment]
@nabla-c0d3 awesome! Any idea when nassl-1.1.3 will be released?

**Comment by nabla-c0d3** [comment]
It's released now.
