### ISSUE TITLE
TypeError - object of type 'UnrecognizedExtension' has no len()

### ISSUE THREAD

**Issue by postmodern** [nabla-c0d3/sslyze#311]
### Steps to Reproduce

1. `pip3 install sslyze==1.4.1`
2. `sslyze --certinfo assets1.twitter.com`

### Expected Results

Normal output:

         Extensions
           OCSP Must-Staple:                  NOT SUPPORTED - Extension not found
           Certificate Transparency:          OK - 4 SCTs included

### Actual Results

    Unhandled exception while running --certinfo:
    TypeError - object of type 'UnrecognizedExtension' has no len()

### Additional Info

This only seems to happen under Python 3.5.2. It works as expected on Python 3.6.5.

**Comment by nabla-c0d3** [comment]
This is usually because of an outdated version of `cryptography`.
