### ISSUE TITLE
Unsure if issue?

### ISSUE THREAD

**Issue by 3x-M4ch1nA** [nabla-c0d3/sslyze#321]
After doing pip install --update sslyze, it downloaded and all, but i got this error here:
![sslyze](https://user-images.githubusercontent.com/34328981/43042578-63902edc-8dc5-11e8-98a9-b28b17c8f79f.png)

I figured, well, that says win32, not relevant to me... but not sure what it meant.

Then when following the guide, as you can see in above pic, the test command (highlighted) gave an error.

I modified the command a bit as you see later on, and the scan still continued.

any help is appreciated

**Comment by nabla-c0d3** [comment]
This is a problem in your environment; looks like you have multiple versions of Python installed but not sure.
