### ISSUE TITLE
Indicate if openssl is outdated as reason for missing SCT details

### ISSUE THREAD

**Issue by stefanb** [nabla-c0d3/sslyze#323]
https://github.com/nabla-c0d3/sslyze/blob/fa32ee143ef8e04ac86e97c2f698e19e062a2c97/sslyze/plugins/certificate_info_plugin.py#L461-L471

Instead of just 'OK - Extension present', it would be helpful to indicate that more details could be provided if openssl was upgraded by adding eg 
* ` (details unknown due to too old version of openssl)` or 
* ` (details require openssl version X or later)` if exact version is known

That was also suggested by @blshkv in #320 
Ported from [commit comment](https://github.com/nabla-c0d3/sslyze/commit/fa32ee143ef8e04ac86e97c2f698e19e062a2c97#commitcomment-29844797) as suggested by @blshkv

**Comment by blshkv** [comment]
I actually have the latest system openssl and this message is not correct. It would be good to know how to enable whatever is required

**Comment by blshkv** [comment]
Also, see: https://github.com/pyca/cryptography/issues/4333

**Comment by blshkv** [comment]
ok, I have reported the issue to the upstream as well, but it is possible to parse it from sslyze. Here is a tool with does it:
https://github.com/pierky/sct-verify/blob/master/sct-verify.py

**Comment by blshkv** [comment]
This bug is classic example why you should not use build your own libraries. Nassl builds 2 versions openssl and yet complain that the system openssl is too old. Don't build the latest version of the library then 😂

**Comment by nabla-c0d3** [comment]
Haha from my perspective that's actually the perfect example as to why it's better to build your own library:

* Nassl will work 100% the same regardless of what version of OpenSSL is on the system; all the features will work, no surprises. 
* Cryptography on the other hand uses the system's OpenSSL which directly led to the bug we're talking about here: different features depending on the version of OpenSSL on the system.

Of course I am not saying shared libraries should never be used, but in the case of "advanced"/new features of OpenSSL, it's great that nassl does not use them. 99% of users (including myself) do not care about what version of OpenSSL is on their system, and changing it is always a time-consuming ordeal.

**Comment by blshkv** [comment]
if you follow your logic you should also build cryptography and compile it against build-bin openssl library. The next thing you will bring the entire OS with one little tool (sslyze) and call it bloatware
