### ISSUE TITLE
Scanning SMTP Servers

### ISSUE THREAD

**Issue by RachelShieGT** [nabla-c0d3/sslyze#329]
I want to check what ciphers and protocols are used on an SMTP server using SSLyze. Does SSLyze work with mail servers, and if so, how is it different from running SSLyze with a web server? Is it just the difference between running SSLyze on a different port? I tried running SSLyze with some mail servers on port 25 and got a warning that SSLyze 'could not complete an SSL handshake'.  

Thank you so much for your help!

**Comment by nabla-c0d3** [comment]
Hi,
It depends how the SMTP server is configured. It's either a normal TLS service running on a different port, or a StartTLS service (more details at https://www.fastmail.com/help/technical/ssltlsstarttls.html). Both are supported by SSLyze; for scanning StartTLS servers, check out the `--starttls=smtp` command line option.
