### ISSUE TITLE
--hide_rejected_ciphers option for json and xml out

### ISSUE THREAD

**Issue by Prockwin** [nabla-c0d3/sslyze#330]
--hide_rejected_ciphers option not hide rejected ciphers into json and xml(with --xml_out or --json_out)

**Comment by nabla-c0d3** [comment]
This is intended to work only when using the CLI tool; the code parsing the XML or JSON data can easily filter rejected ciphers out.

**Comment by warburtron** [comment]
Any chance this issue can be re-evaluated? Code/JSON parsing is fine for a small number of scans, but when performing scans at a large scale the time taken to write and parse the file is considerable, and the extra disk space consumed is significant.
