### ISSUE TITLE
`pip install --upgrade sslyze` fails with `No matching distribution found for nassl<2.2.0,>=2.1.0`

### ISSUE THREAD

**Issue by bknowles** [nabla-c0d3/sslyze#333]
So, I was trying to install `pshtt`, which depends on `sslyze`.

But `sslyze` depends on `nassl`, and although the repo at https://github.com/nabla-c0d3/nassl seems to be up-to-date with version 2.1.0 (so the dependency should be valid), the `pip install` is failing because pip can't seem to find a compatible version in whatever cached locations it is using.

Here's the full error
```
$ pip install --upgrade sslyze
Collecting sslyze
  Using cached https://files.pythonhosted.org/packages/08/db/7f5e3aaefd126318e41717fa4f72bbb2fdb6b5563413b7ff56002b58e59a/sslyze-2.0.0.tar.gz
Collecting nassl<2.2.0,>=2.1.0 (from sslyze)
  Could not find a version that satisfies the requirement nassl<2.2.0,>=2.1.0 (from sslyze) (from versions: 0.13.4.win32, 0.13.1, 0.13.2, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.14.0, 0.14.1, 0.14.2, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.17.0, 1.0.1, 1.0.2, 1.0.3)
No matching distribution found for nassl<2.2.0,>=2.1.0 (from sslyze)
```

**Comment by bknowles** [comment]
I'm running on macOS Sierra 10.12.6.

**Comment by nabla-c0d3** [comment]
I think macOS 10.13 is required.

**Comment by bknowles** [comment]
@scovetta --

If the documentation says that it has been tested on Sierra (10.12), then I would expect it to actually work on Sierra.

If the code has been updated and no longer works on Sierra, then I would think that the documentation needs to be updated to reflect that fact.

Thanks!

**Comment by nabla-c0d3** [comment]
Yeah that's fair; I've updated the documentation.

**Comment by nabla-c0d3** [comment]
@scovetta Windows is now supported again (but with Python 64 bits only).

**Comment by ahrib** [comment]
> @scovetta Windows is now supported again (but with Python 64 bits only).
Awesome work! Confirming OK for me using Python 3.7 64 bit.
