### ISSUE TITLE
How to get SHA256 fingerprint of a certificate

### ISSUE THREAD

**Issue by yahanvesh** [nabla-c0d3/sslyze#337]
Currently i do not see any api which allows me to retrieve sha256 fingerprint, however i do see sha1Fingerprint when i do --certinfo with xml_out. Tried to search documentation, nothing came up.

**Comment by nabla-c0d3** [comment]
It's one line of code in Python using the certificates returned by SSLyze: https://github.com/nabla-c0d3/sslyze/blob/master/sslyze/plugins/certificate_info_plugin.py#L517
