### ISSUE TITLE
Python2.7

### ISSUE THREAD

**Issue by andresriancho** [nabla-c0d3/sslyze#341]
I'm investigating `sslyze` with the objective of adding it as a plugin to w3af, which is written in python2.7.

The `sslyze` documentation states that it supports python3.6+, but I just run a scan against yahoo.com using python2.7 and an unmodified `sslyze` and it worked.

Any ideas on which sections are py3k-only?

**Comment by nabla-c0d3** [comment]
You are probably using an older version (pre 2.0..0). The current version does not support Python 2 at all.

**Comment by andresriancho** [comment]
Ah, you're correct. Thanks!
