### ISSUE TITLE
SSLyze crashes when certificate has a country name not supported by cryptography

### ISSUE THREAD

**Issue by joyride9999** [nabla-c0d3/sslyze#342]
Hi,
there is an check in name.py that verifies that the country name attribute has 2 letters. While this looks ok as in rfc it states : 
ub-country-name-alpha-length INTEGER ::= 2
ub-country-name-numeric-length INTEGER ::= 3

My problem started because of the fact that i found some certificates that have 3 letters :), and this breaks sslyze. 
While is not really a bug in sslyze, could be a feature maybe to relax this check, and continue parsing the certificate ... !

name.py, line 52
>         if ( oid == NameOID.COUNTRY_NAME or oid == NameOID.JURISDICTION_COUNTRY_NAME):
>            if len(value.encode("utf8")) != 2:
>                raise ValueError(
>                    "Country name must be a 2 character country code"
>                )

**Comment by nabla-c0d3** [comment]
Hello,
Can you send me an example of a certificate (or domain with that kind of certificate)?
Thanks!

**Comment by joyride9999** [comment]
not sure i can do that, it's a work related machine. 
But the country oid field is set to net, and searching for more info i found this :
https://www.digicert.com/ssl-certificate-country-codes.htm
here at the end of the listing there are some 3 letters codes .  
COM US Commercial
EDU US Educational
GOV US Government
INT International
MIL US Military
NET Network
ORG Non-Profit Organization
ARPA Old style Arpanet

**Comment by nabla-c0d3** [comment]
As you noted, this is a bug in the certificate parsing library (ie. cryptography); if it is unable to parse the certificate, there's nothing SSLyze can do to recover from the error.
