### ISSUE TITLE
Parsable tag values

### ISSUE THREAD

**Issue by Tragen** [nabla-c0d3/sslyze#35]
When I export everything to an XML file, could you add
the validity in ISO format also?
e.g. instead of

```
<validity>
  <notAfter>May  9 21:58:25 2024 GMT</notAfter>
  <notBefore>May 12 21:58:25 2014 GMT</notBefore>
</validity>
```

it would be great to have the date and time in iso format e.g. with UTC time.
```
<validity_iso>
  <notAfter>2024-05-09 21:58:25</notAfter>
  <notBefore>2014-05-12 21:58:25</notBefore>
</validity>
```

and 

```
<publicKeySize>4096 bit</publicKeySize>
```

would be easier to have as

```
<publicKeySize>4096</publicKeySize>
```

as it's always in bit.

**Comment by nabla-c0d3** [comment]
#2 was fixed a few weeks ago, but the dates come straight from OpenSSL and I'd rather not try to sanitize OpenSSL's output. Also, the date in its current format is not ambiguous.
