### ISSUE TITLE
Feature request: Key Size of Private Key Server

### ISSUE THREAD

**Issue by nottheend** [nabla-c0d3/sslyze#354]
**Problem described:**
I want to know the key-size of the private key of the server via python-library, because a weak key is a serious security issue.

**Possible solution**
Getting the key-size of the server-key via python-library as part of `sslyze.plugins.certificate_info_plugin.CertificateInfoScanResult`.

**Possible alternatives**
It is possible to get the private key-size by using ssylze-terminal command.

**Additional info**
Thanks for building such a great tool!

**Comment by nabla-c0d3** [comment]
It is already returned or do you mean something else?
```
python -m sslyze --certinfo www.google.com

[...]
Key Size:                          256
[...]
```

**Comment by nottheend** [comment]
Exactly that value of key size - but want to access it via _python library_ and I couldn't find it in the [documentation of the scan command](https://nabla-c0d3.github.io/sslyze/documentation/available-scan-commands.html#sslyze.plugins.certificate_info_plugin.CertificateInfoScanResult)

Is it possible to access it via library?

**Comment by nabla-c0d3** [comment]
You need to parse the certificate (provided in PEM format by SSLyze) using the cryptography library.

**Comment by nottheend** [comment]
Thanks! That's what I was looking for. :+1:
