### ISSUE TITLE
Unable to build the verified certificate chain for some hosts

### ISSUE THREAD

**Issue by wondex** [nabla-c0d3/sslyze#355]
Hi Creator,

First of all, a nice tool ;)

SSLyze doesn't always include the subca pem and is_certificate_trusted isn't always correct (properly because of the missing pem).

**Describe the bug**
Two bugs that are related:
1. The SubCA is not always included ("commands_results"]["certinfo"]["certificate_chain"][1]["as_pem"]) is missing in the json file
2. The certificate trust (machine["commands_results"]["certinfo"]["path_validation_result_list"][N]["is_certificate_trusted"]) is not always correct, because of the missing subca

Using openssl and a webbrowser (mozilla firefox, google chrome and microsoft internet explorer) i'm able to see the complete certificate chain, but this is not always included in the json.
Example:
$ echo '' | openssl s_client -connect host.org.nl:443
depth=2 C = NL, O = Org, CN = Root CA - G1
depth=1 C = NL, O = Org, CN = Sub CA - G1
depth=0 C = NL, O = Org, OU = CAO SDS, CN = host.org.nl
verify return:1

**To Reproduce**
Only occurs with a limit amount (~10) of hosts using the local issuer, can't reproduce at this point.

**Expected behavior**
Inclusion of the subca (as_pem)
and correct verification of the custom (is_certificate_trusted)

**Python environment (please complete the following information):**

	SSLyze version:
		$ /opt/rh/rh-python36/root/bin/python -m sslyze --version
		2.0.3

	OS version:
		$ cat /etc/os-release | grep "REDHAT"
		REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
		REDHAT_BUGZILLA_PRODUCT_VERSION=7.5
		REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
		REDHAT_SUPPORT_PRODUCT_VERSION="7.5"

	Python version:
		$ /opt/rh/rh-python36/root/bin/python --version
		Python 3.6.3

**Additional context**
-

Best Regards

**Comment by nabla-c0d3** [comment]
It sounds like this host's certificate chains up to a private CA cert, which SSLyze doesn't know about. Have you tried passing the CA cert using `--ca_file` ? I would need more details to be able to reproduce this (such as a host that I can reach).

**Comment by nabla-c0d3** [comment]
I can now reproduce this; it happens in `TrustStore.build_verified_certificate_chain()` when the server sent the certificate chain in the wrong order.

**Comment by wondex** [comment]
Hi,

Nice that this issue could be reproduced.
Is there any roadmap to solve this issue? 

Best regards

**Comment by nabla-c0d3** [comment]
The fix was released with v2.1.0.
