### ISSUE TITLE
SymantecCert check contains extraneous characters in CA_KEYS_BLACKLIST

### ISSUE THREAD

**Issue by yahanvesh** [nabla-c0d3/sslyze#356]
**Describe the bug**
The Symantec Cert check code has invalid characters in one of the CA KEYS BLACKLIST
https://github.com/nabla-c0d3/sslyze/blame/d974dc1ce5828c3978029ca954f0d1fc0ce30fea/sslyze/plugins/certificate_info_plugin.py#L756

There are extraneous characters ]]  if you compare with https://cs.chromium.org/chromium/src/net/cert/symantec_certs.cc?l=118

**Comment by nabla-c0d3** [comment]
Fix released with v2.0.4.
