### ISSUE TITLE
OCSP check fails using proxy option

### ISSUE THREAD

**Issue by wondex** [nabla-c0d3/sslyze#365]
Hi,

Currently scanning some external websites using the proxy option in sslyze. But the OCSP validation fails.

JSON result:
is_ocsp_response_trusted: null
ocsp_response: null
ocsp_response_status: null

Is this related to OpenSSL? 
Is it possible to solve this?

Best regards

**Comment by nabla-c0d3** [comment]
Hi, 
An HTTP proxy will always strip the OCSP response so the OCSP check cannot work when using a proxy. I have clarified the documentation in regards to this limitation.
