### ISSUE TITLE
When a server requests a client certificate, key_size is set to "null"

### ISSUE THREAD

**Issue by MazeOfThoughts** [nabla-c0d3/sslyze#368]
In a scan using sslyze, we encountered two servers which requested TLS client certificates. That lead to cipher list entries with `"key_size": null` in the JSON output.

Ex: 
```
{
  "is_anonymous": false,
  "key_size": null,
  "openssl_name": "ECDHE-RSA-AES256-SHA",
  "post_handshake_response": null,
   "ssl_version": "TLSV1"
}
```

When we tried parsing this output, it broke on those values (that part is on us). However, it seems to us like a "null" value here is not intended or that at least some sort of warning would be appropriate.

Using sslyze 2.0.6, run `sslyze --regular --json_out file.json` against a server which will request a TLS client certificate.

**Python environment:**
 - OS: Kali Linux
 - Python version: 3.7.3rc1

**Comment by nabla-c0d3** [comment]
Fixed in v3.0.0.
