### ISSUE TITLE
location discovery: unable to find 2 plugins when ran via symlink

### ISSUE THREAD

**Issue by blshkv** [nabla-c0d3/sslyze#37]
I have installed sslyze as a system tool and created a link as below:
/usr/bin/sslyze -> /usr/lib64/sslyze/sslyze.py
It was working fine in the previous version. sslyze 0.10 gives the following error:
```
  PluginCertInfo - Import Error: [Errno 2] No such file or directory
  PluginChromeSha1Deprecation - Import Error: [Errno 2] No such file or directory

  PluginHeartbleed
  PluginCompression
  PluginSessionResumption
  PluginOpenSSLCipherSuites
  PluginSessionRenegotiation
  PluginHSTS
```

As you can see, it is unable to find first 2 plugins

**Comment by nabla-c0d3** [comment]
Thanks, will look into it

**Comment by kiwidude** [comment]
Same problem here. Fix should be fairly easy (use symlink target to locate own files). Would really appreciate a fix so the program can be installed in a maintainable way (just plastering a bunch of random files over /usr/bin may be traditional unix but hasn't been acceptable for quite some time. Thanks!

**Comment by nabla-c0d3** [comment]
Yeah it happens because there are non obvious differences in how Python import modules on Linux, OS X, Windows and Windows/py2exe builds. Getting all these scenarios to work perfectly is not trivial but I'll look into it.

**Comment by memoryoverride** [comment]
if using *nix system a simple workarround is to start sslyze using

user@host:~/bin/sslyze-master$ python ./sslyze.py example.com

**Comment by nabla-c0d3** [comment]
Feel free to re-open this if you still have issues.
