### ISSUE TITLE
IPv6 gaierror

### ISSUE THREAD

**Issue by fbexiga** [nabla-c0d3/sslyze#371]
When trying to run sslyze 2.0.6 against an IPv6 host, I get
WARNING: gaierror: -9; discarding corresponding tasks.

I managed to track down the error to here:
https://github.com/nabla-c0d3/sslyze/blob/master/sslyze/utils/ssl_connection.py#L84

where socket.socket should be called with socket.AF_INET or socket.AF_INET6 corresponding to whether the target is IPv4 or IPv6

**Comment by fbexiga** [comment]
When will the new release come out?

**Comment by nabla-c0d3** [comment]
The fix was released with v2.1.0.
