### ISSUE TITLE
Timeout on valid domain

### ISSUE THREAD

**Issue by Svjard** [nabla-c0d3/sslyze#373]
**Describe the bug**
Running a regular scan on a host which loads fine in the browser and works in other 3rd party tools results in this timeout.

sudo docker exec -it 54480f9b9b24 python -m sslyze tahoecpa.net

 AVAILABLE PLUGINS
 -----------------

  SessionRenegotiationPlugin
  HeartbleedPlugin
  HttpHeadersPlugin
  CompressionPlugin
  FallbackScsvPlugin
  SessionResumptionPlugin
  OpenSslCipherSuitesPlugin
  OpenSslCcsInjectionPlugin
  RobotPlugin
  CertificateInfoPlugin

 CHECKING HOST(S) AVAILABILITY
 -----------------------------

   tahoecpa.net:443                       => WARNING: Could not connect (timeout); discarding corresponding tasks.

 SCAN COMPLETED IN 5.17 S
 ------------------------

**To Reproduce**
1. Latest SSLyze installed
2. python -m sslyze tahoecpa.net

**Expected behavior**
Expect it to return valid results and find the host.

**Python environment (please complete the following information):**
 - OS: Ubuntu 16.04.5 LTS (Xenial Xerus)
 - Python 2.7.12

**Additional context**
I am running inside a docker container, don't believe this is an issue as many others work just fine. I tried it with an older version of SSLyze and the latest, both had the same result.

Any help is appreciated thanks!

**Comment by nabla-c0d3** [comment]
It looks like you are using an older version of SSLyze as Python 2.7 is no longer supported.
I tried just now to scan this host with the latest version of SSLyze on Python 3.7 and it worked fine.
