### ISSUE TITLE
setup.py: conditional dependencies

### ISSUE THREAD

**Issue by blshkv** [nabla-c0d3/sslyze#374]
https://github.com/nabla-c0d3/sslyze/blob/master/setup.py#L85
```dataclasses``` must be added conditionally in order to avoid problems on a system with python3.7, I believe.

Here is how it can be done:
https://hynek.me/articles/conditional-python-dependencies/

Thank you

**Comment by nabla-c0d3** [comment]
Fixed in 2.1.2.
