### ISSUE TITLE
Import and Scan From Nmap XML File

### ISSUE THREAD

**Issue by nullsession0x** [nabla-c0d3/sslyze#377]
The ability to import and scan from an nmap XML would be brilliant.

**Comment by nullsession0x** [comment]
Testssl supports import of nmap file format.
https://github.com/drwetter/testssl.sh

**Comment by nabla-c0d3** [comment]
This should be easy to do using SSLyze' s Python API and is a bit out of scope for the SSLyze CLI, which I would like to keep small and simple.
