### ISSUE TITLE
Potential False Positive

### ISSUE THREAD

**Issue by asudhak** [nabla-c0d3/sslyze#38]
In https://github.com/nabla-c0d3/sslyze/blob/master/plugins/PluginSessionRenegotiation.py, there is a potential false positive when testing Jetty Applications. When Jetty is set to reject renegotiation, it actually completes one handshake, and then closes the socket. So an error is not thrown.

You would however, get 'An established connection was aborted by the software in your host machine' when you try to renegotiate once again since the connection is closed after performing 1 handshake.

**Comment by nabla-c0d3** [comment]
Thanks - do you know of a public jetty server that I could use for a quick test ?

**Comment by asudhak** [comment]
unfortunately, no I do not have a public facing Jetty Server.

**Comment by nabla-c0d3** [comment]
Thanks but I was unable to connect to it. Let me know if it's back on and I'll do some testing

**Comment by FallenHero66** [comment]
Hello!
Sorry for responding to a very old issue.
We run into this same problem a lot with big network scans - F5 allows a certain (configurable) amount of renegotiations until it kills the connection, so this has caused some false positives for me aswell.
I have a (working) proprietary and undynamic fix which issues 11 renegotiations (F5 allows 10 by default as far as I know) and outputs the amount of successful renegotiations in the overview. However, I would like to implement a CLI option which allows you to choose the amount of renegotiations.
Do you think this is practicable?
