### ISSUE TITLE
import the result in DefectDojo

### ISSUE THREAD

**Issue by NRGLine4Sec** [nabla-c0d3/sslyze#381]
What is the better argument or the combinaison of argument to create a report file which can be imported in [DefectDojo](https://github.com/DefectDojo/django-DefectDojo).

I have create an issue in DefectDojo to add the ability to import the result of a scan with sslyze (https://github.com/DefectDojo/django-DefectDojo/issues/1140) but, maybe you can help us to add sslyze to DefectDojo.

**Comment by nabla-c0d3** [comment]
The JSON from is probably the best option for this:

`python -m sslyze --regular --json_out=report.json www.google.com`
