### ISSUE TITLE
Rate limited even with '--slow_connection'

### ISSUE THREAD

**Issue by sindarina** [nabla-c0d3/sslyze#385]
**Is your feature request related to a problem? Please describe.**
Hitting rate limits because, even with `--slow_connection`, SSLyze still fires off hundreds of connections in a few seconds. This triggers rate limits against SMTP endpoints that have no issues with normal loads, leading to failing and incomplete tests. Having to significantly increase limits just to be able to run the test after a configuration change is undesirable.

**Describe the solution you'd like**
Would love a way to specify a delay of some sort between connections; the goal is to get reliable information back, not to get it quick and dirty. Perfectly alright if that means it takes a few minutes instead of a few seconds.

**Describe alternatives you've considered**
Looked at the code to see if there was an easy way to insert a basic `time.sleep(0.25)` somewhere, but couldn't find a spot where it actually mattered. Mozilla's 'cipherscan' seems to have fallen behind a bit, and doesn't test for TLSv1.3 yet.

**Comment by marcfisher** [comment]
I am curious about this one as well, I've tried modifying it in several places to slow it down. I see you can change the thread count in the server connectivity tester. But when it comes to actually the tests execution it would be nice to spread those out possibly.

**Comment by nabla-c0d3** [comment]
Can you post (or send me) an example of a server that doesn't return valid results because of too many connections? It will help me address this.
Thanks!

**Comment by nabla-c0d3** [comment]
The next big release (WIP in https://github.com/nabla-c0d3/sslyze/tree/remove-multi-processing) will address this.

**Comment by nabla-c0d3** [comment]
Fixed in v3.0.0.
