### ISSUE TITLE
--hide_rejected_ciphers does not work with JSON or XML output

### ISSUE THREAD

**Issue by jduprat** [nabla-c0d3/sslyze#389]
**Describe the bug**
--hide_rejected_ciphers reduces what goes to stdout.
It does not reduce the output size in JSON or XML mode however, which I would have expected.

**To Reproduce**
$ sslyze --version
2.1.4
$ sslyze --sslv2 --sslv3 --tlsv1 --tlsv1_1 --tlsv1_2 --tlsv1_3 --json_out=- google.com:443
// look for non-empty rejected_cipher_list[]

**Expected behavior**
I would have expected that array to be empty

**Python environment (please complete the following information):**
 - OS: Fedor30
 - Python version: 3.7.4

**Comment by nabla-c0d3** [comment]
This is by design: unlike the CLI output, JSON and XML files are expected to be read by a program and not a human. Hence how verbose their content is shouldn't matter?
