### ISSUE TITLE
python command

### ISSUE THREAD

**Issue by dR3b** [nabla-c0d3/sslyze#39]
This is the first line in your code:
```python
#!/usr/bin/env python
```
Please note that this is not working if you have "python2" and "python3" installed. On my system "python" is a symbolic link for "python3". Change it to:
```python
#!/usr/bin/env python2
```

Thanks

**Comment by nabla-c0d3** [comment]
Hi,
On my system (OS X 10.10) I get:

    env: python2: No such file or directory

Seems like python2 is not going to work everywhere so I can't make that change.
Thanks,
