### ISSUE TITLE
JSON/XML output does not identify PFS ciphers

### ISSUE THREAD

**Issue by jduprat** [nabla-c0d3/sslyze#390]
**Describe the bug**
I would expect all TLS V1.3 ciphers (and some others) to report perfect forward security (is_anonymous is true):

   "tlsv1_3": {
                    "accepted_cipher_list": [
                        {
                            "is_anonymous": false,
                            "key_size": 256,
                            "openssl_name": "TLS_CHACHA20_POLY1305_SHA256",
                            "post_handshake_response": "",
                            "ssl_version": "TLSV1_3"
                        },
[...]

Those ciphers in fact report:  "is_anonymous": false.

**To Reproduce**
Steps to reproduce the behavior
$ sslyze --version
2.1.4
$ sslyze --sslv2 --sslv3 --tlsv1 --tlsv1_1 --tlsv1_2 --tlsv1_3 --json_out=- google.com:443

Counting the number of ciphers reporting anonymous:
$ sslyze --sslv2 --sslv3 --tlsv1 --tlsv1_1 --tlsv1_2 --tlsv1_3 --hide_rejected_ciphers --json_out=- google.com:443|grep is_anonymous|tr -d ' '  |sort|uniq -c
    461 "is_anonymous":false,
     78 "is_anonymous":true,

**Expected behavior**
The TLS V1.3 ciphers all offer PFS.

**Python environment (please complete the following information):**
 - OS: Fedora 30
 - Python version: 3.7.4

**Additional context**

**Comment by nabla-c0d3** [comment]
Hello,
is_anonymous is True for "Anonymous cipher suites" (https://security.stackexchange.com/questions/113535/what-are-the-use-cases-for-anonymous-ssl-cipher-suites), which fortunately are gone with TLS 1.3. It is unrelated to cipher suites with perfect forward secrecy.
