### ISSUE TITLE
v2.1.4 missing Windows binary

### ISSUE THREAD

**Issue by randomstability** [nabla-c0d3/sslyze#391]
Can we get a binary for this version?  We need to test for older version of TLS/SSL from Windows.

**Comment by dEajL3kA** [comment]
I second the request for new Windows binaries. Thank you!

**Comment by sergeevabc** [comment]
@nabla-c0d3, meow!

**Comment by nabla-c0d3** [comment]
I built an executable for the latest version: https://github.com/nabla-c0d3/sslyze/releases/tag/3.0.1
