### ISSUE TITLE
HSTS header not reported when it is returned only after a redirect

### ISSUE THREAD

**Issue by r0oth3x49** [nabla-c0d3/sslyze#393]
**Describe the bug**
http headers check plugin says HSTS not supported, while scanning the same web on ssllabs shows HSTS enabled. I have also tried with requests to check the headers requests also shows that HSTS is available.

**To Reproduce**
1. install the latest version of SSLyze from pip.
2. Run the following command `python3 -m sslyze --http_headers emm.epf.gov.my`
4. See the error it says not supported.

**Expected behavior**
It should also show that HSTS is supported.

**Python environment (please complete the following information):**
 - OS: Debian Kali latest
 - Python version: 3.7 (default version available on latest kali)

**Screen shots for your reference**
Locally ran the command using requests and sslyze both.
![Capture](https://user-images.githubusercontent.com/11024397/65240863-af0caa00-dafb-11e9-9948-a5305c4d3fa5.PNG)

ssllabs shows.
![Capture](https://user-images.githubusercontent.com/11024397/65240938-d3688680-dafb-11e9-8d1e-0b6494d81f60.PNG)

**Edit**
The reason could be redirections in http request.

**Comment by nabla-c0d3** [comment]
Fix released in v3.0.2.
