### ISSUE TITLE
Python output regarding Symantec certificate

### ISSUE THREAD

**Issue by dhaug-op** [nabla-c0d3/sslyze#406]
**Describe the bug**
The python output about Symantec deprecation does not work correctly.

**To Reproduce**
review https://github.com/nabla-c0d3/sslyze/blob/196839519229a011a61718cc0eb3dd02a4d16572/sslyze/plugins/certificate_info_plugin.py#L462-L466 in combination with https://github.com/nabla-c0d3/sslyze/blob/196839519229a011a61718cc0eb3dd02a4d16572/sslyze/plugins/certificate_info_plugin.py#L303-L306, where it is documented, that ``verified_chain_has_legacy_symantec_anchor`` is a boolean.

**Expected behavior**
The Warning string should be built correctly.

**Additional context**
* https://github.com/nabla-c0d3/sslyze/pull/392 fixes a bug in the current SSLyze 2.1.4, causing the python output to wrongly report a Symentec detection most of the time (when ``verified_chain_has_legacy_symantec_anchor`` is ``False``)
* in https://github.com/nabla-c0d3/sslyze/blob/196839519229a011a61718cc0eb3dd02a4d16572/sslyze/plugins/certificate_info_plugin.py#L1019-L1021 the detailed ENUM information is forgotten and only the boolean information passed to the ``CertificateInfoScanResult`` object.
* Handling might be reworked with https://github.com/nabla-c0d3/sslyze/issues/397

If somebody (@nabla-c0d3) can give a precise decision how to fix this (have a additional field in the ``CertificateInfoScanResult`` object with the detailed ENUM information?), I would be happy to prepare a PR.

**Comment by nabla-c0d3** [comment]
Thanks!

**Comment by dhaug-op** [comment]
I'm sorry, maybe my description was not precise, but your fix doesn't fix the issue I see: the test for building the date inside the Warning string is ``self.verified_chain_has_legacy_symantec_anchor == SymantecDistrustTimelineEnum.MARCH_2018``, but ``self.verified_chain_has_legacy_symantec_anchor`` is a Boolean and will never be equal to ``SymantecDistrustTimelineEnum.MARCH_2018``. The detailed information, when the Certificate was distrusted is not available at this point, as it is forgotten in line https://github.com/nabla-c0d3/sslyze/blob/923f76889b31f86d3d8c368eb8f5dad46095bd6c/sslyze/plugins/certificate_info_plugin.py#L1025.

**Comment by nabla-c0d3** [comment]
Fixed in v3.0.0.
