### ISSUE TITLE
Add support for Python 3.8

### ISSUE THREAD

**Issue by jamincollins** [nabla-c0d3/sslyze#408]
**Describe the bug**
pip3 install sslyze fails

**To Reproduce**
$ pip install sslyze
Collecting sslyze
  Downloading https://files.pythonhosted.org/packages/00/fb/56ccb9c9ab28027f9cedc5b80f3a66a42b73e1310c42eae15da01418c1de/sslyze-2.1.4.tar.gz (1.1MB)
     |████████████████████████████████| 1.1MB 2.4MB/s 
ERROR: Could not find a version that satisfies the requirement nassl<2.3.0,>=2.2.0 (from sslyze) (from versions: 0.13.4.win32, 0.13.1, 0.13.2, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.14.0, 0.14.1, 0.14.2, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.17.0, 1.0.1, 1.0.2, 1.0.3)
ERROR: No matching distribution found for nassl<2.3.0,>=2.2.0 (from sslyze)

**Expected behavior**
A working sslyze installation

**Python environment (please complete the following information):**
 - OS: Arch Linux
 - Python version: 3.8

Similar previous report #366, but closed because of Cygwin

**Comment by nabla-c0d3** [comment]
Fixed in v3.0.0.
