### ISSUE TITLE
 cannot import name 'CouldNotBuildVerifiedChain' from 'nassl.ssl_client'

### ISSUE THREAD

**Issue by sonawanesarvesh** [nabla-c0d3/sslyze#411]
Hi 
I have downloaded the code on my machine and trying to run api_sample.py
so i am getting following error 

ImportError: cannot import name 'CouldNotBuildVerifiedChain' from 'nassl.ssl_client' (C:\Program Files\Python37\lib\site-packages\nassl-2.1.2-py3.7-win-amd64.egg\nassl\ssl_client.py)

**Comment by anivedh555** [comment]
/usr/lib/python3/dist-packages/sslyze/plugins/certificate_info_plugin.py
Went here and commented out line number 22  i.e "from nassl.ssl_client import ClientCertificateRequested, CouldNotBuildVerifiedChain" )
Then went to "/usr/lib/python3/dist-packages/sslyze/plugins/http_headers_plugin.py" 
and commented out line number 8 i.e "from nassl.ssl_client import CouldNotBuildVerifiedChain" 
And it started working for me :)
