### ISSUE TITLE
Reference to invalid nassl module

### ISSUE THREAD

**Issue by duckduckmuse** [nabla-c0d3/sslyze#417]
References 'nassl.temp_key_info' module which does not exist.

1. Install SSLyze using git. Latest commit is adb2e70.
2. Run the following command: `python sslyze www.google.com`
3. See error: "ModuleNotFoundError: No module named 'nassl.temp_key_info'"

 - OS: RHEL 7.7
 - Python version: 3.6

**Comment by scovetta** [comment]
I was able to get something *sort of* working by replacing openssl_cipher_suites_plugin.py with [this version](https://raw.githubusercontent.com/FWinterborn/sslyze/5ca11bf6f5dabfd4395830059b7cd02389a09b78/sslyze/plugins/openssl_cipher_suites_plugin.py) from @FWinterborn's fork, and commenting out line 18 in json_output.py. 

Beware though, you'll be creating a Frankenversion that may be broken in other ways, so YMMV.

**Comment by nabla-c0d3** [comment]
Master should be working now - make sure to update to nassl 3.0.0. 

The Python API has changed drastically (for the better) and is still not final, but very close to it.
