### ISSUE TITLE
Doesn't back off when STARTTLS isn't supported?

### ISSUE THREAD

**Issue by sindarina** [nabla-c0d3/sslyze#42]
I just ran into an odd case while testing (--starttls=smtp) a Mimecast SMTP server that is triggering SSL errors for us; sslyze doesn't back off when it encounters 'StartTLSError - SMTP STARTTLS not supported'.

I would expect that it stops on first occurence, whenever that occurs, instead of running the full set of tests on a target that will not yield meaningful results anyway? Should it not stop the moment there is no 'STARTTLS' seen in the server response?

**Comment by nabla-c0d3** [comment]
Hi,
Is the server externally available so I can do my own testing ? If that's the case can you email it to me? Otherwise I can create a test server myself but it will take more time.
Thanks

**Comment by nabla-c0d3** [comment]
I just checked and there is some logic in ServersConnectivityTester.py to stop all scans if the server doesn't support starttls so I can't reproduce this.
