### ISSUE TITLE
Error when installing via pip.

### ISSUE THREAD

**Issue by lanmaster53** [nabla-c0d3/sslyze#423]
**Describe the bug**
Attempting to install SSLyze via pip as recommended by the docs results in the following error:
```
Collecting sslyze
  Downloading sslyze-3.0.0.tar.gz (1.0 MB)
ERROR: Could not find a version that satisfies the requirement nassl<3.2.0,>=3.0.0 (from sslyze) (from versions: 0.13.4.win32, 0.13.1, 0.13.2, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.14.0, 0.14.1, 0.14.2, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.17.0, 1.0.1, 1.0.2, 1.0.3)
ERROR: No matching distribution found for nassl<3.2.0,>=3.0.0 (from sslyze)
```

**To Reproduce**
1. Install SSLyze using 'pip.
2. See error.

**Expected behavior**
A successful compilation/installation of SSLyze and its dependencies.

**Python environment (please complete the following information):**
 - OS: Alpine
 - Python version: 3.7

**Additional context**
None.

**Comment by nabla-c0d3** [comment]
Are you able to install the previous version v2.1.4?

**Comment by lanmaster53** [comment]
```
Collecting sslyze==2.1.4
  Downloading sslyze-2.1.4.tar.gz (1.1 MB)
ERROR: Could not find a version that satisfies the requirement nassl<2.3.0,>=2.2.0 (from sslyze==2.1.4) (from versions: 0.13.4.win32, 0.13.1, 0.13.2, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.14.0, 0.14.1, 0.14.2, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.17.0, 1.0.1, 1.0.2, 1.0.3)
ERROR: No matching distribution found for nassl<2.3.0,>=2.2.0 (from sslyze==2.1.4)
ERROR: Service 'sslyze' failed to build: The command '/bin/sh -c apk update &&    pip install --no-cache-dir sslyze==2.1.4' returned a non-zero code: 1
```

**Comment by lanmaster53** [comment]
The following command fixes v2.1.4, but 3.0.0 still throws the same error. Looks to be a glibc vs. musl issue. https://github.com/pypa/pip/issues/3969 

```
echo "manylinux1_compatible = True" > /usr/local/lib/python3.7/site-packages/_manylinux.py
```

Not sure why the bypass doesn't work for v3.0.0. Any ideas?

**Comment by lanmaster53** [comment]
Even though 2.1.4 installed, trying to run it failed with the above modification. Looks like I need a different flavor of linux.

**Comment by momcilo78** [comment]
Same issue, with ubuntu 18.04 on raspberry pi 3B+

**Comment by nabla-c0d3** [comment]
Any Linux this is not supported by manylinux2010 (https://github.com/pypa/manylinux) is not supported by SSLyze 

Also ARM is not supported either.
