### ISSUE TITLE
Versioned Docker Image Tags

### ISSUE THREAD

**Issue by J12934** [nabla-c0d3/sslyze#427]
**Is your feature request related to a problem? Please describe.**

The current docker image is only available under the "latest" tag.
The only way to choose the version of sslyze when using docker is by using the digest / image hash.

The image is also nearly always exactly *one* version behind the latest release, as the docker image build pulls in the latest release from pip. The pip release seems slower slower then the build on docker hub so its always one version behind.😀

E.g:

```bash
docker pull nablac0d3/sslyze:latest
docker run nablac0d3/sslyze:latest --version
# Will print 3.0.0, should be 3.0.1 at the time of writing
```

**Describe the solution you'd like**

The image should be tagged using the release versions: e.g. `nablac0d3/sslyze:v3.0.1`

**Describe alternatives you've considered**

Build docker image locally and push to separate image registry.

Use digest e.g. to pin to a specific version e.g. `nablac0d3/sslyze@sha256:c5bc176afe03accaaa0f2a13baed72996d2edcc58ce46dc191e10ccb03f614a4` (Will still be at least one version behind)

**Additional context**

This will likely require the image to be restructured to install sslyze from source instead of installing it via pip.

Would be happy to work on it, and send in a PR to change the dockerfile.

**Comment by nabla-c0d3** [comment]
Hello,
I am not very familiar with Docker but like you said, it is always pulling the latest version from pip. Hence I am not sure why it would be one version behind? I tried just now and it did pull the latest version:

```
docker pull nablac0d3/sslyze:latest
docker run nablac0d3/sslyze:latest --version
3.0.3
# This is the latest version
```

**Comment by nabla-c0d3** [comment]
As for tags for the Docker image, unfortunately I won't have time to support that, as it would add another step to the release process. But I do want to confirm that the Docker image always pull the latest release.

**Comment by J12934** [comment]
> As for tags for the Docker image, unfortunately I won't have time to support that, as it would add another step to the release process. But I do want to confirm that the Docker image always pull the latest release.

Okay that's unfortunate for me, but I can understand why 👍


> Hello,
> I am not very familiar with Docker but like you said, it is always pulling the latest version from pip. Hence I am not sure why it would be one version behind? I tried just now and it did pull the latest version:
> 
> ```
> docker pull nablac0d3/sslyze:latest
> docker run nablac0d3/sslyze:latest --version
> 3.0.3
> # This is the latest version
> ```

This happens as the docker build and the pip release happen at the same time. The docker build appears to be faster then the pip release, so the latest pip release will still be the previous one.

Currently this is up to date, as the docker build get's triggered for every commit on the master branch. So the 3.0.3 image didn't get build directly with the release, but for the latest commit, as the 3.0.3 pip was already published then.

**Comment by J12934** [comment]
@nabla-c0d3 this is currently again the case.

```bash
docker pull nablac0d3/sslyze:latest
docker run nablac0d3/sslyze:latest --version
# Will currently still print 3.0.3 until the next release or commit pushed to master.
```

**Comment by polarathene** [comment]
> But I do want to confirm that the Docker image always pull the latest release.

Generally `latest` is only useful for testing, you can't easily pull/reference a specific version and if you already have `latest` IIRC then a pull may not retrieve any updates, requiring the image to be removed and pulled again. At least I'm pretty sure I've experienced that issue in the past with other images and you'd find many articles online warning against the reliance of a `latest` tag for similar reasons.

Not having familiarity with Docker or time to allocate to versioned tags is understandable, that's something someone else might be able to help contribute.
