### ISSUE TITLE
change --regular to default

### ISSUE THREAD

**Issue by blshkv** [nabla-c0d3/sslyze#440]
Hello,

I don't run the tool every day and getting annoyed everytime I hit this issue

First, it would be good to run it using a simple command  "sslyze https://www.xyz.domain"
Instead, I need to remember an "unnatural" "sslyze --regular www.xyz.domain:443"

Could you make --regular a default behaviour and accept https://xyz as a default for xyz:443?

**Comment by nabla-c0d3** [comment]
Yeah agreed about `--regular`. For the domain you can just do  `sslyze --regular www.domain.com` - no need for 443 or https.

**Comment by blshkv** [comment]
well, the problem with "https" is that I'm getting it by copy-pasting from the browser sometimes.
Using hotkeys: ctrl-l (location bar focus) -> ctrl-c (copy) -> switch to console -> ctrl-v (paste)
At the end, the cursor would be at the end of cli, so I need to go back, remove "https://".

I'm sure it could you use some library which would "understand" different user's input formats.

**Comment by nabla-c0d3** [comment]
Released in v3.0.7.

**Comment by blshkv** [comment]
Great, thanks. I'll file a separate issue for the second suggestion

**Comment by nabla-c0d3** [comment]
If you're talking about HTTP URLs, I don't think I will support it 😅
