### ISSUE TITLE
user friendly / readable / pci dss output

### ISSUE THREAD

**Issue by blshkv** [nabla-c0d3/sslyze#441]
Hello,

Thanks a lot for a great tool, the latest version is really fast and I love it. However, I'm not able to use sslyze in real life because it's still hard to read the output and hard to understand which ciphers need to be disabled. So I end up using testssl.sh because its output is close to sslabs.

I know it has been discussed here:
https://github.com/nabla-c0d3/sslyze/issues/111 (fixed)
https://github.com/nabla-c0d3/sslyze/issues/317 (open)

but I don't feel like it is really fixed. I was also using https://github.com/Archstacker/sslyze-html to convert xml into readable html as a workaround but "--xml_out" option is gone, and this is an additional step anyway

Could you please consider exporting xsl from sslyze-html and improving it or come up with a simpler readable output?

**Comment by nabla-c0d3** [comment]
An easier-to-read output has been implemented as part of https://github.com/nabla-c0d3/sslyze/issues/453.

**Comment by blshkv** [comment]
finally, after so many years! Thanks!
