### ISSUE TITLE
Add plugin for scanning supported EC curves 

### ISSUE THREAD

**Issue by nabla-c0d3** [nabla-c0d3/sslyze#447]
Based on #410

**Comment by nabla-c0d3** [comment]
@fabian-hk the feature is now ready to go. Thanks again for your contributions!

**Comment by fabian-hk** [comment]
@nabla-c0d3 thank you for integrating it into sslyze!

**Comment by nabla-c0d3** [comment]
Released as part of [v3.1.0](https://github.com/nabla-c0d3/sslyze/releases/tag/3.1.0) .
