### ISSUE TITLE
www reneg issue

### ISSUE THREAD

**Issue by Xurcr0h** [nabla-c0d3/sslyze#45]
Hey :)
I wondering, why there is a different between

python sslyze.py --reneg www.mint.com
and
python sslyze.py --reneg mint.com

If i skip the www, everything is okay. But if I try it with www. it tells me that secure reneg is vuln.
Same with www.airbnb.com

Why is it acting different?

**Comment by nabla-c0d3** [comment]
Hi,
These two domains point to different hosts and most likely have a different SSL configuration:

    WWW.MINT.COM:443 - 172.230.104.222:443
    MINT.COM:443 - 38.81.36.15:443
