### ISSUE TITLE
Mozilla Profile's TLS/SSL recommendation 

### ISSUE THREAD

**Issue by unl1k3ly** [nabla-c0d3/sslyze#453]
Hi,

Thank you so much to this lib. It's beyond great !

Would you be considering implement https://github.com/danielfett/tlsprofiler/ or from it's own https://ssl-config.mozilla.org/guidelines/latest.json in a plugin ?

Cheers

**Comment by nabla-c0d3** [comment]
Released in [v5.0.0](https://github.com/nabla-c0d3/sslyze/releases/tag/5.0.0).
