### ISSUE TITLE
Support for cryptography 3.X

### ISSUE THREAD

**Issue by weddige** [nabla-c0d3/sslyze#455]
Are there any plans on supporting cryptography 3.1?

I would love to use the support for PKCS7/PKCS12, that was added in 3.0 and 3.1 in a project that depends (for an independent feature) also on sslyze. Therefore it would be great therefore it would be great to be able to use cryptography > 3.0 with sslyze.

**Comment by nabla-c0d3** [comment]
Fix released as part of [v3.1.0](https://github.com/nabla-c0d3/sslyze/releases/tag/3.1.0) .
