### ISSUE TITLE
openssl server side option "SSL_OP_PRIORITIZE_CHACHA" is not detected / handled correctly

### ISSUE THREAD

**Issue by bratkartoffel** [nabla-c0d3/sslyze#456]
**Describe the bug**
On servers with openssl option "SSL_OP_PRIORITIZE_CHACHA" enabled results in "The server has no preferred cipher suite."

**To Reproduce**
* Start a TLSv1.2 or TLSv1.3 server with this option enabled (you may also use current proftpd (1.3.7a-r0) on alpine edge)
* With cipher string `EECDH+AES128:EECDH+AES256:CHACHA20:!aPSK:!PSK:!DHE` the no preferred-ciphersuite message is shown
* With cipher string `EECDH+AES128:EECDH+AES256:!aPSK:!PSK:!DHE` the no preferred-ciphersuite message is not shown

**Expected behavior**
Sslyze should also honor this setting and not "warn" about server not having a suite order preference. This setting could be determined by sslyze when execution two handshakes, one with ChaCha20 and one without.
If the server prefers ChaCha20, then this option is set and a corresponding mesasge should be shown.

**Python environment (please complete the following information):**
 - OS: Windows 10
 - Python version: used the distributed .exe 3.0.8

**Additional context**
Relates to https://github.com/proftpd/proftpd/issues/1076

**Comment by nabla-c0d3** [comment]
Thanks for the detailed report. I've removed the "preferred cipher suite" functionality for now (in https://github.com/nabla-c0d3/sslyze/commit/efbd4766375748f06681e7ddbdbb5eea46ec1730); it had too many problems.

I will fix this bug by building a full-fledged cipher suite order detection check, which has been a common request for the past few years. The main ticket for this is https://github.com/nabla-c0d3/sslyze/issues/338. I will close the ticket here as a "duplicate", and I will take this SSL_OP_PRIORITIZE_CHACHA option into account when building the new check.
