### ISSUE TITLE
Windows Server 2019 missing cipher suites

### ISSUE THREAD

**Issue by paul179** [nabla-c0d3/sslyze#463]
Hello, 

I use the tool SSLynz to query a Windows Server 2019 via port 3389 and get the following cipher suites displayed for the TLS 1.2 protocol.

* TLS 1.2 Cipher suites:
    Attempted to connect using 158 cipher suites.

    The server accepted the following 6 cipher suites:
       TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384             256       ECDH: secp384r1 (384 bits)
       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384             256       ECDH: secp384r1 (384 bits)
       TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256             128       ECDH: prime256v1 (256 bits)
       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256             128       ECDH: prime256v1 (256 bits)
       TLS_DHE_RSA_WITH_AES_256_GCM_SHA384               256       DH (2048 bits)
       TLS_DHE_RSA_WITH_AES_128_GCM_SHA256               128       DH (2048 bits)

And under Windows Server 2019 with powershell these cipher suites are displayed.

PS C:\Windows\system32> Get-TlsCipherSuite | Format-Table Name

Name                           
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384  
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256  
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384    
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256    
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384  
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256  

I missing all cipher suites with TLS_ECDHE_ECDSA*

TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256

Microsoft says it is supported.
https://docs.microsoft.com/en-us/windows/win32/secauthn/tls-cipher-suites-in-windows-10-v1809

Can the missing cipher suites be displayed?

Sorry my english is not good.

Thanks Paul

**Comment by nabla-c0d3** [comment]
It looks like a configuration issue on your side (maybe a missing EC certificate?). SSLyze is definitely able to detect ECDSA cipher suites and I added a test for this just to be sure.
