### ISSUE TITLE
Python 3.10 not supported 

### ISSUE THREAD

**Issue by teodem** [nabla-c0d3/sslyze#464]
Hi, 

**Bug:**
i'm integrating Sslyze in my Docker Image, but as i update the image today, Sslyze stopped to work: 

`ERROR: Could not find a version that satisfies the requirement nassl<3.1.0,>=3.0.0 (from sslyze) (from versions: 0.13.4.win32, 0.13.1, 0.13.2, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.14.0, 0.14.1, 0.14.2, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.17.0, 1.0.1, 1.0.2, 1.0.3)
ERROR: No matching distribution found for nassl<3.1.0,>=3.0.0 (from sslyze)`

**To Reproduce**
I'm working with python:slim-buster (uses python3.10)
1. Install SSLyze using: `RUN pip install --upgrade setuptools
RUN pip install --upgrade sslyze`
2. See error

**Expected behavior**
Sslyze is supposed to be installed. 

**Python environment (please complete the following information):**
 - OS: Linux -x86 [here the image](https://github.com/docker-library/python/blob/3807214e06b217eede0651863ba2dceb06534fb7/3.10-rc/buster/slim/Dockerfile)
 - Python version: 3.10

**Additional context**
As i said, i'm adding the tool to my personal Docker File. Was working before, but as soon as the base image (Debias based) was updated with Python3.10, Sslyze was not working anymore.

**Comment by nabla-c0d3** [comment]
Hello,
Unfortunately Python 3.10 has not been released yet. It will be released in October 2021 (https://www.python.org/dev/peps/pep-0619/#schedule), which is when I will add support for it. 
I don't want to add support for an alpha release of Python because it's too tricky and time-consuming.

**Comment by jduprat** [comment]
With Python 3.10 shipping and released with Linux distros (e.g. Fedora 35) it might be time to revisit this issue.

**Comment by PhilippSelenium** [comment]
@nabla-c0d3 Are you accepting PRs?

**Comment by nabla-c0d3** [comment]
@PhilippSelenium Definitely! The work for Python 3.10 support is happening there - the last remaining step is for the build to pass: https://github.com/nabla-c0d3/nassl/tree/support-for-python-3-10

**Comment by PhilippSelenium** [comment]
Thanks, I only looked at the PRs not the branches.

**Comment by nabla-c0d3** [comment]
Python 3.10 support has been added to [v5.0.2](https://github.com/nabla-c0d3/sslyze/releases/tag/5.0.2).
