### ISSUE TITLE
Why is python 3.6 not supported anymore

### ISSUE THREAD

**Issue by PhilippSelenium** [nabla-c0d3/sslyze#465]
Why was the support for python 3.6 dropped https://github.com/nabla-c0d3/sslyze/commit/f0a6eb125a551cfbdb4311c7218cf3ed012311dd even though its end of life is in December 2021?

**Comment by nabla-c0d3** [comment]
Every Python version that's supported adds 4 binary wheels that I have to build on every release of https://github.com/nabla-c0d3/nassl (win64, macOS, linux32, linux64). Unfortunately I don't really have time for this so I am keeping the number of Python versions supported to a minimum.

**Comment by PhilippSelenium** [comment]
Okay. Thanks. @nabla-c0d3 So github provides no way of building these wheels automatically?

**Comment by nabla-c0d3** [comment]
As far as I know there isn't a "one click" solution, and the windows and macos builds require a windows and macos computer.
