### ISSUE TITLE
Support cryptography 3.3.1

### ISSUE THREAD

**Issue by PhilippSelenium** [nabla-c0d3/sslyze#467]

**Comment by nabla-c0d3** [comment]
The fix was released as part of [v4.0.0](https://github.com/nabla-c0d3/sslyze/releases/tag/4.0.0).

**Comment by seanmarpo** [comment]
@nabla-c0d3, looks like the Pipfile was updated, but the `setup.py` did not get the change. Check this line: https://github.com/nabla-c0d3/sslyze/blob/release/setup.py#L94

Thanks!

**Comment by nabla-c0d3** [comment]
@seanmarpo Good catch - I fixed this in [v4.0.1](https://github.com/nabla-c0d3/sslyze/releases/tag/4.0.1).
