### ISSUE TITLE
Missing certificates if chain is invalid

### ISSUE THREAD

**Issue by warburtr0n** [nabla-c0d3/sslyze#469]
**Describe the bug**
If the certificate chain order is invalid (certs sent in wrong order or contains an anchor) then only the leaf certificate is displayed. No information is available for other certificates. Unsure if this is by design but it seems as though the information should be available.

**To Reproduce**
1. Install SSLyze using pip
2. Run sslyze www.f5.com --certinfo
3. Console (and JSON) output contain only information on certificate_0 (the leaf cert)

**Expected behavior**
SSLyze would display details of certificate_1 and certificate_2

**Python environment (please complete the following information):**
 - OS: Windows 10 
 - Python 3.8.6

**Additional context**
The leaf cert is valid and SSLyze can display the [incorrectly ordered] chain.

**Comment by nabla-c0d3** [comment]
Hello, I am unable to reproduce this. The CLI output is valid:


```
$ python -m sslyze --certinfo www.f5.com

[...]

Certificate #0 - Trust
       Hostname Validation:               OK - Certificate matches server hostname
       Android CA Store (9.0.0_r9):       OK - Certificate is trusted
       Apple CA Store (iOS 13, iPadOS 13, macOS 10.15, watchOS 6, and tvOS 13):OK - Certificate is trusted
       Java CA Store (jdk-13.0.2):        OK - Certificate is trusted
       Mozilla CA Store (2020-09-17):     OK - Certificate is trusted, Extended Validation
       Windows CA Store (2020-10-01):     OK - Certificate is trusted
       Symantec 2018 Deprecation:         OK - Not a Symantec-issued certificate
       Received Chain:                    author-www.f5.com --> Entrust Root Certification Authority - G2 --> Entrust Certification Authority - L1M
       Verified Chain:                    author-www.f5.com --> Entrust Certification Authority - L1M --> Entrust Root Certification Authority - G2
       Received Chain Contains Anchor:    WARNING - Received certificate chain contains the anchor certificate
       Received Chain Order:              FAILED - Certificate chain out of order!
```

Only the leaf certificate is displayed, by design. 

In the JSON output I do see all the three certificates in the `received_certificate_chain` field.

Feel free to re-open this issue if I missed something. Thanks
