### ISSUE TITLE
[Question] Can sslyze be used to check for compliance?

### ISSUE THREAD

**Issue by MartinThoma** [nabla-c0d3/sslyze#479]
There are a couple of standards which are interesting to be compliant with:

NIST:

* Guideline for Using Cryptographic Standards in the Federal Government: Cryptographic Mechanisms ([NIST 800-175B](https://csrc.nist.gov/publications/detail/sp/800-175b/rev-1/final)) 
* Recommendations for Key Management (NIST 800-57: [Part 1](https://csrc.nist.gov/publications/detail/sp/800-57-part-1/rev-5/final), [Part 2](https://csrc.nist.gov/publications/detail/sp/800-57-part-2/rev-1/final), [Part 3](https://csrc.nist.gov/publications/detail/sp/800-57-part-3/rev-1/final))
* Transitions: Recommendation for Transitioning the use of Cryptographic Algorithms and Key Lengths ([NIST 800-131A](https://www.nist.gov/publications/transitioning-use-cryptographic-algorithms-and-key-lengths))
* Guidelines for the Selection, Configuration, and Use of Transport Layer Security (TLS) Implementations ([NIST 800-52](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-52r2.pdf))

FIPS:

* Security Requirements for Cryptographic Modules ([FIPS 140-2](https://en.wikipedia.org/wiki/FIPS_140-2))

and potentially many more?
 
Is it possible to use sslyze to audit for compliance issues against those standards?

**Comment by MartinThoma** [comment]
Maybe this could be done with "profiles", similar to the suggestions here: https://github.com/drwetter/testssl.sh/issues/1085

A profile could look like this:

```
{
    "cipher_suite": {
        "protocol": {
            "accept": [
                {
                    "name": "TLS",
                    "version": ">=1.2"
                }
            ],
            "reject": [
                {
                    "name": "SSL",
                    "version": ">=0.0.0"
                }
            ]
        },
        "key_exchange": {
            "accept": [
                "RSA",
                "DH"
            ],
            "reject": []
        },
        "authentication": {
            "accept": [
                "RSA",
                "DSA"
            ],
            "reject": []
        },
        "encryption": {
            "accept": [
                "DES",
                "3DES",
                "AES",
                "ChaCha20"
            ],
            "reject": [
                "None"
            ]
        },
        "hash_function": {
            "accept": [
                "SHA"
            ],
            "reject": [
                "MD5"
            ]
        }
    },
    "tls_extensions": {
        "madatory": [
            "supports_secure_renegotiation",
            "server_name_indication",
            "extended_master_secret",
            "ocsp"
        ],
        "forbidden": []
    }
}
```

**Comment by MartinThoma** [comment]
I'd especially be interested to have this running regularly. I imagine it like this:

1. A just is ran every 24h. 
2. This job first installs / upgrades sslyze
3. Then the job checks a website for potential issues in the TLS configuration. If something is found, a trigger is executed (e.g. a slack channel is notified). Otherwise, it just finishes with exit code 0.

Does anybody do that?

**Comment by nabla-c0d3** [comment]
I know a few organizations who do this. It can be implemented using SSLyze's Python API: https://nabla-c0d3.github.io/sslyze/documentation/
