### ISSUE TITLE
Cannot install on Red Hat Enterprise Linux 7.9

### ISSUE THREAD

**Issue by na21** [nabla-c0d3/sslyze#489]
**Describe the bug**
Can't install or upgrade sslyze on machine to any version above 2.1.4.

**To Reproduce**
1. Install SSLyze using pip
2. Run the following comman: pip install sslyze or pip install --upgrade sslyze==4.0.2 
4. See error: Could not find a version that satisfies the requirement nassl<5.0.0,>=4.0.0

**Expected behavior**
Successful installation of sslyze 4.0.2

**Python environment (please complete the following information):**
 - OS: Linux (Red Hat Enterprise Linux version 7.9)
 - Python version: 3.7.1

**Comment by nabla-c0d3** [comment]
Hello, can you run the following command and post the output:
```
$ uname -a  
```

**Comment by na21** [comment]
> Hello, can you run the following command and post the output:
> 
> ```
> $ uname -a  
> ```

Linux hostname 3.10.0-1160.11.1.e17.x86_64 #1 SMP Mon Nov 30 13:05:31 EST 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ThoughtHopper** [comment]
I have the same issue.... 

I'm trying to install sslyze inside a docker image and I'm running into the same problem.
This used to work before (for version 2.1.4)

My docker file does a step like this:

RUN apt install -y python3-pip &&\
    pip3 install --upgrade setuptools &&\
    pip3 install sslyze

Inside the docker image
**root@8f929ef495aa:/# uname -a
Linux 8f929ef495aa 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 GNU/Linux**

When I run:
_pip3 install nassl_ 
it installs version 2.2.0

So it's no surprise that pip3 install sslyze complains about this error.

**Comment by wondex** [comment]
Hi na21 and ThoughtHopper,

I think this is because of you (older) Python version, which version of Python do you use?
Can you try updating this first and try again.

**Comment by morrisco** [comment]
I have python 3.9.1 installed on macOS 11.2.1 and am running into the exact same issue. Is there a known fix for this issue?

**Comment by nabla-c0d3** [comment]
I've uploaded manylinux2014 wheels for nassl which should solve most installation issues with Linux. If you are still getting this error, then your OS/platform is probably not supported (for example, Apple Silicon is not supported natively - https://github.com/nabla-c0d3/sslyze/issues/507).
