### ISSUE TITLE
Allow to hide all outputs

### ISSUE THREAD

**Issue by cjeanneret** [nabla-c0d3/sslyze#49]
Hello!

I'm currently wanting to use sslyze in a script, running as a cron job. I added the xml_output option, but I still get a lot of output from sslyze — is it possible to get some quiet run? I didn't see anything in the options, and the code doesn't seem to propose this kind of feature (a lot of "print" without any condition).

Would be great if this could be done :).

Cheers,

C.

**Comment by tuftedocelot** [comment]
https://github.com/nabla-c0d3/sslyze/issues/25

**Comment by cjeanneret** [comment]
darn… "This doesn't seem to be really needed" ­— wrong. Especially when we can drop an XML file: what's the use of the output?
Using redirections might be possible, but in my case isn't an option (call with perl "system" command, no output management at all)…
A --quiet won't explode user's capabilities to understand how to run the script :/

Would @nabla-c0d3 at least consider a pull-request for that?

**Comment by nabla-c0d3** [comment]
Yes I will and it sounds like this would actually be useful. Everything is printed at the end of sslyze.py so it shouldn't be too much work.
I always ask for a good reason before adding a new command line option otherwise we would probably have 60+ options by now.
Thanks,

**Comment by cjeanneret** [comment]
And here you are :). Pretty easy indeed. Lemme know if this suites your coding style.
