### ISSUE TITLE
Stable json output

### ISSUE THREAD

**Issue by maage** [nabla-c0d3/sslyze#491]
**Is your feature request related to a problem? Please describe.**

It seems json output is not stable. If I run it repeatedly, entities change order.

scan_commands
elliptic_curves.rejected_curves order
openssl_name seems to change from DHE to EDH variant.

Obviously ephemeral_key public_bytes,x,y and total_scan_time are going change, but that is not a problem.

**Describe the solution you'd like**

Run sslyze with some args, wait couple of minutes, run it again with same args as before. Compare json outputs with diff or similar tool. And notice there is only differencies where values changed.

**Describe alternatives you've considered**

This helps to fix scan_commands:
```
diff --git a/sslyze/json.py b/sslyze/json.py
index 79cea7b..06244a2 100644
--- a/sslyze/json.py
+++ b/sslyze/json.py
@@ -32,7 +32,7 @@ def _enum_to_json(obj: Enum) -> JsonType:
 
 
 def _set_to_json(obj: set) -> JsonType:
-    return list(obj)
+    return sorted(list(obj))
 
 
 def _path_to_json(obj: Path) -> JsonType:
```
But elliptic_curves.rejected_curves order seems to be random.

**Comment by nabla-c0d3** [comment]
Fix released as part of [v4.0.3](https://github.com/nabla-c0d3/sslyze/releases/tag/4.0.3).
