### ISSUE TITLE
OCSP validation fails

### ISSUE THREAD

**Issue by wondex** [nabla-c0d3/sslyze#502]
**Describe the bug**
OCSP validation fails on internal hosts by using sslyze, while the OCSP responder is reachable.
Getting the following JSON output after a regular scan using sslyze:
```
         "scan_commands_results": {
                "certificate_info": {
                    "certificate_deployments": [
                        {
                            "leaf_certificate_has_must_staple_extension": false,
                            "leaf_certificate_is_ev": false,
                            "leaf_certificate_signed_certificate_timestamps_count": 0,
                            "leaf_certificate_subject_matches_hostname": true,
                            "ocsp_response": null,
                            "ocsp_response_is_trusted": null,
```
							
But when verifying with openssl using:
`/bin/openssl ocsp -issuer <(echo -e "-----BEGIN CERTIFICATE-----\n<issuer>\n-----END CERTIFICATE-----\n") -cert <(echo -e "-----BEGIN CERTIFICATE-----\n<cert>\n-----END CERTIFICATE-----\n") -timeout 1 -url ${ocsp_responder}`

I get the following output:
```
Response verify OK
/dev/fd/62: good
        This Update: Feb 18 08:55:38 2021 GMT
```

To Reproduce
Install SSLyze using: pip
Run the following command: /opt/rh/rh-python38/root/usr/bin/python3.8 -m sslyze --regular

Expected behavior
Successful ocsp check

Python environment (please complete the following information):
OS: Red Hat Enterprise Linux Server release 7.9 (Maipo)
Python version: 3.8
SSLyzeL: 4.0.3

**Comment by nabla-c0d3** [comment]
The ocsp_response returned by SSLyze is the one the server returned via OCSP Stapling. Looks like in this case the server didn't return any response that way (ie. it doesn't use stapling)?
