### ISSUE TITLE
Deprecated public-key-pins headers

### ISSUE THREAD

**Issue by binarymist** [nabla-c0d3/sslyze#506]
This may just be informational, but public key pins header and public key pins report only header are deprecated:

* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Public-Key-Pins#:~:text=The%20HTTP%20Public%2DKey%2DPins,and%20Expect%2DCT%20header%20instead.
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Public-Key-Pins-Report-Only

Do they need to still be checked in sslyze?

**Comment by nabla-c0d3** [comment]
Agreed - HPKP will be removed in the next major version.

**Comment by nabla-c0d3** [comment]
Fixed in [v5.0.0](https://github.com/nabla-c0d3/sslyze/releases/tag/5.0.0).
