### ISSUE TITLE
JSON output?

### ISSUE THREAD

**Issue by cjeanneret** [nabla-c0d3/sslyze#51]
Hello,

Would you accept a JSON output alongside the current XML?

Purpose:
XML is nice and so, but currently the "trend" is more for JSON, as it's really easy to parse it with some small javascript stuff. It would be a better format in order to display elements on some web page.
Also, having a JSON output allows to take profit of the different types like hash and ordered lists, meaning it might be better if we list Server preferred ciphers in Server order.

I'm pretty sure it won't be that hard, as JSON is just, let's say, a list of hashes (or a hash of lists, or both) and can be pretty easily converted to/from this "object" from/to JSON file.

Also, I'm using sslyze in some script, and its original output was JSON ­— I'm using right now some format conversion process, but that's not really the best way to do what I need ;).

Cheers,

C.

**Comment by nabla-c0d3** [comment]
Yes I would but it can't add a new dependency to sslyze (like the previous pull request for json). I'll look into it at some point.

Thanks,

**Comment by cjeanneret** [comment]
hmm. this "limitation" will make this feature almost impossible I think? I'll give it a try though.

It *might* be an optional dependency? like, "by default no json support, but doesn't break anything" ?

**Comment by nabla-c0d3** [comment]
Unfortunately the build/packaging process for nassl and sslyze is very complex already, especially on Windows. I don't want to add another layer of complexity (ie. optional dependencies/features) just for JSON support...

**Comment by cjeanneret** [comment]
makes sense. I'll stick to my XML2JSON conversion then :)
