### ISSUE TITLE
Last working versions for specific Py releases

### ISSUE THREAD

**Issue by sskras** [nabla-c0d3/sslyze#510]
**Is your feature request related to a problem? Please describe.**
Whatever Py version + installation way I try, I get errors.

The last one I got during the installation of SSLyze from git and running on CentOS 7.9.2009:
```
$ git clone http://github.com/nabla-c0d3/sslyze.git
  ...
$ cd sslyze
$ pip3 install .
Processing /home/admin2/sslyze
/usr/local/lib/python3.6/site-packages/setuptools/dist.py:645: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
  % (opt, underscore_opt))
sslyze requires Python '>=3.7' but the running Python is 3.6.8
```

**Describe the solution you'd like**
Can the website or repo somehow pin the last working SSLyze versions for specific Python releases like: 
* 2.7.5
* 3.6.8
... please?

Then I would know at least what to expect.

A table mentioning these versions + a way to install a specific SSLyze release (pip, git, etc) would be perfect. : )
Thanks in advance.

**Describe alternatives you've considered**
#508, #509

**Comment by nabla-c0d3** [comment]
The versions of Python that are currently supported are at the top of the README, displayed as badges. Older versions of Python or SSLyze are no longer supported.

**Comment by sskras** [comment]
@nabla-c0d3:
> The versions of Python that are currently supported are at the top of the README, displayed as badges. Older versions of Python or SSLyze are no longer supported.

Thanks, but you seem to respond to my issues #508 and #509. 

And this my question is different. It's about the older version combos where mainstream Python versions were still supported by SSLyze in the past. I mean version that still work even if are unsupported.

I get from the answer that you don't know this or have no information for such table of past major Py versions.

Now if I do the regression testing myself and come up with such version table, eg:

| Python | Last working commit | Last working version |
| -----: | ------------------: | -------------------: |
|  2.7.5 |           ? 556e272 |              ? [1.4.3](https://github.com/nabla-c0d3/sslyze/releases/tag/1.4.3) |
|  3.6.8 |                TODO |              > [2.1.4](https://github.com/nabla-c0d3/sslyze/releases/tag/2.1.4) |

... are you willing to accept it somewhere in the official repo for the folks like me?
(who just like to run Stable distros with older Pythons, eg. on mainstream servers and still be able to use some functionality)

This would help a great lot.

**Comment by nabla-c0d3** [comment]
Hello,
Thanks for offering to take care of it. 
Unfortunately these older versions have known bugs and are 100% unsupported. Putting a version table will just cause people to open issues about bugs in older versions, which I won't have time to process.
