### ISSUE TITLE
ellipti_curves missing from Docker image

### ISSUE THREAD

**Issue by binarymist** [nabla-c0d3/sslyze#518]
**Describe the bug**

It appears as though there is no elliptic_curves in the Docker image?  
version: 4.0.4 appears to have it, but we get below error.

**To Reproduce**

Running the Docker container:

`docker run --rm -it nablac0d3/sslyze --elliptic_curves <SUT>`

produces:

`sslyze: error: no such option: --elliptic_curves`

**Expected behavior**

Output for elliptic curves

**Comment by nabla-c0d3** [comment]
Will be fixed by #527.

**Comment by nabla-c0d3** [comment]
Fixed with the latest release https://hub.docker.com/r/nablac0d3/sslyze/tags
