### ISSUE TITLE
No local packages or working download links found for nassl<5.0.0,>=4.0.0

### ISSUE THREAD

**Issue by Parad0xs** [nabla-c0d3/sslyze#519]
Hello,

i'd like to report an issue :
I work on Debian 10.
Everything works by pip install but it's had the module in python 2.7.

I've got the following issue when i try to install the module by pip3 or python3.7 setup.py install :

  Installed /usr/local/lib/python3.7/dist-packages/tls_parser-1.2.2-py3.7.egg
  Searching for nassl<5.0.0,>=4.0.0
  Reading https://pypi.org/simple/nassl/
  No local packages or working download links found for nassl<5.0.0,>=4.0.0
  error: Could not find suitable distribution for Requirement.parse('nassl<5.0.0,>=4.0.0')

Best regards ;-)

**Comment by nabla-c0d3** [comment]
Can you try updating `pip` ?

``` 
pip install --upgrade pip
```

**Comment by Parad0xs** [comment]
The issue is solve  !
Thx a lot for your  job ;-)
