### ISSUE TITLE
Docker Tag v4.1.0 is missing 🤔

### ISSUE THREAD

**Issue by rfelber** [nabla-c0d3/sslyze#521]
**Is your feature request related to a problem? Please describe.**
As a **sslyze** user i would like to decide which release version of sslyze is currently running in my infrastructure.

In a fully automated docker container based setup it is somehow a little bit risky to always reference a latest docker tag image instead of specific versions. Additionally to that you docker image (`latest` tag) seems to be a bit outdated (9 month old): https://hub.docker.com/r/nablac0d3/sslyze

The latest release version is currently: v4.1.0
- https://github.com/nabla-c0d3/sslyze/releases

Trying to pull this release version fails 🤭  `docker pull nablac0d3/sslyze:v7.4.0`

see: https://hub.docker.com/r/nablac0d3/sslyze/tags?page=1&ordering=last_updated

**Describe the solution you'd like**
It would be great if your release process will be extended to create stable semantic version tags as **docker image tags** and push them to dockerhub. There are some helpful GitHub actions that could do the job easily 😊

**Describe alternatives you've considered**
none

**Comment by rfelber** [comment]
Do you need a helping hand on this @nabla-c0d3?

**Comment by nabla-c0d3** [comment]
@rseedorff Sure! A GitHub action that takes of this would be nice indeed 👍

**Comment by rfelber** [comment]
Ok, i'll give it a try @nabla-c0d3 

Can you give me some hints what your current branch and release strategy / pattern looks like? For which branch `release` vs `dev-5.0.0` should i create a PR for?

Thx in advance :)

**Comment by nabla-c0d3** [comment]
@rseedorff Thank you!

I think ideally it should be a Github Action that gets triggered whenever a `git tag` is created (all versions have a corresponding tag https://github.com/nabla-c0d3/sslyze/tags ), and that then pushes the code to DockerHub and sets the tag there.

Does this make sense? You can create a PR for `release`. Thanks!

**Comment by rfelber** [comment]
Hi @nabla-c0d3,
i opened a PR for this, feedback is welcome 🙂
