### ISSUE TITLE
Fast-Scan or Basic-Scan for Automation

### ISSUE THREAD

**Issue by teodem** [nabla-c0d3/sslyze#525]
**Is your feature request related to a problem? Please describe.**
SSLyze is a very good tool and works very well. 
There is a small problem with its operation when automated. 
In fact, after its integration in pipeline in Gitlab, the duration times of the normal scan are abnormal. This causes the runner to timeout and block the pipeline. This happen mostly with big tests with a lot of entries. 

**Describe the solution you'd like**
It would be great to have a "Fast-Scan" option or a basic-scan, perhaps with a few less features but testing the bare minimum. This could help to have a lighter and more usable tool in pipeline, helping me and my team to still test, but in less time and without destroying the pipeline. 

**Describe alternatives you've considered**
At the moment we have added a flag to skip tests with SSLyze for too long scans, but it is not a real solution. 
Otherwise, I will have to consider other tools or another solution without SSLyze.

**Comment by nabla-c0d3** [comment]
How many servers are being scanned in one invocation of SSLyze? It could be related to https://github.com/nabla-c0d3/sslyze/issues/511 where the runner runs out of memory and hangs.

**Comment by teodem** [comment]
It's just one server (or maximum 2). All the URLs are from the same web-application. Actually there is no "blocks", but the scan looks still a lot of time (if has to scan a lot of entries).

**Comment by nabla-c0d3** [comment]
@teodem Can you paste here the command that is used to run SSLyze? A scan on a single server should not be a problem.

**Comment by teodem** [comment]
Hi I think i was too quick in the explanation.

`sslyze --regular $domain --json_out=sslyze/scan-$I-$domain.json`

 I use SSLyze via a JSON that contains a list of URLs that I want to scan. I only use their basic domain. So if I have entries like _www.test.com/test/v1_, my parser will only provide SSLyze with _www.test.com_. 

There are several domains involved, often the JSON contains hundreds of entries, which is why scans take so long. To understand, things like _www.app.cloud_ ,  _www.app.int.cloud_ ,  _www.service.cloud_ etc...   

But I noticed that even with 2-3-4 entries, sslyze still takes a few minutes to run. Which is understandable, but I was wondering if it would be possible to have a light-weight or fast-scan function.

**Comment by nabla-c0d3** [comment]
In [v5.0.0](https://github.com/nabla-c0d3/sslyze/releases/tag/5.0.0), SSLyze will automatically run a scan to check the server against Mozilla's recommended configuration - you should try it. 

If it still takes too long, there isn't much I will be able to do... perhaps CI/CD is not the right place for scanning a lot of servers. For example a CRON might be better.
