### ISSUE TITLE
Cryptography released a new version with a new version scheme 35.0.0

### ISSUE THREAD

**Issue by PhilippSelenium** [nabla-c0d3/sslyze#529]
Cryptography changed its versioning the newest version is: 35.0.0 
so this needs to be adapted in setup.py

**Comment by nabla-c0d3** [comment]
The newest version is 5.0.0b0 (it's a beta release): https://github.com/nabla-c0d3/sslyze/blob/dev-5.0.0/sslyze/__version__.py#L2
Where did you see 35.0.0?

**Comment by PhilippSelenium** [comment]
Sorry i meant cryptography ...

**Comment by nabla-c0d3** [comment]
Fixed in [v5.0.0](https://github.com/nabla-c0d3/sslyze/releases/tag/5.0.0).
