### ISSUE TITLE
support for session ticket resumption rate, and possible false negative in ticket resumption 

### ISSUE THREAD

**Issue by lziest** [nabla-c0d3/sslyze#53]
It would be nice to extend --resum_rate to include session ticket resumption tests.

And there is a possibility that session ticket resumption return "false" even though the session is correctly resumed, because it only compares the sent session ticket and returned one, but according RFC 5077, the server may return a renewed session ticket if the ticket encryption key is rotated. I would recommend using the more reliable 'hit' bit in OpenSSL's SSL struct.

**Comment by nabla-c0d3** [comment]
Thanks and sounds good. I'll look into this.

**Comment by nabla-c0d3** [comment]
Fixed in [v5.0.0](https://github.com/nabla-c0d3/sslyze/releases/tag/5.0.0).
