### ISSUE TITLE
Support for resolve into multiple IP's

### ISSUE THREAD

**Issue by hmilkovi** [nabla-c0d3/sslyze#540]
**Is your feature request related to a problem? Please describe.**
Hostname is resolved to multiple server IP's where one can have valid ssl certificate other not so the scan can provide "partial false" data.

**Describe the solution you'd like**
Should support to resolve to multiple IP's then scan all IP's with given hostname.

**Describe alternatives you've considered**
Custom resolve hostname to IP's then provide multiple info to scan.

**Additional context**
Many HA setups have DNS load balancing or resolve to multiple IP's so to solve this it would be nice to have :)

**Comment by hmilkovi** [comment]
I will maybe make PR when I have time, just please check if this makes sense to implement in lib or user alternative to implement it myself then give multiple scan instances to scanner instance?

**Comment by nabla-c0d3** [comment]
Hello,

You can force a specific IP to be scanned:

```
python -m sslyze www.cloudflare.com{1.1.1.1}
```

Hence, you can achieve what you want by supplying all the IPs you want to scan to SSLyze.

**Comment by hmilkovi** [comment]
You are super. I use Python API and this is now even easier via:
```
class sslyze.ServerNetworkLocation(hostname, port=443, ip_address=None, http_proxy_settings=None)
```

Many thanks for you work :)
