### ISSUE TITLE
Support cryptography 36.0.0

### ISSUE THREAD

**Issue by PhilippSelenium** [nabla-c0d3/sslyze#542]
https://pypi.org/project/cryptography/

;)

Maybe enabling this https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates might help to do this automatically?

**Comment by nabla-c0d3** [comment]
This was fixed in [v5.0.1](https://github.com/nabla-c0d3/sslyze/releases/tag/5.0.1).
