### ISSUE TITLE
Mozilla report conflicts with JSON reporting

### ISSUE THREAD

**Issue by dcarley** [nabla-c0d3/sslyze#543]
**Describe the bug**
We call SSLyze from some integration tests, parse the JSON report, and make assertions on about protocols/ciphers that we expect to see. The new `--mozilla-config` functionality conflicts with our use in two ways:

1. the plaintext output to STDOUT means that `json_out=-` doesn't produce valid JSON
1. the exit code of 1, when the Mozilla check is not compliant, is hard to distinguish from other errors

I considered raising these as separate issues but I think it's possible to solve them both at the same time by including the Mozilla report in the JSON output and not changing the exit code when not compliant, so that you can perform your own assertions on the output.

**To Reproduce**

Parsing the output with `jq` results in an error when it gets to the Mozilla banner:
```
$ docker run --rm nablac0d3/sslyze:5.0.0 --json_out=- google.com | jq .sslyze_version ; echo $?
"5.0.0"
parse error: Invalid numeric literal at line 10090, column 12
4
```

Scanning a server with a self-signed certificate produces a non-zero exit code:
```
$ docker run --rm nablac0d3/sslyze:5.0.0 --json_out=- 10.108.40.189 >/dev/null; echo $?
1
```

**Expected behavior**

These both resulted in zero exit codes in the previously published version:
```
$ docker run --rm nablac0d3/sslyze:sha-7e16dc0 --json_out=- google.com | jq .sslyze_version ; echo $?
"4.1.0"
0
$ docker run --rm nablac0d3/sslyze:sha-7e16dc0 --json_out=- 10.108.40.189 >/dev/null; echo $?
0
```

**Additional context**
The utility is great and so is the new Mozilla functionality. Thanks!

**Comment by nabla-c0d3** [comment]
This was fixed in [v5.0.1](https://github.com/nabla-c0d3/sslyze/releases/tag/5.0.1).
