### ISSUE TITLE
Option to shorthand the rejected ciphers in JSON output when TLS version is not supported

### ISSUE THREAD

**Issue by ctminime** [nabla-c0d3/sslyze#549]
When scanning many servers and sending the output to JSON, the file can get quite large. For instance, scanning around 200 servers can result in over a 40MB file, without any certificate information. I noticed that a lot of this space is used up by the "rejected_cipher_suites". What I propose is to have either an option/switch (if this would break the schema or if this data has a use case) or as just a change in the way it outputs, is this:

If "is_tls_version_supported" is false, then set "rejected_cipher_suites" to "all". So, it would look something like this instead of listing out all the rejected cipher suites.

"ssl_3_0_cipher_suites": {
    "error_reason": null,
    "error_trace": null,
    "result": {
        "accepted_cipher_suites": [],
        "is_tls_version_supported": false,
        "rejected_cipher_suites": "all",
        "tls_version_used": "SSL_3_0"
    },
    "status": "COMPLETED"
}

When doing a JSON output for a single server that has only TLS 1.2 enabled, the file it generated was 405KB. I then manually edited the file, in accordance with what I suggested above, and the file size reduced to 282KB. That is more than a 25% space savings. And I would guess that this could improve parsing speed for very large JSON files.

**Comment by nabla-c0d3** [comment]
Hello,
I would suggest compressing the files (tar.gz or similar). This will give you the best results: a 630 kb JSON result file becomes 48 kb when compressed.
