### ISSUE TITLE
wrong hint to --mozilla-config in scan results

### ISSUE THREAD

**Issue by danielpauldd** [nabla-c0d3/sslyze#561]
In scan results there is a hint for compliance checking agains Mozilla TLS Configuration:

```
 COMPLIANCE AGAINST MOZILLA TLS CONFIGURATION
 --------------------------------------------

    Disabled; use --mozilla-config={old, intermediate, modern}.
```
--> that is after renaming the paramter to `--mozilla_config` not correct anymore.

**Comment by nabla-c0d3** [comment]
Thanks - this was fixed in v5.0.3.
