### ISSUE TITLE
Counter nssl problem when creating docker image

### ISSUE THREAD

**Issue by HeangSok** [nabla-c0d3/sslyze#564]
Hi nabla, I had cloned your github repository and try to make a new docker image from it; however, it showed an error with nssl. I even use the same Dockerfile like yours, but I still get the same error. 

I also tried to build a docker image from python3.9-slim, then I install sslyze with pip (pip install --upgrade sslyze), but I still get the same error with nssl.

May you tell me how you build the docker image? Thank you.

**Comment by nabla-c0d3** [comment]
Hello, Unfortunately I don't have time to provide technical support. Good luck!
