### ISSUE TITLE
Error building Dockerfile locally in MacOS

### ISSUE THREAD

**Issue by theinfosecguy** [nabla-c0d3/sslyze#569]
**Describe the bug**
While building the Dockerfile, getting the following error message
```
error: Could not find suitable distribution for Requirement.parse('nassl<5.0.0,>=4.0.1')
```

**To Reproduce**
1. Clone the sslyze github repository
2. Build the Dockerfile using `docker build . -t sslyze1.0`
3. Run the Dockerfile `docker run sslyze1.0`

**Python environment (please complete the following information):**
 - OS: macOS Monterey
 - Python version: Running it using Docker

**Comment by HeangSok** [comment]
Please set your platform to "linux/amd64".

My Dockerfile: 
-----------------
FROM python:3.9-slim
WORKDIR /app
COPY . .
RUN apt-get update && apt-get install -y sudo
RUN sudo pip install --upgrade pip setuptools wheel
RUN pip install --upgrade sslyze
CMD tail -f /dev/null

My docker-compose:
---------------------
version: '3.8'
services:
  nuclei:
    build: .
    container_name: testssl
    platform: "linux/amd64" 
    volumes:
      - .:/app
volumes:
  .:

My machine:
-----------------
- mac m1 chip

**Comment by theinfosecguy** [comment]
That worked for me. Is there any way to make it work without using Docker?
