### ISSUE TITLE
Missing support for pydantic 1.10

### ISSUE THREAD

**Issue by extrwi** [nabla-c0d3/sslyze#576]
**Describe the bug**

pydantic 1.10.2 has recently been [released](https://pydantic-docs.helpmanual.io/changelog/), but sslyze is constrained to <1.10.

```toml
pydantic = ">=1.7,<1.10"
```

When embedding sslyze as a library, it's not possible to use pydantic 1.10 in the embedding program.

**Expected behavior**

```toml
pydantic = ">=1.7,<1.11"
```

**Comment by nabla-c0d3** [comment]
Fix released as part of [v5.0.6](https://github.com/nabla-c0d3/sslyze/releases/tag/5.0.6).
