### ISSUE TITLE
cipher suite naming convention

### ISSUE THREAD

**Issue by postmodern** [nabla-c0d3/sslyze#58]
I noticed that sslyze uses hyphenated names (ex: `ECDHE-ECDSA-NULL-SHA`) but most people identify TLS cipher suites using underscores (ex: `TLS_RSA_EXPORT_WITH_DES40_CBC_SHA`). Should both names be included in the output? Is there a canonical naming convention for cipher suites?

**Comment by postmodern** [comment]
Ah, apparently the `FOO-BAR` names are an artifact of OpenSSL. https://www.openssl.org/docs/apps/ciphers.html

**Comment by nabla-c0d3** [comment]
Closing this a duplicate of issue #66
