### ISSUE TITLE
Parse basicConstraints

### ISSUE THREAD

**Issue by postmodern** [nabla-c0d3/sslyze#59]
I noticed the `<x509v3BasicConstraints>` is a plain string. The BasicConstraints extensions can be defined in short form `CA:FALSE pathLen:0` or so called [long form](https://www.openssl.org/docs/apps/x509v3_config.html). I think it would be useful to fully parse the basic constraints into key:value pairs.

**Comment by postmodern** [comment]
Currently, I'm just using crude regexps to pull out the values from the string.

**Comment by nabla-c0d3** [comment]
Fixed in https://github.com/nabla-c0d3/nassl/commit/1ad33d0b65e84550c2ff15189bf284f2e6a85d01
