### ISSUE TITLE
Segmentation Fault for Most Targets

### ISSUE THREAD

**Issue by onurgule** [nabla-c0d3/sslyze#594]
I am using OpenSSL version 1.1.1k and when I tried to use sslyze, it gives segmentation fault for **most** targets.

 ![Screen Shot 2023-01-23 at 16 48 18](https://user-images.githubusercontent.com/1492430/214056609-853a1ef4-953c-4d21-b7eb-536db74c3830.png)

Logs in /var/log/message:

![Screen Shot 2023-01-23 at 16 53 27](https://user-images.githubusercontent.com/1492430/214057246-065c7395-69a0-46b6-8a1a-305f134525de.png)

It seems there is a bug with libcrypto.so.1.1.1k file.

**Environment:**
 - OS: Red Hat Linux 8.6 (Ootpa)
 - Python version: 3.8.12
 - SSLyze version: 5.1.1
 - OpenSSL version: 1.1.1k

Additionally, it works with some targets:
![Screen Shot 2023-01-23 at 17 05 28](https://user-images.githubusercontent.com/1492430/214060263-ae29182e-3753-470a-b6d3-db8929ed9773.png)

I'm not sure if it's related with the issue #556.

**Comment by nabla-c0d3** [comment]
It is the same issue as https://github.com/nabla-c0d3/sslyze/issues/556 - I will close this one here as a duplicate. Thanks

**Comment by onurgule** [comment]
I tried to fix with RHEL but it needs to upgrade to 9 because of the OpenSSL dependencies.
Had to change hosts to Kali, if anyone facing the same problem in the future.
Thanks.
