### ISSUE TITLE
NASSL Error installing on latest Kali Linux

### ISSUE THREAD

**Issue by eapolsniper** [nabla-c0d3/sslyze#598]
I can't install NASSL on the latest version of Kali. There's no package in apt, pip fails to install it. Here's the error when I try to pip install sslyze:

└─# pip install --upgrade sslyze
Collecting sslyze
  Using cached sslyze-5.1.2.tar.gz (966 kB)
  Preparing metadata (setup.py) ... done
  Using cached sslyze-5.1.1.tar.gz (979 kB)
  Preparing metadata (setup.py) ... done
  Using cached sslyze-5.1.0.tar.gz (979 kB)
  Preparing metadata (setup.py) ... done
  Using cached sslyze-5.0.6.tar.gz (988 kB)
  Preparing metadata (setup.py) ... done
  Using cached sslyze-5.0.5.tar.gz (985 kB)
  Preparing metadata (setup.py) ... done
  Using cached sslyze-5.0.4.tar.gz (975 kB)
  Preparing metadata (setup.py) ... done
  Using cached sslyze-5.0.3.tar.gz (977 kB)
  Preparing metadata (setup.py) ... done
  Using cached sslyze-5.0.2.tar.gz (1.1 MB)
  Preparing metadata (setup.py) ... done
  Using cached sslyze-5.0.1.tar.gz (1.1 MB)
  Preparing metadata (setup.py) ... done
  Using cached sslyze-5.0.0.tar.gz (1.0 MB)
  Preparing metadata (setup.py) ... done
  Using cached sslyze-4.1.0.tar.gz (1.0 MB)
  Preparing metadata (setup.py) ... done
  Using cached sslyze-4.0.4.tar.gz (1.0 MB)
  Preparing metadata (setup.py) ... done
  Using cached sslyze-4.0.3.tar.gz (1.0 MB)
  Preparing metadata (setup.py) ... done
  Using cached sslyze-4.0.2.tar.gz (1.0 MB)
  Preparing metadata (setup.py) ... done
  Using cached sslyze-4.0.1.tar.gz (1.0 MB)
  Preparing metadata (setup.py) ... done
  Using cached sslyze-4.0.0.tar.gz (1.0 MB)
  Preparing metadata (setup.py) ... done
  Using cached sslyze-3.1.0.tar.gz (1.0 MB)
  Preparing metadata (setup.py) ... done
  Using cached sslyze-3.0.8.tar.gz (1.0 MB)
  Preparing metadata (setup.py) ... done
  Using cached sslyze-3.0.7.tar.gz (1.0 MB)
  Preparing metadata (setup.py) ... done
  Using cached sslyze-3.0.6.tar.gz (1.0 MB)
  Preparing metadata (setup.py) ... done
  Using cached sslyze-3.0.4.tar.gz (1.0 MB)
  Preparing metadata (setup.py) ... done
  Using cached sslyze-3.0.3.tar.gz (1.0 MB)
  Preparing metadata (setup.py) ... done
  Using cached sslyze-3.0.2.tar.gz (1.0 MB)
  Preparing metadata (setup.py) ... done
  Using cached sslyze-3.0.1.tar.gz (1.0 MB)
  Preparing metadata (setup.py) ... done
  Using cached sslyze-3.0.0.tar.gz (1.0 MB)
  Preparing metadata (setup.py) ... done
  Using cached sslyze-2.1.4.tar.gz (1.1 MB)
  Preparing metadata (setup.py) ... done
  Using cached sslyze-2.1.3.tar.gz (1.0 MB)
  Preparing metadata (setup.py) ... done
  Using cached sslyze-2.1.2.tar.gz (1.1 MB)
  Preparing metadata (setup.py) ... done
  Using cached sslyze-2.1.1.tar.gz (1.1 MB)
  Preparing metadata (setup.py) ... done
  Using cached sslyze-2.1.0.tar.gz (971 kB)
  Preparing metadata (setup.py) ... done
  Using cached sslyze-2.0.6.tar.gz (1.2 MB)
  Preparing metadata (setup.py) ... done
  Using cached sslyze-2.0.5.tar.gz (1.2 MB)
  Preparing metadata (setup.py) ... done
  Using cached sslyze-2.0.4.tar.gz (1.2 MB)
  Preparing metadata (setup.py) ... done
  Using cached sslyze-2.0.3.tar.gz (1.2 MB)
  Preparing metadata (setup.py) ... done
  Using cached sslyze-2.0.2.tar.gz (1.2 MB)
  Preparing metadata (setup.py) ... done
  Using cached sslyze-2.0.1.tar.gz (1.1 MB)
  Preparing metadata (setup.py) ... done
  Using cached sslyze-2.0.0.tar.gz (1.1 MB)
  Preparing metadata (setup.py) ... done
  Using cached SSLyze-1.4.3.tar.gz (1.1 MB)
  Preparing metadata (setup.py) ... done
  Using cached SSLyze-1.4.2.tar.gz (1.1 MB)
  Preparing metadata (setup.py) ... done
  Using cached SSLyze-1.4.1.tar.gz (1.0 MB)
  Preparing metadata (setup.py) ... done
  Using cached SSLyze-1.4.0.tar.gz (1.0 MB)
  Preparing metadata (setup.py) ... done
  Using cached SSLyze-1.3.4-py3-none-any.whl
Collecting nassl<1.1.0,>=1.0.0
  Using cached nassl-1.0.3.tar.gz (30.0 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: cryptography>=2.1.4 in /usr/lib/python3/dist-packages (from sslyze) (38.0.4)
Requirement already satisfied: tls-parser<1.3.0,>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from sslyze) (1.2.2)
Building wheels for collected packages: nassl
  Building wheel for nassl (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      /usr/local/lib/python3.11/dist-packages/setuptools/dist.py:788: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-311
      creating build/lib.linux-aarch64-cpython-311/nassl
      copying nassl/__init__.py -> build/lib.linux-aarch64-cpython-311/nassl
      copying nassl/ssl_client.py -> build/lib.linux-aarch64-cpython-311/nassl
      copying nassl/legacy_ssl_client.py -> build/lib.linux-aarch64-cpython-311/nassl
      copying nassl/ocsp_response.py -> build/lib.linux-aarch64-cpython-311/nassl
      running build_ext
      building 'nassl._nassl_legacy' extension
      creating build/temp.linux-aarch64-cpython-311
      creating build/temp.linux-aarch64-cpython-311/nassl
      creating build/temp.linux-aarch64-cpython-311/nassl/_nassl
      aarch64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DLEGACY_OPENSSL=1 -I/tmp/pip-install-wlkueauo/nassl_f5058434955544be8913d472a57eba91/bin/openssl-legacy/include -Inassl/_nassl -I/usr/include/python3.11 -c nassl/_nassl/nassl.c -o build/temp.linux-aarch64-cpython-311/nassl/_nassl/nassl.o -Wall
      aarch64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DLEGACY_OPENSSL=1 -I/tmp/pip-install-wlkueauo/nassl_f5058434955544be8913d472a57eba91/bin/openssl-legacy/include -Inassl/_nassl -I/usr/include/python3.11 -c nassl/_nassl/nassl_BIO.c -o build/temp.linux-aarch64-cpython-311/nassl/_nassl/nassl_BIO.o -Wall
      aarch64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DLEGACY_OPENSSL=1 -I/tmp/pip-install-wlkueauo/nassl_f5058434955544be8913d472a57eba91/bin/openssl-legacy/include -Inassl/_nassl -I/usr/include/python3.11 -c nassl/_nassl/nassl_OCSP_RESPONSE.c -o build/temp.linux-aarch64-cpython-311/nassl/_nassl/nassl_OCSP_RESPONSE.o -Wall
      aarch64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DLEGACY_OPENSSL=1 -I/tmp/pip-install-wlkueauo/nassl_f5058434955544be8913d472a57eba91/bin/openssl-legacy/include -Inassl/_nassl -I/usr/include/python3.11 -c nassl/_nassl/nassl_SSL.c -o build/temp.linux-aarch64-cpython-311/nassl/_nassl/nassl_SSL.o -Wall
      aarch64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DLEGACY_OPENSSL=1 -I/tmp/pip-install-wlkueauo/nassl_f5058434955544be8913d472a57eba91/bin/openssl-legacy/include -Inassl/_nassl -I/usr/include/python3.11 -c nassl/_nassl/nassl_SSL_CTX.c -o build/temp.linux-aarch64-cpython-311/nassl/_nassl/nassl_SSL_CTX.o -Wall
      In function ‘pem_passwd_cb’,
          inlined from ‘pem_passwd_cb’ at nassl/_nassl/nassl_SSL_CTX.c:238:12:
      nassl/_nassl/nassl_SSL_CTX.c:260:5: warning: ‘strncpy’ specified bound depends on the length of the source argument [-Wstringop-truncation]
        260 |     strncpy(buf, passwordBuf, passwordSize);
            |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      nassl/_nassl/nassl_SSL_CTX.c:253:20: note: length computed here
        253 |     passwordSize = strlen(passwordBuf) + 1;
            |                    ^~~~~~~~~~~~~~~~~~~
      aarch64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DLEGACY_OPENSSL=1 -I/tmp/pip-install-wlkueauo/nassl_f5058434955544be8913d472a57eba91/bin/openssl-legacy/include -Inassl/_nassl -I/usr/include/python3.11 -c nassl/_nassl/nassl_SSL_SESSION.c -o build/temp.linux-aarch64-cpython-311/nassl/_nassl/nassl_SSL_SESSION.o -Wall
      aarch64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DLEGACY_OPENSSL=1 -I/tmp/pip-install-wlkueauo/nassl_f5058434955544be8913d472a57eba91/bin/openssl-legacy/include -Inassl/_nassl -I/usr/include/python3.11 -c nassl/_nassl/nassl_X509.c -o build/temp.linux-aarch64-cpython-311/nassl/_nassl/nassl_X509.o -Wall
      aarch64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DLEGACY_OPENSSL=1 -I/tmp/pip-install-wlkueauo/nassl_f5058434955544be8913d472a57eba91/bin/openssl-legacy/include -Inassl/_nassl -I/usr/include/python3.11 -c nassl/_nassl/nassl_X509_EXTENSION.c -o build/temp.linux-aarch64-cpython-311/nassl/_nassl/nassl_X509_EXTENSION.o -Wall
      aarch64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DLEGACY_OPENSSL=1 -I/tmp/pip-install-wlkueauo/nassl_f5058434955544be8913d472a57eba91/bin/openssl-legacy/include -Inassl/_nassl -I/usr/include/python3.11 -c nassl/_nassl/nassl_X509_NAME_ENTRY.c -o build/temp.linux-aarch64-cpython-311/nassl/_nassl/nassl_X509_NAME_ENTRY.o -Wall
      aarch64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DLEGACY_OPENSSL=1 -I/tmp/pip-install-wlkueauo/nassl_f5058434955544be8913d472a57eba91/bin/openssl-legacy/include -Inassl/_nassl -I/usr/include/python3.11 -c nassl/_nassl/nassl_errors.c -o build/temp.linux-aarch64-cpython-311/nassl/_nassl/nassl_errors.o -Wall
      aarch64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DLEGACY_OPENSSL=1 -I/tmp/pip-install-wlkueauo/nassl_f5058434955544be8913d472a57eba91/bin/openssl-legacy/include -Inassl/_nassl -I/usr/include/python3.11 -c nassl/_nassl/openssl_utils.c -o build/temp.linux-aarch64-cpython-311/nassl/_nassl/openssl_utils.o -Wall
      aarch64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DLEGACY_OPENSSL=1 -I/tmp/pip-install-wlkueauo/nassl_f5058434955544be8913d472a57eba91/bin/openssl-legacy/include -Inassl/_nassl -I/usr/include/python3.11 -c nassl/_nassl/python_utils.c -o build/temp.linux-aarch64-cpython-311/nassl/_nassl/python_utils.o -Wall
      aarch64-linux-gnu-gcc -shared -Wl,-O1 -Wl,-Bsymbolic-functions -g -fwrapv -O2 build/temp.linux-aarch64-cpython-311/nassl/_nassl/nassl.o build/temp.linux-aarch64-cpython-311/nassl/_nassl/nassl_BIO.o build/temp.linux-aarch64-cpython-311/nassl/_nassl/nassl_OCSP_RESPONSE.o build/temp.linux-aarch64-cpython-311/nassl/_nassl/nassl_SSL.o build/temp.linux-aarch64-cpython-311/nassl/_nassl/nassl_SSL_CTX.o build/temp.linux-aarch64-cpython-311/nassl/_nassl/nassl_SSL_SESSION.o build/temp.linux-aarch64-cpython-311/nassl/_nassl/nassl_X509.o build/temp.linux-aarch64-cpython-311/nassl/_nassl/nassl_X509_EXTENSION.o build/temp.linux-aarch64-cpython-311/nassl/_nassl/nassl_X509_NAME_ENTRY.o build/temp.linux-aarch64-cpython-311/nassl/_nassl/nassl_errors.o build/temp.linux-aarch64-cpython-311/nassl/_nassl/openssl_utils.o build/temp.linux-aarch64-cpython-311/nassl/_nassl/python_utils.o /tmp/pip-install-wlkueauo/nassl_f5058434955544be8913d472a57eba91/bin/openssl-legacy/linux64/libssl.a /tmp/pip-install-wlkueauo/nassl_f5058434955544be8913d472a57eba91/bin/openssl-legacy/linux64/libcrypto.a /tmp/pip-install-wlkueauo/nassl_f5058434955544be8913d472a57eba91/bin/zlib/linux64/libz.a -L/usr/lib/aarch64-linux-gnu -o build/lib.linux-aarch64-cpython-311/nassl/_nassl_legacy.cpython-311-aarch64-linux-gnu.so
      /usr/bin/ld: /tmp/pip-install-wlkueauo/nassl_f5058434955544be8913d472a57eba91/bin/openssl-legacy/linux64/libssl.a(s2_meth.o): Relocations in generic ELF (EM: 62)
      /usr/bin/ld: /tmp/pip-install-wlkueauo/nassl_f5058434955544be8913d472a57eba91/bin/openssl-legacy/linux64/libssl.a(s2_meth.o): Relocations in generic ELF (EM: 62)
      /usr/bin/ld: /tmp/pip-install-wlkueauo/nassl_f5058434955544be8913d472a57eba91/bin/openssl-legacy/linux64/libssl.a(s2_meth.o): Relocations in generic ELF (EM: 62)
      /usr/bin/ld: /tmp/pip-install-wlkueauo/nassl_f5058434955544be8913d472a57eba91/bin/openssl-legacy/linux64/libssl.a: error adding symbols: file in wrong format
      collect2: error: ld returned 1 exit status
      error: command '/usr/bin/aarch64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for nassl
  Running setup.py clean for nassl                                                                                                     
Failed to build nassl
Installing collected packages: nassl, sslyze
  Running setup.py install for nassl ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for nassl did not run successfully.
  │ exit code: 1
  ╰─> [46 lines of output]
      /usr/local/lib/python3.11/dist-packages/setuptools/dist.py:788: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      running install
      /usr/local/lib/python3.11/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-311
      creating build/lib.linux-aarch64-cpython-311/nassl
      copying nassl/__init__.py -> build/lib.linux-aarch64-cpython-311/nassl
      copying nassl/ssl_client.py -> build/lib.linux-aarch64-cpython-311/nassl
      copying nassl/legacy_ssl_client.py -> build/lib.linux-aarch64-cpython-311/nassl
      copying nassl/ocsp_response.py -> build/lib.linux-aarch64-cpython-311/nassl
      running build_ext
      building 'nassl._nassl_legacy' extension
      creating build/temp.linux-aarch64-cpython-311
      creating build/temp.linux-aarch64-cpython-311/nassl
      creating build/temp.linux-aarch64-cpython-311/nassl/_nassl
      aarch64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DLEGACY_OPENSSL=1 -I/tmp/pip-install-wlkueauo/nassl_f5058434955544be8913d472a57eba91/bin/openssl-legacy/include -Inassl/_nassl -I/usr/include/python3.11 -c nassl/_nassl/nassl.c -o build/temp.linux-aarch64-cpython-311/nassl/_nassl/nassl.o -Wall
      aarch64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DLEGACY_OPENSSL=1 -I/tmp/pip-install-wlkueauo/nassl_f5058434955544be8913d472a57eba91/bin/openssl-legacy/include -Inassl/_nassl -I/usr/include/python3.11 -c nassl/_nassl/nassl_BIO.c -o build/temp.linux-aarch64-cpython-311/nassl/_nassl/nassl_BIO.o -Wall
      aarch64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DLEGACY_OPENSSL=1 -I/tmp/pip-install-wlkueauo/nassl_f5058434955544be8913d472a57eba91/bin/openssl-legacy/include -Inassl/_nassl -I/usr/include/python3.11 -c nassl/_nassl/nassl_OCSP_RESPONSE.c -o build/temp.linux-aarch64-cpython-311/nassl/_nassl/nassl_OCSP_RESPONSE.o -Wall
      aarch64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DLEGACY_OPENSSL=1 -I/tmp/pip-install-wlkueauo/nassl_f5058434955544be8913d472a57eba91/bin/openssl-legacy/include -Inassl/_nassl -I/usr/include/python3.11 -c nassl/_nassl/nassl_SSL.c -o build/temp.linux-aarch64-cpython-311/nassl/_nassl/nassl_SSL.o -Wall
      aarch64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DLEGACY_OPENSSL=1 -I/tmp/pip-install-wlkueauo/nassl_f5058434955544be8913d472a57eba91/bin/openssl-legacy/include -Inassl/_nassl -I/usr/include/python3.11 -c nassl/_nassl/nassl_SSL_CTX.c -o build/temp.linux-aarch64-cpython-311/nassl/_nassl/nassl_SSL_CTX.o -Wall
      In function ‘pem_passwd_cb’,
          inlined from ‘pem_passwd_cb’ at nassl/_nassl/nassl_SSL_CTX.c:238:12:
      nassl/_nassl/nassl_SSL_CTX.c:260:5: warning: ‘strncpy’ specified bound depends on the length of the source argument [-Wstringop-truncation]
        260 |     strncpy(buf, passwordBuf, passwordSize);
            |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      nassl/_nassl/nassl_SSL_CTX.c:253:20: note: length computed here
        253 |     passwordSize = strlen(passwordBuf) + 1;
            |                    ^~~~~~~~~~~~~~~~~~~
      aarch64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DLEGACY_OPENSSL=1 -I/tmp/pip-install-wlkueauo/nassl_f5058434955544be8913d472a57eba91/bin/openssl-legacy/include -Inassl/_nassl -I/usr/include/python3.11 -c nassl/_nassl/nassl_SSL_SESSION.c -o build/temp.linux-aarch64-cpython-311/nassl/_nassl/nassl_SSL_SESSION.o -Wall
      aarch64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DLEGACY_OPENSSL=1 -I/tmp/pip-install-wlkueauo/nassl_f5058434955544be8913d472a57eba91/bin/openssl-legacy/include -Inassl/_nassl -I/usr/include/python3.11 -c nassl/_nassl/nassl_X509.c -o build/temp.linux-aarch64-cpython-311/nassl/_nassl/nassl_X509.o -Wall
      aarch64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DLEGACY_OPENSSL=1 -I/tmp/pip-install-wlkueauo/nassl_f5058434955544be8913d472a57eba91/bin/openssl-legacy/include -Inassl/_nassl -I/usr/include/python3.11 -c nassl/_nassl/nassl_X509_EXTENSION.c -o build/temp.linux-aarch64-cpython-311/nassl/_nassl/nassl_X509_EXTENSION.o -Wall
      aarch64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DLEGACY_OPENSSL=1 -I/tmp/pip-install-wlkueauo/nassl_f5058434955544be8913d472a57eba91/bin/openssl-legacy/include -Inassl/_nassl -I/usr/include/python3.11 -c nassl/_nassl/nassl_X509_NAME_ENTRY.c -o build/temp.linux-aarch64-cpython-311/nassl/_nassl/nassl_X509_NAME_ENTRY.o -Wall
      aarch64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DLEGACY_OPENSSL=1 -I/tmp/pip-install-wlkueauo/nassl_f5058434955544be8913d472a57eba91/bin/openssl-legacy/include -Inassl/_nassl -I/usr/include/python3.11 -c nassl/_nassl/nassl_errors.c -o build/temp.linux-aarch64-cpython-311/nassl/_nassl/nassl_errors.o -Wall
      aarch64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DLEGACY_OPENSSL=1 -I/tmp/pip-install-wlkueauo/nassl_f5058434955544be8913d472a57eba91/bin/openssl-legacy/include -Inassl/_nassl -I/usr/include/python3.11 -c nassl/_nassl/openssl_utils.c -o build/temp.linux-aarch64-cpython-311/nassl/_nassl/openssl_utils.o -Wall
      aarch64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DLEGACY_OPENSSL=1 -I/tmp/pip-install-wlkueauo/nassl_f5058434955544be8913d472a57eba91/bin/openssl-legacy/include -Inassl/_nassl -I/usr/include/python3.11 -c nassl/_nassl/python_utils.c -o build/temp.linux-aarch64-cpython-311/nassl/_nassl/python_utils.o -Wall
      aarch64-linux-gnu-gcc -shared -Wl,-O1 -Wl,-Bsymbolic-functions -g -fwrapv -O2 build/temp.linux-aarch64-cpython-311/nassl/_nassl/nassl.o build/temp.linux-aarch64-cpython-311/nassl/_nassl/nassl_BIO.o build/temp.linux-aarch64-cpython-311/nassl/_nassl/nassl_OCSP_RESPONSE.o build/temp.linux-aarch64-cpython-311/nassl/_nassl/nassl_SSL.o build/temp.linux-aarch64-cpython-311/nassl/_nassl/nassl_SSL_CTX.o build/temp.linux-aarch64-cpython-311/nassl/_nassl/nassl_SSL_SESSION.o build/temp.linux-aarch64-cpython-311/nassl/_nassl/nassl_X509.o build/temp.linux-aarch64-cpython-311/nassl/_nassl/nassl_X509_EXTENSION.o build/temp.linux-aarch64-cpython-311/nassl/_nassl/nassl_X509_NAME_ENTRY.o build/temp.linux-aarch64-cpython-311/nassl/_nassl/nassl_errors.o build/temp.linux-aarch64-cpython-311/nassl/_nassl/openssl_utils.o build/temp.linux-aarch64-cpython-311/nassl/_nassl/python_utils.o /tmp/pip-install-wlkueauo/nassl_f5058434955544be8913d472a57eba91/bin/openssl-legacy/linux64/libssl.a /tmp/pip-install-wlkueauo/nassl_f5058434955544be8913d472a57eba91/bin/openssl-legacy/linux64/libcrypto.a /tmp/pip-install-wlkueauo/nassl_f5058434955544be8913d472a57eba91/bin/zlib/linux64/libz.a -L/usr/lib/aarch64-linux-gnu -o build/lib.linux-aarch64-cpython-311/nassl/_nassl_legacy.cpython-311-aarch64-linux-gnu.so
      /usr/bin/ld: /tmp/pip-install-wlkueauo/nassl_f5058434955544be8913d472a57eba91/bin/openssl-legacy/linux64/libssl.a(s2_meth.o): Relocations in generic ELF (EM: 62)
      /usr/bin/ld: /tmp/pip-install-wlkueauo/nassl_f5058434955544be8913d472a57eba91/bin/openssl-legacy/linux64/libssl.a(s2_meth.o): Relocations in generic ELF (EM: 62)
      /usr/bin/ld: /tmp/pip-install-wlkueauo/nassl_f5058434955544be8913d472a57eba91/bin/openssl-legacy/linux64/libssl.a(s2_meth.o): Relocations in generic ELF (EM: 62)
      /usr/bin/ld: /tmp/pip-install-wlkueauo/nassl_f5058434955544be8913d472a57eba91/bin/openssl-legacy/linux64/libssl.a: error adding symbols: file in wrong format
      collect2: error: ld returned 1 exit status
      error: command '/usr/bin/aarch64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> nassl

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by nabla-c0d3** [comment]
Hello,
SSLyze can be installed on Kali via `sudo apt install sslyze` : https://www.kali.org/tools/sslyze/
