### ISSUE TITLE
Mozilla TLS configuration out-of-date

### ISSUE THREAD

**Issue by jrchenery** [nabla-c0d3/sslyze#608]
**Describe the bug**
The TLS configuration recommendations from Mozilla are out-of-date.  There is now a version 5.7, SSLyze is still using 5.6.
Running SSLyze against config that aligns with these new recommendations returns 'FAILED - Not compliant'

**To Reproduce**
1. Run SSLyze against a configuration that complies with the latest Mozilla recommendations.
2. Result is 'FAILED - Not compliant'

**Expected behavior**
The Mozilla configuration should be updated to version 5.7

**Python environment**
 - OS: AlmaLinux 8.8
 - Python version: 3.9

**Comment by nabla-c0d3** [comment]
Thanks for the PR!

**Comment by nabla-c0d3** [comment]
Fixed in [v5.2.0](https://github.com/nabla-c0d3/sslyze/releases/tag/5.2.0).
