### ISSUE TITLE
Strangle nassl error when testing SSLv3

### ISSUE THREAD

**Issue by postmodern** [nabla-c0d3/sslyze#61]
Ran into this freak error. Cannot seem to reproduce it.

<pre>
SCAN RESULTS FOR 192.186.208.98:993 - 192.186.208.98:993
--------------------------------------------------------

  * Deflate Compression:
      OK - Compression disabled

Unhandled exception when processing --reneg:
 _nassl.OpenSSLError - error:140940F5:SSL routines:SSL3_READ_BYTES:unexpected record
</pre>

**Comment by nabla-c0d3** [comment]
This is most likely cause by a bugger server as OpenSSL is complaining about the server's response.

**Comment by nabla-c0d3** [comment]
Or a really slow/buggy network...
