### ISSUE TITLE
Servers requesting client cert can cause scan to hang forever if server closes connection

### ISSUE THREAD

**Issue by FestiveKyle** [nabla-c0d3/sslyze#612]
**Describe the bug**

If a server requests a client cert but then closes the connection, the scan will never finish. The issue occurs at [_detect_client_auth_requirement_with_tls_1_3 ](https://github.com/nabla-c0d3/sslyze/blob/fccf7f9dd49178d0dae5e41599d4e13de64896d3/sslyze/server_connectivity.py#L111-L115) under check_connectivity_to_server during the [ssl_connection_auth.ssl_client.read(1)](https://github.com/nabla-c0d3/sslyze/blob/fccf7f9dd49178d0dae5e41599d4e13de64896d3/sslyze/server_connectivity.py#L346) step. The client throws an IOError [here](https://github.com/nabla-c0d3/nassl/blob/5d272b45bddec50ae56b8b8de73e1d8db482e72f/nassl/ssl_client.py#L240-L241) which doesn't get caught.

**Expected behavior**

The error would be caught and shown in the results. 

Looking at [_detect_support_for_tls_1_3](https://github.com/nabla-c0d3/sslyze/blob/fccf7f9dd49178d0dae5e41599d4e13de64896d3/sslyze/server_connectivity.py#L223-L267), this error would be caught under OSError, perhaps this could be added to _detect_client_auth_requirement_with_tls_1_3 as well?

**Python environment (please complete the following information):**

 - OS: Ubuntu 22.04
 - Python version: 3.11.4

**Additional context**

Image of error:

![image](https://github.com/nabla-c0d3/sslyze/assets/47400288/24749d33-5f32-4d0d-9103-685e85f81af3)

**Comment by nabla-c0d3** [comment]
Nice catch! Thanks for the detailed report and PR 👍👍

**Comment by nabla-c0d3** [comment]
Fixed in [v5.2.0](https://github.com/nabla-c0d3/sslyze/releases/tag/5.2.0).
