### ISSUE TITLE
Cannot instantiate default MozillaTlsConfigurationChecker - JSON with definition incorrectly formatted

### ISSUE THREAD

**Issue by Marian-Kechlibar** [nabla-c0d3/sslyze#614]
An attempt to run

`mozilla_checker = MozillaTlsConfigurationChecker.get_default()`

fails with exception thrown by pydantic: "version" parameter in the definition file
`5.6.json `
is required to be a string, but it is in fact a float (5.6).

**Python environment (please complete the following information):**
 - OS: Windows 11
 - Python version: 3.11

If I edit the 5.6 json file and redefine 
`version: 5.6 `
to 
`version: "5.6"`
the bug disappears.

**Comment by nabla-c0d3** [comment]
Fixed in [v5.2.0](https://github.com/nabla-c0d3/sslyze/releases/tag/5.2.0).
