### ISSUE TITLE
Bump upper pydantic requirement

### ISSUE THREAD

**Issue by kazet** [nabla-c0d3/sslyze#624]
There is a new version of pydantic, 2.4.0, but sslyze requires pydantic<2.4.0. Would it be possible to bump this requirement up?

**Comment by yurivict** [comment]
@nabla-c0d3
Any chance to use pydantic2 ?

Thanks,
Yuri

**Comment by nabla-c0d3** [comment]
Fixed in [v6.0.0](https://github.com/nabla-c0d3/sslyze/releases/tag/6.0.0).
