### ISSUE TITLE
"Server rejected the connection" but server is healthy

### ISSUE THREAD

**Issue by joyma** [nabla-c0d3/sslyze#625]
"Server rejected the connection" but the server is healthy

**To Reproduce**
1. Install SSLyze 5.2.0
2. Run the following command 'python -m sslyze --slow_connection vanderpump.co.uk'
3. See error "Server rejected the connection"

Occasionally the certificate information is reported correctly, but the cipher suite tests don't execute with "Server rejected the connection". 

**Expected behavior**
Sslyze should connect to the server and run tests.

**Python environment :**
 - OS:  Ubuntu 22.04, Python version: 3.10
 - OS: OSX 11.7.10, Python 3.8.2

**Additional context**
vanderpump.co.uk server is healthy and browser connects OK. 
OpenSSL -connect works fine.

**Comment by nabla-c0d3** [comment]
Hello,
I just ran `python -m sslyze --slow_connection vanderpump.co.uk` on SSLyze 6.0.0 and it worked.
