### ISSUE TITLE
Plugin request: POODLE TLS

### ISSUE THREAD

**Issue by tecknicaltom** [nabla-c0d3/sslyze#63]
It would be convenient to have sslyze be able to test for the TLS POODLE issue

https://www.imperialviolet.org/2014/12/08/poodleagain.html

**Comment by fabian-z** [comment]
+1
Qualys latest SSL Pulse shows that ~6% of scanned servers were vulnerable to POODLE over TLS.

Example test implementation in Python can be found here:
http://www.exploresecurity.com/testing-for-poodle_tls-manually/

The author mentions that testing for this would require a patched version of openssl, so I suspect that changes to nassl are needed for this Plugin.

**Comment by AshleyPoole** [comment]
I'd like to see this too! Along with a new field showing if the server is vulnerable or not.

**Comment by feralfenrir** [comment]
+1 I'd love to see this and BEAST checks

**Comment by nottheend** [comment]
+1 I would also be happy if this would be available in sslyze

**Comment by nabla-c0d3** [comment]
TLS 1.0 is now outdated anyway, so I don't see a lot of value in writing the Poodle TLS check now.
