### ISSUE TITLE
Add support for Python 3.12

### ISSUE THREAD

**Issue by VKOPd** [nabla-c0d3/sslyze#630]
Does not install under Python 3.12 per the directions on https://github.com/nabla-c0d3/sslyze -- at least on Win 11.

The directions do work under Python 3.11 which I also have.

**Comment by jduprat** [comment]
Same issue on Fedora 39 which comes with Python 3.12.

**Comment by nabla-c0d3** [comment]
Fixed in [v6.0.0](https://github.com/nabla-c0d3/sslyze/releases/tag/6.0.0).

**Comment by Ansl55555** [comment]
> Gleiches Problem auf Fedora 39, das mit Python 3.12. geliefert wird.ucker F
