### ISSUE TITLE
Please support pydantic-2.5.3

### ISSUE THREAD

**Issue by yurivict** [nabla-c0d3/sslyze#631]
**Describe the bug**
[here](https://github.com/nabla-c0d3/sslyze/blob/release/setup.py#L104)

PYPI now has pydantic at 2.5.3 and having two versions of Pydantic at the same time causes conflicts in resolving dependencies for some other packages, because pydantic-1.x and pydantic-2.x use the same namespace 'pydantic'.

**Comment by nabla-c0d3** [comment]
Closing this as a duplicate of #624
