### ISSUE TITLE
Scan hangs forever when "invalid padding" error occurs

### ISSUE THREAD

**Issue by FestiveKyle** [nabla-c0d3/sslyze#632]
**Describe the bug**

If an OpenSSLError is raised for `invalid padding`, the scan hangs forever. There is an `illegal padding` in the `_HANDSHAKE_REJECTED_TLS_ERRORS`, but not a `invalid padding`.

**Expected behavior**

The error should be caught.

**Python environment (please complete the following information):**

- OS: Ubuntu 22.04
- Python version: 3.10.12

**Additional context**

Image of error:
![image](https://github.com/nabla-c0d3/sslyze/assets/47400288/b12bf319-4e40-47c4-acaa-c6ccba9cfc04)

**Comment by nabla-c0d3** [comment]
Thanks for the fix 👍😀

**Comment by nabla-c0d3** [comment]
Fixed in [v6.0.0](https://github.com/nabla-c0d3/sslyze/releases/tag/6.0.0).
