### ISSUE TITLE
CLI parameter negation

### ISSUE THREAD

**Issue by ITaluone** [nabla-c0d3/sslyze#637]
**Is your feature request related to a problem? Please describe.**
We do not support TLS1.3 on our servers, because of technical reasons. Now, when I run an SSL test for a domain on this server the test "fails" due to incompliant TLS1.3, but everything else is fine..

**Describe the solution you'd like**
It would be cool if I could run an SSL test like this: `docker run --rm -it **nablac0d3/sslyze:latest --!tlsv1_3` (note the `!` in the paramter) which runs everything but the TLS1.3 test.

**Describe alternatives you've considered**
I know, I could do this by manually enabling all but this parameter; just seems inconvenient...

**Comment by nabla-c0d3** [comment]
Hello, as you mentioned you could do this manually... I am trying to keep the command line options as simple as possible and adding some logic to support what you proposed would make it very complex, so I will not implement it. Good luck!
