### ISSUE TITLE
Please Add to the 5.1.3 Release Notes That It Is the Last Version to Support Windows 7

### ISSUE THREAD

**Issue by griesimatt1** [nabla-c0d3/sslyze#640]
The 5.2.0 Windows version of SSLYZE uses a Python version incompatible with Windows 7.

Users will get the error: "api-ms-win-core-path-l1-1-1.ddl is missing"

If possible, please add a bullet point to the 5.1.3 Release Notes indicating that it is the last version to support Windows 7.

Alternatively, on the 5.2.0 Release Notes, add a bullet point indicating that support for Windows 7 has been dropped due to an incompatible Python version.

**Comment by nabla-c0d3** [comment]
Hello,
Thanks for letting me know 👍. I've added a bullet point to the 5.1.3 release notes.
