### ISSUE TITLE
Please bump cryptography requirement upper bound as there are known vulnerabilities in cryptography <42

### ISSUE THREAD

**Issue by kazet** [nabla-c0d3/sslyze#641]
**Describe the bug**
Please bump cryptography requirement upper bound as there are known vulnerabilities in cryptography <42, e.g. https://github.com/advisories/GHSA-3ww4-gg4f-jr7f

**Comment by nabla-c0d3** [comment]
Implemented as part of #638

**Comment by nabla-c0d3** [comment]
Fixed in [v6.0.0](https://github.com/nabla-c0d3/sslyze/releases/tag/6.0.0).
