### ISSUE TITLE
by default sslyze is now skipping secure header check

### ISSUE THREAD

**Issue by KIT-GregC** [nabla-c0d3/sslyze#645]
**Describe the bug**
The documentation for sslyze describes that "all checks" will be run if you simply pass a target. This used to in include --http_headers .  I must now pass those arguments separately and run two scans
**To Reproduce**
1. Install SSLyze using '...' [e.g. pip, git]
2. Run the following command python3 sslyze -m www.ftd.com
4. Note: no hsts or other header information
5. Run the following command python3 sslyze -m --http_headers www.ftd.com
6. Note: ONLY HSTS information is returned

I believe there used to be a --regular option to run all scans. It is ok not to have that as long as you maintain "umbrella check" operation.

**Expected behavior**
All checks should be run as advertised
**Python environment (please complete the following information):**
 - OS: MacOS Sonoma 14.4.1
 - Python version: 3.11.6

**Additional context**

**Comment by nabla-c0d3** [comment]
You can combine commands, for example: `python -m sslyze --mozilla_config=intermediate --http_headers  www.google.com`

**Comment by nabla-c0d3** [comment]
Will be fixed by https://github.com/nabla-c0d3/sslyze/issues/683
