### ISSUE TITLE
[question] Does sslyze support OpenSSL 3.0+?

### ISSUE THREAD

**Issue by yurivict** [nabla-c0d3/sslyze#650]
The FreeBSD port security/py-sslyze was removed last month because sslyze-5.2.0 didn't support OpenSSL 3.0+

Does version 6.0 support OpenSSL 3.0+ ?

Thanks,
Yuri

**Comment by nabla-c0d3** [comment]
Hello,
OpenSSL 3.x is not supported yet : https://github.com/nabla-c0d3/nassl/issues/114
