### ISSUE TITLE
Map the OpenSSL cipher suite names to their RFC names

### ISSUE THREAD

**Issue by postmodern** [nabla-c0d3/sslyze#66]
It would be useful if the XML included the RFC cipher suite name. https://testssl.sh/openssl-rfc.mappping.html

**Comment by nabla-c0d3** [comment]
Agreed, will look into it

**Comment by postmodern** [comment]
Here's the [translation table](https://github.com/trailofbits/ruby-sslyze/blob/082ae07568b90bb56c4dd84131c1a18153219b40/lib/sslyze/cipher_suite.rb#L13-L184) I adapted from [testssl.sh table](https://testssl.sh/openssl-rfc.mappping.html).
