### ISSUE TITLE
JSON output fails for certain domains because of OCSP error

### ISSUE THREAD

**Issue by afreudenreich** [nabla-c0d3/sslyze#663]
**Describe the bug**
For certain domains pydantic throws a validation error "OCSP response status is not successful so the property has no value" when choosing json output. No json output is produced.

**To Reproduce**
1. Run the following command 'sslyze www.apecofa.fr --json_out data/apecofa.out'
2. See error:
3. ...Traceback (most recent call last):
  File "/Users/MyUser/venv/bin/sslyze", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/MyUser/venv/lib/python3.12/site-packages/sslyze/__main__.py", line 79, in main
    server_scan_results=[ServerScanResultAsJson.model_validate(result) for result in all_server_scan_results],
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/MyUser/venv/lib/python3.12/site-packages/pydantic/main.py", line 509, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 6 validation errors for ServerScanResultAsJson
result.certificate_deployments.0.ocsp_response.certificate_status
  Error extracting attribute: ValueError: OCSP response status is not successful so the property has no value [type=get_attribute_error, input_value=<cryptography.hazmat.bind...e object at 0x105436640>, input_type=OCSPResponse]
    For further information visit https://errors.pydantic.dev/2.6/v/get_attribute_error
result.certificate_deployments.0.ocsp_response.revocation_time
  Error extracting attribute: ValueError: OCSP response status is not successful so the property has no value [type=get_attribute_error, input_value=<cryptography.hazmat.bind...e object at 0x105436640>, input_type=OCSPResponse]
    For further information visit https://errors.pydantic.dev/2.6/v/get_attribute_error
result.certificate_deployments.0.ocsp_response.produced_at
  Error extracting attribute: ValueError: OCSP response status is not successful so the property has no value [type=get_attribute_error, input_value=<cryptography.hazmat.bind...e object at 0x105436640>, input_type=OCSPResponse]
    For further information visit https://errors.pydantic.dev/2.6/v/get_attribute_error
result.certificate_deployments.0.ocsp_response.this_update
  Error extracting attribute: ValueError: OCSP response status is not successful so the property has no value [type=get_attribute_error, input_value=<cryptography.hazmat.bind...e object at 0x105436640>, input_type=OCSPResponse]
    For further information visit https://errors.pydantic.dev/2.6/v/get_attribute_error
result.certificate_deployments.0.ocsp_response.next_update
  Error extracting attribute: ValueError: OCSP response status is not successful so the property has no value [type=get_attribute_error, input_value=<cryptography.hazmat.bind...e object at 0x105436640>, input_type=OCSPResponse]
    For further information visit https://errors.pydantic.dev/2.6/v/get_attribute_error
result.certificate_deployments.0.ocsp_response.serial_number
  Error extracting attribute: ValueError: OCSP response status is not successful so the property has no value [type=get_attribute_error, input_value=<cryptography.hazmat.bind...e object at 0x105436640>, input_type=OCSPResponse]
    For further information visit https://errors.pydantic.dev/2.6/v/get_attribute_error

**Expected behavior**
On the console output the OCSP status shows as "ERROR - OCSP response status is not successful: UNAUTHORIZED".
I would expect this error to be caught before creating json and the OCSP response set to something valid, which conforms to json syntax. In the end json output should be produced.

**Python environment (please complete the following information):**
 - OS: macOS Sonoma, RHEL9
 - Python version: 3.12.6

**Additional context**
I am using the ServerScanResultAsJson class for a different purpose and this error is difficult to work around, as it should be caught at a lower level.

**Comment by afreudenreich** [comment]
Hm - just after submitting I noticed there is already an issue for this (#646) so this is a duplicate - but it has been closed and then reopened. Does this mean it has not been fixed yet?
If this is handled by #646/#647 please close.

**Comment by nabla-c0d3** [comment]
Hi! Yes this looks like a duplicate. I will close this one and keep the other issue opened.
