### ISSUE TITLE
The WSL bash exit code is 0, even though an error occurred.

### ISSUE THREAD

**Issue by GitHub-for-Tobias** [nabla-c0d3/sslyze#665]
**Describe the bug**

When running SSLyze in the Ubuntu WSL bash, the exit code is 0 despite encountering an ERROR.

**To Reproduce**
1. Install WSL2 with ubuntu
https://learn.microsoft.com/en-us/windows/wsl/install
https://learn.microsoft.com/en-us/windows/wsl/install-manual
2. Install SSLyze using
# curl -s https://api.github.com/repos/nabla-c0d3/sslyze/releases/latest | grep "browser_download_url.*zip" | cut -d : -f 2,3 | tr -d \" | wget -qi - && unzip -o sslyze-*.zip && rsync -av --remove-source-files sslyze-*/ . && rm -r sslyze-* && chmod +x sslyze.exe
3. Run the following command
**_First Use Case_**
root@xxx:~/scan_tls# ./sslyze.exe unreachable_target

 CHECKING CONNECTIVITY TO SERVER(S)
 ----------------------------------

   unreachable_target:443              => ERROR: Could not resolve hostname unreachable_target; discarding scan.
root@xxx:~/scan_tls# echo $?
0

**_Second Use Case_**
using a bash script
...
   # Run sslyze.exe and redirect both stdout and stderr to the output file
    "$sslyzePath" "$server" > "$outputFile" 2>&1
...
    if [ $? -eq 0 ]; then
        echo "All OK for $server and saved output to $outputFile."
    else
        echo -e "${RED}Warning, Error or Non-Compliance for $server. Check the output file for details: $outputFile.${NC}"
    fi

the output on the console is
"All OK for $server and saved output to $outputFile."
 
the outputFile contains
CHECKING CONNECTIVITY TO SERVER(S)
 ----------------------------------

   yyy:443 => ERROR: Connection to the server timed out; discarding scan.

 SCANS COMPLETED IN 5.19427 S
 ----------------------------

4. See exit code and error

**Expected behavior**
The exit code should be 1.
https://tldp.org/LDP/abs/html/exitcodes.html

**Python environment (please complete the following information):**
 - OS: Windows 11 23H2
 - Python version: 3.12.3
 - SSLyze: 6.0.0

**Additional context**
I did not test this on a real Linux version or other WSLs.

**Comment by GitHub-for-Tobias** [comment]
as a workaround:
# ANSI color code for red text
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check if sslyze.exe executed successfully
    if [ $? -eq 0 ]; then
        # Check if "Error", "Warning", or "Failed" is mentioned in the output file
        if grep -iE "error|warning|failed" "$outputFile"; then
            echo -e "${RED}Warning, Error, or Non-Compliance for $server. Check the output file for details: $outputFile.${NC}"
        else
            echo "All OK for $server and saved output to $outputFile."
        fi
    else
        echo -e "${RED}Warning, Error, or Non-Compliance for $server. Check the output file for details: $outputFile.${NC}"
    fi

**Comment by nabla-c0d3** [comment]
A scan that fails for one server doesn't mean that SSLyze did not execute successfully. For example, other scans might have succeeded and hence, the results returned by SSLyze might be useful. In this situation the exit code should not be 1.

**Comment by GitHub-for-Tobias** [comment]
@nabla-c0d3 
Thank you for your feedback. 

Could you please elaborate on your comment? From my understanding, SSLyze is only being run for a single server at a time, meaning that exit code 0 is not particularly useful in this case.

For example, when running the following command:

```
# ./sslyze.exe unreachable_target
```

The result pertains solely to that specific server, correct?

When using SSLyze in a CI/CD pipeline, it would be beneficial to receive an error exit code if the server is unreachable.

I propose introducing custom exit codes in the range of 64-113 (in addition to 0 for success) to make debugging easier. For instance:
- 64 ERROR: Connection to the server timed out; discarding scan.

This would improve clarity when diagnosing issues.
