### ISSUE TITLE
why maximum_certificate_lifespan 366 days ?

### ISSUE THREAD

**Issue by dgisec** [nabla-c0d3/sslyze#669]
I would to know why do you require a maximum_certificate_lifespan 366 days ?

The max seems 397 days;
https://www.tenable.com/plugins/was/112563
https://blog.mozilla.org/security/2020/07/09/reducing-tls-certificate-lifespans-to-398-days/
https://thehackernews.com/2020/09/ssl-tls-certificate-validity-398.html

I understand the shortest is the best and google tries to reduce to 90 days:
On March 3, 2023, Google's Chromium Projects announced that the organization plans to reduce the maximum validity period for public Transport Layer Security (TLS) certificates from 398 days to 90 days.

But 366 should be compliant with the current recommendation

**Comment by janbrasna** [comment]
This is to match https://wiki.mozilla.org/Security/Server_Side_TLS:

https://github.com/nabla-c0d3/sslyze/blob/761892bf6a613726f272eb4e19b33faee2272b6f/sslyze/mozilla_tls_profile/5.7.json#L84-L87

(only `modern` sets both to 90)

**Comment by nabla-c0d3** [comment]
Correct 👍- this is what is configured in Mozilla's TLS profile.
