### ISSUE TITLE
Mozilla Trust Store: unable to get local issuer certificate

### ISSUE THREAD

**Issue by fishouttah20** [nabla-c0d3/sslyze#69]
In the latest sslyze version, The report for www.onlineabs.barclays.co.uk shows the cert is trusted in all cert stores except for Mozilla NSS CA Store (04/2015) which indicates "FAILED - Certificate is NOT Trusted: unable to get local issuer certificate"

I've pulled up the website in firefox on windows and linux just to be sure and see no cert issues within firefox itself. Any ideas?

**Comment by nabla-c0d3** [comment]
Same result when using OpenSSL directly:

    $ openssl s_client -connect  www.onlineabs.barclays.co.uk:443 -CAfile plugins/data/trust_stores/mozilla.pem -verify 5
    verify depth is 5
    CONNECTED(00000003)
    depth=2 /C=US/O=VeriSign, Inc./OU=VeriSign Trust Network/OU=(c) 2006 VeriSign, Inc. - For authorized use only/CN=VeriSign Class 3 Public Primary Certification Authority - G5
    verify error:num=20:unable to get local issuer certificate
    verify return:1
    depth=2 /C=US/O=VeriSign, Inc./OU=VeriSign Trust Network/OU=(c) 2006 VeriSign, Inc. - For authorized use only/CN=VeriSign Class 3 Public Primary Certification Authority - G5
    verify error:num=27:certificate not trusted
    verify return:1
    depth=1 /C=US/O=Symantec Corporation/OU=Symantec Trust Network/CN=Symantec Class 3 EV SSL SGC CA - G2
    verify return:1
    depth=0 /1.3.6.1.4.1.311.60.2.1.3=GB/businessCategory=Private Organization/serialNumber=01026167/C=GB/postalCode=E14 5HP/ST=London/L=London/street=1 Churchill Place/O=Barclays Bank PLC/OU=Web and Infrastructure Service EXGL-LI06 SHA1
    verify return:1

My guess is that it has to do with this: https://community.qualys.com/thread/14754. Basically it sounds like "VeriSign Class 3 Public Primary Certification Authority - G5" should not be sent by the server (but removing it from the chain might break the website for older clients?).
