### ISSUE TITLE
"undefined symbol: inflate" from version 0.11

### ISSUE THREAD

**Issue by abtreece** [nabla-c0d3/sslyze#70]
no issues running 0.10, but when i attempt to run 0.11 i get the following...

> /sslyze/nassl/_nassl.so: undefined symbol: inflate
> ERROR: Could not import nassl Python module. Did you clone SSLyze's repo ?
> Please download the right pre-compiled package as described in the README.

I am using the pre-compiled 64bit linux version for both.

**Comment by thomai** [comment]
Do you use the compatible nassl release for sslyze 0.11?
https://github.com/nabla-c0d3/nassl/releases/tag/v0.11

**Comment by abtreece** [comment]
is the compatible nassl version not included with the version release?

**Comment by thomai** [comment]
Yes, that's right. I don't use the pre-compiled versions ;-)
The readme file says:
> The pre-compiled packages for SSLyze contain a compiled version of this wrapper in sslyze/nassl. If you want to clone the SSLyze repo, you will have to get a compiled version of nassl from one of the SSLyze packages and copy it to sslyze-master/nassl, in order to get SSLyze to run.

**Comment by nabla-c0d3** [comment]
Which Linux distro and version are you using ? I've tested the pre-compiled packages on Debian 7 only.

**Comment by abtreece** [comment]
RHEL 6.5 (and variants)... l0.10 works w/out issue. 0.11 is the one i'm having issues with.

**Comment by nabla-c0d3** [comment]
I just fixed this in nassl (https://github.com/nabla-c0d3/nassl/commit/5c0a57bc831c93d8e9e43f93f5bbe6a32f606623) and uploaded new packages in the release page for 0.11.
Please re-download the Linux packages, they should work fine now.

**Comment by abtreece** [comment]
confirmed. thanks!

**Comment by ashleyblackmore** [comment]
Same story here, downloaded the latest packages today:
```
(env) ~/Downloads/sslyze-0_11-linux64/sslyze 
15:08 $ python sslyze.py www.example.com
  File "sslyze.py", line 38
    print str(e) + '\nERROR: Could not import nassl Python module. Did you clone SSLyze\'s repo ? \n' +\
            ^
SyntaxError: invalid syntax
```
