### ISSUE TITLE
Ssylze Version 0.11 --chrome_sha1 bug

### ISSUE THREAD

**Issue by laurarosenberg** [nabla-c0d3/sslyze#73]
The option "--chrome_sha1" doesn't work in version 0.11. I am using Python 2.7.6 and sslyze 0.10 works perfect for --chrome_sha1, but for 0.11 it get a exception.

**Comment by nabla-c0d3** [comment]
What exception are you getting ? Seems to be working fine on my side.

**Comment by laurarosenberg** [comment]
hi! ok, I am not sure if that is my problem or yours :/ I am calling sslyze
as a subprocess from my script
 output = subprocess.check_output(['python', './sslyze/sslyze.py',
'--chrome_sha1', line])

and geht following exception
Unhandled exception when processing --chrome_sha1:
exceptions.TypeError - Incorrect padding

that only happens for the version 0.11, for 0.10 it works perfect!
if I use --regular or --heartbleed or any other options in 0.11 as
subprocess in my script it works fine, only the --chrome_sha1 didn't work
correct?

2015-05-09 21:55 GMT+02:00 Alban Diquet <notifications@github.com>:

**Comment by laurarosenberg** [comment]
ok, I recognized that if I use --chrome_sha1 with IPv4 it doesn't work out
and with IPv6 it works well ??? I try to analyze where the problem is - and
I am not sure, maybe the path for morzilla?

2015-05-11 11:45 GMT+02:00 Laura Luisa Rosenberg <
rosenberg.laura.luisa@googlemail.com>:

**Comment by laurarosenberg** [comment]
I get the following exception: 
Unhandled exception when processing --chrome_sha1:
exceptions.TypeError - Incorrect padding

please check your mozilla.pm file in version 0.11 - there are titles between the certificates - this cause the exception.

example:

**Equifax Secure CA
=================**
-----BEGIN CERTIFICATE-----
MIIDIDCCAomgAwIBAgIENd70zzANBgkqhkiG9w0BAQUFADBOMQswCQYDVQQGEwJVUzEQMA4GA1UE
ChMHRXF1aWZheDEtMCsGA1UECxMkRXF1aWZheCBTZWN1cmUgQ2VydGlmaWNhdGUgQXV0aG9yaXR5
MB4XDTk4MDgyMjE2NDE1MVoXDTE4MDgyMjE2NDE1MVowTjELMAkGA1UEBhMCVVMxEDAOBgNVBAoT
B0VxdWlmYXgxLTArBgNVBAsTJEVxdWlmYXggU2VjdXJlIENlcnRpZmljYXRlIEF1dGhvcml0eTCB
nzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEAwV2xWGcIYu6gmi0fCG2RFGiYCh7+2gRvE4RiIcPR
fM6fBeC4AfBONOziipUEZKzxa1NfBbPLZ4C/QgKO/t0BCezhABRP/PvwDN1Dulsr4R+AcJkVV5MW
8Q+XarfCaCMczE1ZMKxRHjuvK9buY0V7xdlfUNLjUA86iOe/FP3gx7kCAwEAAaOCAQkwggEFMHAG
A1UdHwRpMGcwZaBjoGGkXzBdMQswCQYDVQQGEwJVUzEQMA4GA1UEChMHRXF1aWZheDEtMCsGA1UE
CxMkRXF1aWZheCBTZWN1cmUgQ2VydGlmaWNhdGUgQXV0aG9yaXR5MQ0wCwYDVQQDEwRDUkwxMBoG
A1UdEAQTMBGBDzIwMTgwODIyMTY0MTUxWjALBgNVHQ8EBAMCAQYwHwYDVR0jBBgwFoAUSOZo+SvS
spXXR9gjIBBPM5iQn9QwHQYDVR0OBBYEFEjmaPkr0rKV10fYIyAQTzOYkJ/UMAwGA1UdEwQFMAMB
Af8wGgYJKoZIhvZ9B0EABA0wCxsFVjMuMGMDAgbAMA0GCSqGSIb3DQEBBQUAA4GBAFjOKer89961
zgK5F7WF0bnj4JXMJTENAKaSbn+2kmOeUJXRmm/kEd5jhW6Y7qj/WsjTVbJmcVfewCHrPSqnI0kB
BIZCe/zuf6IWUrVnZ9NA2zsmWLIodz2uFHdh1voqZiegDfqnc1zqcPGUIWVEX/r87yloqaKHee95
70+sB3c4
-----END CERTIFICATE-----
