### ISSUE TITLE
Precompiled packages not importing nassl

### ISSUE THREAD

**Issue by ashleyblackmore** [nabla-c0d3/sslyze#74]
Same story as [here](https://github.com/nabla-c0d3/sslyze/issues/70), downloaded the latest packages (today):

```
(env) ~/Downloads/sslyze-0_11-linux64/sslyze 
15:08 $ python sslyze.py www.example.com
  File "sslyze.py", line 38
    print str(e) + '\nERROR: Could not import nassl Python module. Did you clone SSLyze\'s repo ? \n' +\
            ^
SyntaxError: invalid syntax
https://github.com/nabla-c0d3/sslyze/releases/download/release-0.11/sslyze-0_11-linux64.zip
```
```
sha1sum - 45c6fe9eb53d6226e117a92d437fd2f31fbfe705 sslyze-0_11-linux64.zip
```

Any ideas what I might be doing wrong? Cheers!

**Comment by nabla-c0d3** [comment]
Which Linux distro are you using? I'm unable to reproduce this.

**Comment by ashleyblackmore** [comment]
Ubuntu 15.04

**Comment by nabla-c0d3** [comment]
Just ran SSLyze 0.11 on Ubuntu 15.04, no issues...

    $ uname -a
    Linux ubuntu15 3.19.0-15-generic #15-Ubuntu SMP Thu Apr 16 23:32:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
    $ python --version
    Python 2.7.9

**Comment by ashleyblackmore** [comment]
Yeah seems to be fixed, likely pebkac somehow. Thanks.
