### ISSUE TITLE
XML output to console / stdout

### ISSUE THREAD

**Issue by AshleyPoole** [nabla-c0d3/sslyze#78]
I like the ability to output in an xml format but would it be possible to output the xml to the console / stdout instead of to file?

**Comment by nabla-c0d3** [comment]
I can add something like "--xm_out -" for outputting to stdout

**Comment by AshleyPoole** [comment]
That would be cool.

**Comment by konklone** [comment]
This would be very helpful. I'm integrating `sslyze` into a domain scanning tool which has its own methods for taking output from STDOUT and writing the output to predictable directories, creating directories automatically when need be, etc. It's inconvenient to have `sslyze` do that work internally, without any hooks to manage persistence.

**Comment by konklone** [comment]
Thank you!
