### ISSUE TITLE
Selectable output type

### ISSUE THREAD

**Issue by AshleyPoole** [nabla-c0d3/sslyze#79]
Would it be possible to select between JSON or XML as the output type to enable better integration with external consumers?

**Comment by RedTechie** [comment]
+1 ! 

I too would love this capability! I had to wrote a tool that parses the XML and converts it to a C# object then from that into JSON via WebAPI. It would be great to just pass the exact JSON output from the tool removing the need for the extra computation!

**Comment by nabla-c0d3** [comment]
Yes - this is next on my list. It will be pretty easy now that all the results are basically Python dictionaries (since v0.13).
