### ISSUE TITLE
sslyze 0.11 fails to handle OCSP responses

### ISSUE THREAD

**Issue by postmodern** [nabla-c0d3/sslyze#81]
After upgrading to sslyze 0.11, I noticed that `ocspResponses` disappeared from the XML output. I discovered this error:

    <target host="yahoo.com" ip="98.138.253.109" port="443">
      <certinfo exception="_nassl.OpenSSLError - error:27069065:OCSP routines:OCSP_basic_verify:certificate verify error" title="PluginCertInfo"/>

**Comment by nabla-c0d3** [comment]
This was because yahoo's ocsp response doesn't seem to be trusted by SSLyze... this might be another bug but at least the XML output is back.
