### ISSUE TITLE
SSLyze - wrong xml tag for certificate

### ISSUE THREAD

**Issue by glestel** [nabla-c0d3/sslyze#82]
Hello

When using xml output sometimes a tag for the certificate extension is malformed. The extract of the xml is:
```xml
<X509v3KeyUsage>
      <CRLSign />
      <CertificateSign />
   </X509v3KeyUsage>
   <oid-1.3.6.1.5.5.7.1.12>
      <Not Supported>
   </oid-1.3.6.1.5.5.7.1.12>
   <X509v3CertificatePolicies>
      <Policy>
         <listEntry>X509v3 Any Policy</listEntry>
      </Policy>
      <CPS>
         <listEntry>https://www.verisign.com/cps</listEntry>
      </CPS>
   </X509v3CertificatePolicies>
```

This happen with sslyze v 0.11 and also previous version

**Comment by janderse** [comment]
Is it just the Not Supported tag?  Are there other problems?

**Comment by glestel** [comment]
Yes it's the ``Not Supported`` tag, it's not a valid xml one and some parser won't process it (fortunately not python).
No other problem to report.

**Comment by nabla-c0d3** [comment]
Sure - I'll remove the white spaces.

**Comment by janderse** [comment]
Technically it should be <Not supported/> right, since there is no closing
tag?

**Comment by janderse** [comment]
Ugh, autocorrect:
<NotSupported/>

On May 18, 2015 8:40 AM, "Jon Andersen" <janderse@gmail.com> wrote:
>
> Technically it should be <Not supported/> right, since there is no
closing tag?
>

**Comment by nabla-c0d3** [comment]
Actually this is what I'm seeing in 0.11:

    <oid-1.3.6.1.5.5.7.1.12>&lt;Not Supported&gt;</oid-1.3.6.1.5.5.7.1.12>

While not very pretty, this is valid XML as "&lt;Not Supported&gt;" is actually not an XML node but just a value (which is properly XML-escaped). Closing this as it doesn't seem to be an issue; please re-open if I missed something.
Thanks,

**Comment by glestel** [comment]
Indeed this explains why python was able to parse the xml. This happened when I displayed the xml with firefox, once I copy/paste the xml the escaping is lost. 
I think dropping the "&lt; &gt;" would makes things less error-prone.
Thanks for the explanation.
