### ISSUE TITLE
Include "Logjam Attack" warning

### ISSUE THREAD

**Issue by shakalandy** [nabla-c0d3/sslyze#83]
please include logjam warning in addition to Heartbleed & co.
Infos: https://weakdh.org/

**Comment by nabla-c0d3** [comment]
This is already detected by SSLyze as it will show the length of the DH parameters for each supported cipher suite.

**Comment by memoryoverride** [comment]
however sslyze does not show if the DH group is commonly used one, like the test on https://weakdh.org/sysadmin.html does

or did I miss something?

**Comment by nabla-c0d3** [comment]
Yeah that's correct, but it is safer to assume that any DH group below 2048 bits can be broken:

"We further estimate that an academic team can break a 768-bit prime and that a nation-state can break a 1024-bit prime. " - https://weakdh.org/
