### ISSUE TITLE
please add detection for filtered STARTTLS commands

### ISSUE THREAD

**Issue by ka7** [nabla-c0d3/sslyze#84]
...as discussed here:
https://stomp.colorado.edu/blog/blog/2012/12/31/on-smtp-starttls-and-the-cisco-asa/

guess how has a hosting provider with such an "(un)security enhancement"

**Comment by nabla-c0d3** [comment]
Hi,
This is too specific to one vendor (Cisco), and it can already be identified with SSLyze as the tool will return an error when trying to negotiate StartTLS if there's a device that's disabling StartTLS.
