### ISSUE TITLE
scanning cipher suites for disabled TLS versions results in timeouts

### ISSUE THREAD

**Issue by lostgravity** [nabla-c0d3/sslyze#85]
Apache 2.2.15 on CentOS 6 with OpenSSL 1.0.1e-fips has SSLv2, SSLv3, TLSv1, and TLSv1_1 disabled. Using sslyze 0.11.0, Python 2.7.3.

As expected, SSL cipher suites all get reported as rejected with "TLS / No ciphers available" or "TLS / Alert handshake failure". But, while some TLS cipher suites get reported as rejected with "TLS / No ciphers available" as well, others get reported as "Undefined - An unexpected error happened" with "timeout - timed out". Are the timeouts by design?

<pre>
sslyze.py --sslv3 --tlsv1_1 server.name

 AVAILABLE PLUGINS
 -----------------

  PluginCompression
  PluginSessionRenegotiation
  PluginOpenSSLCipherSuites
  PluginHeartbleed
  PluginHSTS
  PluginCertInfo
  PluginChromeSha1Deprecation
  PluginSessionResumption

 CHECKING HOST(S) AVAILABILITY
 -----------------------------

   server.name:443      => 10.x.x.x:443

 SCAN RESULTS FOR SERVER.NAME:443 - 10.x.x.x:443
 ----------------------------------------------------------------

  * TLSV1_1 Cipher Suites:
      Undefined - An unexpected error happened: 
                 SEED-SHA                            timeout - timed out                
                 RC4-SHA                             timeout - timed out                
                 RC4-MD5                             timeout - timed out                
                 NULL-SHA                            timeout - timed out                
                 NULL-MD5                            timeout - timed out                
                 IDEA-CBC-SHA                        timeout - timed out                
                 EXP-RC4-MD5                         timeout - timed out                
                 EXP-RC2-CBC-MD5                     timeout - timed out                
                 EXP-EDH-RSA-DES-CBC-SHA             timeout - timed out                
                 EXP-EDH-DSS-DES-CBC-SHA             timeout - timed out                
                 EXP-DH-RSA-DES-CBC-SHA              timeout - timed out                
                 EXP-DH-DSS-DES-CBC-SHA              timeout - timed out                
                 EXP-DES-CBC-SHA                     timeout - timed out                
                 EXP-ADH-RC4-MD5                     timeout - timed out                
                 EXP-ADH-DES-CBC-SHA                 timeout - timed out                
                 EDH-RSA-DES-CBC3-SHA                timeout - timed out                
                 EDH-RSA-DES-CBC-SHA                 timeout - timed out                
                 EDH-DSS-DES-CBC3-SHA                timeout - timed out                
                 EDH-DSS-DES-CBC-SHA                 timeout - timed out                
                 ECDHE-RSA-RC4-SHA                   timeout - timed out                
                 ECDHE-RSA-NULL-SHA                  timeout - timed out                
                 ECDHE-RSA-DES-CBC3-SHA              timeout - timed out                
                 ECDHE-RSA-AES256-SHA                timeout - timed out                
                 ECDHE-RSA-AES128-SHA                timeout - timed out                
                 ECDHE-ECDSA-RC4-SHA                 timeout - timed out                
                 ECDHE-ECDSA-NULL-SHA                timeout - timed out                
                 ECDHE-ECDSA-DES-CBC3-SHA            timeout - timed out                
                 ECDHE-ECDSA-AES256-SHA              timeout - timed out                
                 ECDHE-ECDSA-AES128-SHA              timeout - timed out                
                 ECDH-RSA-RC4-SHA                    timeout - timed out                
                 ECDH-RSA-NULL-SHA                   timeout - timed out                
                 ECDH-RSA-DES-CBC3-SHA               timeout - timed out                
                 ECDH-RSA-AES256-SHA                 timeout - timed out                
                 ECDH-RSA-AES128-SHA                 timeout - timed out                
                 ECDH-ECDSA-RC4-SHA                  timeout - timed out                
                 ECDH-ECDSA-NULL-SHA                 timeout - timed out                
                 ECDH-ECDSA-DES-CBC3-SHA             timeout - timed out                
                 ECDH-ECDSA-AES256-SHA               timeout - timed out                
                 ECDH-ECDSA-AES128-SHA               timeout - timed out                
                 DHE-RSA-SEED-SHA                    timeout - timed out                
                 DHE-RSA-CAMELLIA256-SHA             timeout - timed out                
                 DHE-RSA-CAMELLIA128-SHA             timeout - timed out                
                 DHE-RSA-AES256-SHA                  timeout - timed out                
                 DHE-RSA-AES128-SHA                  timeout - timed out                
                 DHE-DSS-SEED-SHA                    timeout - timed out                
                 DHE-DSS-CAMELLIA256-SHA             timeout - timed out                
                 DHE-DSS-CAMELLIA128-SHA             timeout - timed out                
                 DHE-DSS-AES256-SHA                  timeout - timed out                
                 DHE-DSS-AES128-SHA                  timeout - timed out                
                 DH-RSA-SEED-SHA                     timeout - timed out                
                 DH-RSA-DES-CBC3-SHA                 timeout - timed out                
                 DH-RSA-DES-CBC-SHA                  timeout - timed out                
                 DH-RSA-CAMELLIA256-SHA              timeout - timed out                
                 DH-RSA-CAMELLIA128-SHA              timeout - timed out                
                 DH-RSA-AES256-SHA                   timeout - timed out                
                 DH-RSA-AES128-SHA                   timeout - timed out                
                 DH-DSS-SEED-SHA                     timeout - timed out                
                 DH-DSS-DES-CBC3-SHA                 timeout - timed out                
                 DH-DSS-DES-CBC-SHA                  timeout - timed out                
                 DH-DSS-CAMELLIA256-SHA              timeout - timed out                
                 DH-DSS-CAMELLIA128-SHA              timeout - timed out                
                 DH-DSS-AES256-SHA                   timeout - timed out                
                 DH-DSS-AES128-SHA                   timeout - timed out                
                 DES-CBC3-SHA                        timeout - timed out                
                 DES-CBC-SHA                         timeout - timed out                
                 CAMELLIA256-SHA                     timeout - timed out                
                 CAMELLIA128-SHA                     timeout - timed out                
                 AES256-SHA                          timeout - timed out                
                 AES128-SHA                          timeout - timed out                
                 AECDH-RC4-SHA                       timeout - timed out                
                 AECDH-NULL-SHA                      timeout - timed out                
                 AECDH-DES-CBC3-SHA                  timeout - timed out                
                 AECDH-AES256-SHA                    timeout - timed out                
                 AECDH-AES128-SHA                    timeout - timed out                
                 ADH-SEED-SHA                        timeout - timed out                
                 ADH-RC4-MD5                         timeout - timed out                
                 ADH-DES-CBC3-SHA                    timeout - timed out                
                 ADH-DES-CBC-SHA                     timeout - timed out                
                 ADH-CAMELLIA256-SHA                 timeout - timed out                
                 ADH-CAMELLIA128-SHA                 timeout - timed out                
                 ADH-AES256-SHA                      timeout - timed out                
                 ADH-AES128-SHA                      timeout - timed out                
      Rejected:                        
                 SRP-RSA-AES-256-CBC-SHA             TLS / No ciphers available         
                 SRP-RSA-AES-128-CBC-SHA             TLS / No ciphers available         
                 SRP-RSA-3DES-EDE-CBC-SHA            TLS / No ciphers available         
                 SRP-DSS-AES-256-CBC-SHA             TLS / No ciphers available         
                 SRP-DSS-AES-128-CBC-SHA             TLS / No ciphers available         
                 SRP-DSS-3DES-EDE-CBC-SHA            TLS / No ciphers available         
                 SRP-AES-256-CBC-SHA                 TLS / No ciphers available         
                 SRP-AES-128-CBC-SHA                 TLS / No ciphers available         
                 SRP-3DES-EDE-CBC-SHA                TLS / No ciphers available         
                 PSK-RC4-SHA                         TLS / No ciphers available         
                 PSK-AES256-CBC-SHA                  TLS / No ciphers available         
                 PSK-AES128-CBC-SHA                  TLS / No ciphers available         
                 PSK-3DES-EDE-CBC-SHA                TLS / No ciphers available         
                 NULL-SHA256                         TLS / No ciphers available         
                 ECDHE-RSA-AES256-SHA384             TLS / No ciphers available         
                 ECDHE-RSA-AES256-GCM-SHA384         TLS / No ciphers available         
                 ECDHE-RSA-AES128-SHA256             TLS / No ciphers available         
                 ECDHE-RSA-AES128-GCM-SHA256         TLS / No ciphers available         
                 ECDHE-ECDSA-AES256-SHA384           TLS / No ciphers available         
                 ECDHE-ECDSA-AES256-GCM-SHA384       TLS / No ciphers available         
                 ECDHE-ECDSA-AES128-SHA256           TLS / No ciphers available         
                 ECDHE-ECDSA-AES128-GCM-SHA256       TLS / No ciphers available         
                 ECDH-RSA-AES256-SHA384              TLS / No ciphers available         
                 ECDH-RSA-AES256-GCM-SHA384          TLS / No ciphers available         
                 ECDH-RSA-AES128-SHA256              TLS / No ciphers available         
                 ECDH-RSA-AES128-GCM-SHA256          TLS / No ciphers available         
                 ECDH-ECDSA-AES256-SHA384            TLS / No ciphers available         
                 ECDH-ECDSA-AES256-GCM-SHA384        TLS / No ciphers available         
                 ECDH-ECDSA-AES128-SHA256            TLS / No ciphers available         
                 ECDH-ECDSA-AES128-GCM-SHA256        TLS / No ciphers available         
                 DHE-RSA-AES256-SHA256               TLS / No ciphers available         
                 DHE-RSA-AES256-GCM-SHA384           TLS / No ciphers available         
                 DHE-RSA-AES128-SHA256               TLS / No ciphers available         
                 DHE-RSA-AES128-GCM-SHA256           TLS / No ciphers available         
                 DHE-DSS-AES256-SHA256               TLS / No ciphers available         
                 DHE-DSS-AES256-GCM-SHA384           TLS / No ciphers available         
                 DHE-DSS-AES128-SHA256               TLS / No ciphers available         
                 DHE-DSS-AES128-GCM-SHA256           TLS / No ciphers available         
                 DH-RSA-AES256-SHA256                TLS / No ciphers available         
                 DH-RSA-AES256-GCM-SHA384            TLS / No ciphers available         
                 DH-RSA-AES128-SHA256                TLS / No ciphers available         
                 DH-RSA-AES128-GCM-SHA256            TLS / No ciphers available         
                 DH-DSS-AES256-SHA256                TLS / No ciphers available         
                 DH-DSS-AES256-GCM-SHA384            TLS / No ciphers available         
                 DH-DSS-AES128-SHA256                TLS / No ciphers available         
                 DH-DSS-AES128-GCM-SHA256            TLS / No ciphers available         
                 AES256-SHA256                       TLS / No ciphers available         
                 AES256-GCM-SHA384                   TLS / No ciphers available         
                 AES128-SHA256                       TLS / No ciphers available         
                 AES128-GCM-SHA256                   TLS / No ciphers available         
                 ADH-AES256-SHA256                   TLS / No ciphers available         
                 ADH-AES256-GCM-SHA384               TLS / No ciphers available         
                 ADH-AES128-SHA256                   TLS / No ciphers available         
                 ADH-AES128-GCM-SHA256               TLS / No ciphers available         

  * SSLV3 Cipher Suites:
      Rejected:                        
                 SRP-RSA-AES-256-CBC-SHA             TLS / No ciphers available         
                 SRP-RSA-AES-128-CBC-SHA             TLS / No ciphers available         
                 SRP-RSA-3DES-EDE-CBC-SHA            TLS / No ciphers available         
                 SRP-DSS-AES-256-CBC-SHA             TLS / No ciphers available         
                 SRP-DSS-AES-128-CBC-SHA             TLS / No ciphers available         
                 SRP-DSS-3DES-EDE-CBC-SHA            TLS / No ciphers available         
                 SRP-AES-256-CBC-SHA                 TLS / No ciphers available         
                 SRP-AES-128-CBC-SHA                 TLS / No ciphers available         
                 SRP-3DES-EDE-CBC-SHA                TLS / No ciphers available         
                 PSK-RC4-SHA                         TLS / No ciphers available         
                 PSK-AES256-CBC-SHA                  TLS / No ciphers available         
                 PSK-AES128-CBC-SHA                  TLS / No ciphers available         
                 PSK-3DES-EDE-CBC-SHA                TLS / No ciphers available         
                 NULL-SHA256                         TLS / No ciphers available         
                 ECDHE-RSA-AES256-SHA384             TLS / No ciphers available         
                 ECDHE-RSA-AES256-GCM-SHA384         TLS / No ciphers available         
                 ECDHE-RSA-AES128-SHA256             TLS / No ciphers available         
                 ECDHE-RSA-AES128-GCM-SHA256         TLS / No ciphers available         
                 ECDHE-ECDSA-AES256-SHA384           TLS / No ciphers available         
                 ECDHE-ECDSA-AES256-GCM-SHA384       TLS / No ciphers available         
                 ECDHE-ECDSA-AES128-SHA256           TLS / No ciphers available         
                 ECDHE-ECDSA-AES128-GCM-SHA256       TLS / No ciphers available         
                 ECDH-RSA-AES256-SHA384              TLS / No ciphers available         
                 ECDH-RSA-AES256-GCM-SHA384          TLS / No ciphers available         
                 ECDH-RSA-AES128-SHA256              TLS / No ciphers available         
                 ECDH-RSA-AES128-GCM-SHA256          TLS / No ciphers available         
                 ECDH-ECDSA-AES256-SHA384            TLS / No ciphers available         
                 ECDH-ECDSA-AES256-GCM-SHA384        TLS / No ciphers available         
                 ECDH-ECDSA-AES128-SHA256            TLS / No ciphers available         
                 ECDH-ECDSA-AES128-GCM-SHA256        TLS / No ciphers available         
                 DHE-RSA-AES256-SHA256               TLS / No ciphers available         
                 DHE-RSA-AES256-GCM-SHA384           TLS / No ciphers available         
                 DHE-RSA-AES128-SHA256               TLS / No ciphers available         
                 DHE-RSA-AES128-GCM-SHA256           TLS / No ciphers available         
                 DHE-DSS-AES256-SHA256               TLS / No ciphers available         
                 DHE-DSS-AES256-GCM-SHA384           TLS / No ciphers available         
                 DHE-DSS-AES128-SHA256               TLS / No ciphers available         
                 DHE-DSS-AES128-GCM-SHA256           TLS / No ciphers available         
                 DH-RSA-AES256-SHA256                TLS / No ciphers available         
                 DH-RSA-AES256-GCM-SHA384            TLS / No ciphers available         
                 DH-RSA-AES128-SHA256                TLS / No ciphers available         
                 DH-RSA-AES128-GCM-SHA256            TLS / No ciphers available         
                 DH-DSS-AES256-SHA256                TLS / No ciphers available         
                 DH-DSS-AES256-GCM-SHA384            TLS / No ciphers available         
                 DH-DSS-AES128-SHA256                TLS / No ciphers available         
                 DH-DSS-AES128-GCM-SHA256            TLS / No ciphers available         
                 AES256-SHA256                       TLS / No ciphers available         
                 AES256-GCM-SHA384                   TLS / No ciphers available         
                 AES128-SHA256                       TLS / No ciphers available         
                 AES128-GCM-SHA256                   TLS / No ciphers available         
                 ADH-AES256-SHA256                   TLS / No ciphers available         
                 ADH-AES256-GCM-SHA384               TLS / No ciphers available         
                 ADH-AES128-SHA256                   TLS / No ciphers available         
                 ADH-AES128-GCM-SHA256               TLS / No ciphers available         
                 SEED-SHA                            TLS / Alert handshake failure      
                 RC4-SHA                             TLS / Alert handshake failure      
                 RC4-MD5                             TLS / Alert handshake failure      
                 NULL-SHA                            TLS / Alert handshake failure      
                 NULL-MD5                            TLS / Alert handshake failure      
                 IDEA-CBC-SHA                        TLS / Alert handshake failure      
                 EXP-RC4-MD5                         TLS / Alert handshake failure      
                 EXP-RC2-CBC-MD5                     TLS / Alert handshake failure      
                 EXP-EDH-RSA-DES-CBC-SHA             TLS / Alert handshake failure      
                 EXP-EDH-DSS-DES-CBC-SHA             TLS / Alert handshake failure      
                 EXP-DH-RSA-DES-CBC-SHA              TLS / Alert handshake failure      
                 EXP-DH-DSS-DES-CBC-SHA              TLS / Alert handshake failure      
                 EXP-DES-CBC-SHA                     TLS / Alert handshake failure      
                 EXP-ADH-RC4-MD5                     TLS / Alert handshake failure      
                 EXP-ADH-DES-CBC-SHA                 TLS / Alert handshake failure      
                 EDH-RSA-DES-CBC3-SHA                TLS / Alert handshake failure      
                 EDH-RSA-DES-CBC-SHA                 TLS / Alert handshake failure      
                 EDH-DSS-DES-CBC3-SHA                TLS / Alert handshake failure      
                 EDH-DSS-DES-CBC-SHA                 TLS / Alert handshake failure      
                 ECDHE-RSA-RC4-SHA                   TLS / Alert handshake failure      
                 ECDHE-RSA-NULL-SHA                  TLS / Alert handshake failure      
                 ECDHE-RSA-DES-CBC3-SHA              TLS / Alert handshake failure      
                 ECDHE-RSA-AES256-SHA                TLS / Alert handshake failure      
                 ECDHE-RSA-AES128-SHA                TLS / Alert handshake failure      
                 ECDHE-ECDSA-RC4-SHA                 TLS / Alert handshake failure      
                 ECDHE-ECDSA-NULL-SHA                TLS / Alert handshake failure      
                 ECDHE-ECDSA-DES-CBC3-SHA            TLS / Alert handshake failure      
                 ECDHE-ECDSA-AES256-SHA              TLS / Alert handshake failure      
                 ECDHE-ECDSA-AES128-SHA              TLS / Alert handshake failure      
                 ECDH-RSA-RC4-SHA                    TLS / Alert handshake failure      
                 ECDH-RSA-NULL-SHA                   TLS / Alert handshake failure      
                 ECDH-RSA-DES-CBC3-SHA               TLS / Alert handshake failure      
                 ECDH-RSA-AES256-SHA                 TLS / Alert handshake failure      
                 ECDH-RSA-AES128-SHA                 TLS / Alert handshake failure      
                 ECDH-ECDSA-RC4-SHA                  TLS / Alert handshake failure      
                 ECDH-ECDSA-NULL-SHA                 TLS / Alert handshake failure      
                 ECDH-ECDSA-DES-CBC3-SHA             TLS / Alert handshake failure      
                 ECDH-ECDSA-AES256-SHA               TLS / Alert handshake failure      
                 ECDH-ECDSA-AES128-SHA               TLS / Alert handshake failure      
                 DHE-RSA-SEED-SHA                    TLS / Alert handshake failure      
                 DHE-RSA-CAMELLIA256-SHA             TLS / Alert handshake failure      
                 DHE-RSA-CAMELLIA128-SHA             TLS / Alert handshake failure      
                 DHE-RSA-AES256-SHA                  TLS / Alert handshake failure      
                 DHE-RSA-AES128-SHA                  TLS / Alert handshake failure      
                 DHE-DSS-SEED-SHA                    TLS / Alert handshake failure      
                 DHE-DSS-CAMELLIA256-SHA             TLS / Alert handshake failure      
                 DHE-DSS-CAMELLIA128-SHA             TLS / Alert handshake failure      
                 DHE-DSS-AES256-SHA                  TLS / Alert handshake failure      
                 DHE-DSS-AES128-SHA                  TLS / Alert handshake failure      
                 DH-RSA-SEED-SHA                     TLS / Alert handshake failure      
                 DH-RSA-DES-CBC3-SHA                 TLS / Alert handshake failure      
                 DH-RSA-DES-CBC-SHA                  TLS / Alert handshake failure      
                 DH-RSA-CAMELLIA256-SHA              TLS / Alert handshake failure      
                 DH-RSA-CAMELLIA128-SHA              TLS / Alert handshake failure      
                 DH-RSA-AES256-SHA                   TLS / Alert handshake failure      
                 DH-RSA-AES128-SHA                   TLS / Alert handshake failure      
                 DH-DSS-SEED-SHA                     TLS / Alert handshake failure      
                 DH-DSS-DES-CBC3-SHA                 TLS / Alert handshake failure      
                 DH-DSS-DES-CBC-SHA                  TLS / Alert handshake failure      
                 DH-DSS-CAMELLIA256-SHA              TLS / Alert handshake failure      
                 DH-DSS-CAMELLIA128-SHA              TLS / Alert handshake failure      
                 DH-DSS-AES256-SHA                   TLS / Alert handshake failure      
                 DH-DSS-AES128-SHA                   TLS / Alert handshake failure      
                 DES-CBC3-SHA                        TLS / Alert handshake failure      
                 DES-CBC-SHA                         TLS / Alert handshake failure      
                 CAMELLIA256-SHA                     TLS / Alert handshake failure      
                 CAMELLIA128-SHA                     TLS / Alert handshake failure      
                 AES256-SHA                          TLS / Alert handshake failure      
                 AES128-SHA                          TLS / Alert handshake failure      
                 AECDH-RC4-SHA                       TLS / Alert handshake failure      
                 AECDH-NULL-SHA                      TLS / Alert handshake failure      
                 AECDH-DES-CBC3-SHA                  TLS / Alert handshake failure      
                 AECDH-AES256-SHA                    TLS / Alert handshake failure      
                 AECDH-AES128-SHA                    TLS / Alert handshake failure      
                 ADH-SEED-SHA                        TLS / Alert handshake failure      
                 ADH-RC4-MD5                         TLS / Alert handshake failure      
                 ADH-DES-CBC3-SHA                    TLS / Alert handshake failure      
                 ADH-DES-CBC-SHA                     TLS / Alert handshake failure      
                 ADH-CAMELLIA256-SHA                 TLS / Alert handshake failure      
                 ADH-CAMELLIA128-SHA                 TLS / Alert handshake failure      
                 ADH-AES256-SHA                      TLS / Alert handshake failure      
                 ADH-AES128-SHA                      TLS / Alert handshake failure      

 SCAN COMPLETED IN 111.36 S
 --------------------------

</pre>

**Comment by nabla-c0d3** [comment]
Timeouts might mean that the server can't handle so many connections. Can you try with just one tls version (`--tlsv1_1` for example) ?

**Comment by arjones67** [comment]
Was anything ever found on this issue?  I'm seeing the same thing with using --regular with only TLSv1.1 or TLSv1.2 (just 1 of them) enabled on Apache 1.2.15 on RHEL 6.6.  I'm using sslyze  0.11 with Python 2.7.5.  

With only tlsv1.2 and using --tlsv1_2, I get the results for tlsv1.2, but --regular times out.  I get this same behavior with only tlsv1.1 enabled (--tlsv1_1 works, but not --regular).  With TLSv1 only enabled both --regular and --tlsv1 work.  As soon as I enable a 2nd protocol, --regular works with any combination.

**Comment by nabla-c0d3** [comment]
SSLyze was mistakenly detecting a timeout, although a different network error was happening. Thanks for the feedback
