### ISSUE TITLE
IPv6 compatibility

### ISSUE THREAD

**Issue by Vilican** [nabla-c0d3/sslyze#86]
It does not work with IPv6. For example, when checking host availability:
sufix.cz -> 2a01:9420:41:100::1:443
TIMEOUT
Instead of
sufix.cz -> [2a01:9420:41:100::1]:443
OK

**Comment by nabla-c0d3** [comment]
I tried this scanning this host over IPv6 and it seemed to be working fine. Is it just a display issue in the output ? 
Ie. Showing 

    sufix.cz -> [2a01:9420:41:100::1]:443

Instead of

    sufix.cz -> 2a01:9420:41:100::1:443

**Comment by Vilican** [comment]
No, it does not work. It shows timeout.

**Comment by nabla-c0d3** [comment]
It works for me over IPv6:
```
$ python sslyze.py --certinfo=basic sufix.cz

[...]

CHECKING HOST(S) AVAILABILITY
 -----------------------------

   sufix.cz:443                        => 2a01:9420:41:100::1:443



 SCAN RESULTS FOR SUFIX.CZ:443 - 2A01:9420:41:100::1:443
 -------------------------------------------------------

[...]
```

Are you sure you can connect to the server from your host ? Do you have a lot of simultaneous connections open?

**Comment by Vilican** [comment]
Are you sure you can connect to the server from your host? Yes, I can.
Do you have a lot of simultaneous connections open? What exactly mean a lot of?

**Comment by fabian-z** [comment]
Works perfectly here over IPv6. Are you sure you don't have a broken IPv6 config? Please check here http://test-ipv6.com/ and provide only the summary from the tab "For the Help Desk" on the right. Please do not include the link at the very bottom of the tab, as this will share your IP address.
