### ISSUE TITLE
Getting the worker results

### ISSUE THREAD

**Issue by carlskii** [nabla-c0d3/sslyze#88]
Hi,

I need to fire the result for each of the completed worker tasks to an external database. Where is the best place to insert the call to the DB in order to capture each result set.

Thanks.

**Comment by nabla-c0d3** [comment]
Most likely in plugins.PluginResult ? This class gets instantiated as soon as a plugin task is over in order to pass the results around.

**Comment by nabla-c0d3** [comment]
If you want something less sneaky, you could also do it at the end of sslyze.py
