### ISSUE TITLE
Client initiated renegotiations - Vulnerable

### ISSUE THREAD

**Issue by tr4nc3** [nabla-c0d3/sslyze#90]
In TLSv1.2 only supported servers, where client initiated renegotiations are possible, a message is shown - Vulnerable - Server honors client-initiated renegotiations.  On a jboss server, that uses latest JRE and with the command line flag allowUnsafeReneogitations=false, it still shows up as vulnerable.

Is this a bug in SSLyze code? 

Update:
Verified this: the OpenSSL 0.9.8k version that does not implement the insecure client side fixes, was not able to establish communication with the server but sslyze reported that as vulnerable.

**Comment by elvanderb** [comment]
Vulnerable to *client-initiated renegotiations* this is not the same thing than *unsafe renegotiation*.
Client initiated renegotiation can be used to perform DoS attacks.
Unsafe renegotiation can be used to inject arbitrary data in encrypted messages.

**Comment by tr4nc3** [comment]
Interesting point.  So it's not even a false positive too.  I'd imagine to be not vulnerable then one would have to disable all renegotiations - secure and insecure.  Do you happen to know how often modern browsers issue SSL renegotiation requests?  I'd imagine this wouldn't be so frequent.
