### ISSUE TITLE
--ca-file not working as expected

### ISSUE THREAD

**Issue by henshin** [nabla-c0d3/sslyze#91]
Hi,

Recently I was checking a client's host and I noticed something strange.
I'm running sslyze like this:
<pre>
$ ./sslyze_v0.11/sslyze.py --regular host:443  
(...)
  * Certificate - Trust:
      Hostname Validation:               OK - Subject Alternative Name matches
      Mozilla NSS CA Store (04/2015):    FAILED - Certificate is NOT Trusted: unable to get local issuer certificate
      Java 6 CA Store (Update 65):       FAILED - Certificate is NOT Trusted: unable to get local issuer certificate
      Microsoft CA Store (04/2015):      FAILED - Certificate is NOT Trusted: unable to get local issuer certificate
      Apple CA Store (OS X 10.10.3):     FAILED - Certificate is NOT Trusted: unable to get local issuer certificate
      Certificate Chain Received:        ['host']
(...)
</pre>
I also tried running OpenSSL directly:
<pre>
$ openssl s_client -connect host:443 -verify 5                      
verify depth is 5
CONNECTED(00000003)
depth=0 C = IT, ST = [omitted], L = [omitted], O = [omitted]., OU = [omitted], OU = Terms of use at www.verisign.com/rpa (c)05, CN = host
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 C = IT, ST = [omitted], L = [omitted], O = [omitted], OU = [omitted], OU = Terms of use at www.verisign.com/rpa (c)05, CN = host
verify error:num=27:certificate not trusted
verify return:1
depth=0 C = IT, ST = [omitted], L = [omitted], O = [omitted]., OU = [omitted], OU = Terms of use at www.verisign.com/rpa (c)05, CN = host
verify error:num=21:unable to verify the first certificate
verify return:1
(...)
</pre>
It seems that the certificate isn't valid, however when I opened the host on my browser (I tried Firefox, Chrome and IE) they all say that the certificate is verified.
After digging a bit on the internet, I concluded that it's failing because there's an intermediate certificate which has the CN '**VeriSign Class 3 International Server CA - G3**' which seems that is not trusted on some systems.
So I downloaded the certificate from here https://www.tbs-certificates.co.uk/FAQ/en/600.html and ran again the OpenSSL with the -CAfile option:
<pre>
$ openssl s_client -connect host:443 -CAfile SVRIntlG3.crt -verify 5
verify depth is 5
CONNECTED(00000003)
depth=2 C = US, O = "VeriSign, Inc.", OU = VeriSign Trust Network, OU = "(c) 2006 VeriSign, Inc. - For authorized use only", CN = VeriSign Class 3 Public Primary Certification Authority - G5
verify return:1
depth=1 C = US, O = "VeriSign, Inc.", OU = VeriSign Trust Network, OU = Terms of use at https://www.verisign.com/rpa (c)10, CN = VeriSign Class 3 International Server CA - G3
verify return:1
depth=0 C = IT, ST = [omitted], L = [omitted], O = [omitted]., OU = [omitted], OU = Terms of use at www.verisign.com/rpa (c)05, CN = host
verify return:1
---
</pre>
No errors. However when I use the --ca_file parameter on sslyze, i still get all the errors:
<pre>
$ ./sslyze_v0.11/sslyze.py --regular --ca_file SVRIntlG3.crt host:443 
(...)
  * Certificate - Trust:
      Hostname Validation:               OK - Subject Alternative Name matches
      Mozilla NSS CA Store (04/2015):    FAILED - Certificate is NOT Trusted: unable to get local issuer certificate
      Java 6 CA Store (Update 65):       FAILED - Certificate is NOT Trusted: unable to get local issuer certificate
      Microsoft CA Store (04/2015):      FAILED - Certificate is NOT Trusted: unable to get local issuer certificate
      Custom --ca_file CA Store (N/A):   FAILED - Certificate is NOT Trusted: unable to get issuer certificate
      Apple CA Store (OS X 10.10.3):     FAILED - Certificate is NOT Trusted: unable to get local issuer certificate
      Certificate Chain Received:        ['host']
(...)
</pre>

Maybe I'm using some option incorrectly, but I would expect sslyze to behave similarly to OpenSSL.
_(I had to omit the host and some info on the certs, sorry)_

**Comment by glestel** [comment]
I have some similar issues, and it's because an intermediate certificate is signed with SHA-1

**Comment by henshin** [comment]
In this case the certificate was in fact signed using SHA-1. But is there any workaround for this?

**Comment by nabla-c0d3** [comment]
The server should be sending back all the intermediate certificates along with the leaf/server cert. If you have to manually add it via -CAfile, it means the server is misconfigured; when SSLyze tries to build the chain, it can't as this intermediate cert is missing. Browsers still work because they cache all the intermediate certs they see (specifically as a workaround for misconfigured servers).

**Comment by henshin** [comment]
I see. Thanks for the explanation.
So it means that for SSLyze to validate the host correctly, the cert file provided in the **--ca_file** option should have the complete chain inside, right?
I think it would be nice for it to use that certificate along with the others in the stores to validate the target. Or is it a bad idea?

**Comment by nabla-c0d3** [comment]
It's not really the intent of ca_file to use the other trust stores for validation (as it is meant to validate against a custom store). Here, the server is misconfigured so I think SSLyze returning a validation error is acceptable.

**Comment by henshin** [comment]
Yes, I agree that it's acceptable. 
Before closing this issue, just one more question. Does SSLyze has the capability of recognizing when the server sends the complete chain or not and warn about it when it doesn't (instead of just reporting it as invalid)? 
I'm currently parsing the xml output of SSLyze to feed another script and it would be very helpful if I can infer this situation.
Thanks for the feedback

**Comment by nabla-c0d3** [comment]
Debugging invalid certificate chains is always a bit tricky. You would have to look at the error message returned by SSLyze (which is one OpenSSL returns): "unable to get local issuer certificate". AFAIK this one means one of the two following things:
* The CA/anchor cert is not in the trust store
* An intermediate cert is missing so the full chain can't be built
Somewhat unrelated but certificate validation will be slightly better in the next version as I'll update to OpenSSL 1.0.2 which performs certificate validation in a way that's closer to what browsers do.

**Comment by henshin** [comment]
In my case, the problem is the second thing you mentioned. The intermediate certificates are missing and that makes it invalid. However because browsers can fetch the intermediate certificates on-the-fly through the information on AIA extension, they validate the cert successfully.
I downloaded the latest version of OpenSSL 1.0.2d, and ran the validation check again and unfortunately it still marks it as invalid. I tried to check if there any options related to the AIA extension, but I didn't found any.
So far the only thing that makes SSLyze mark the certificate as valid is to download the intermediate certificate, add it to a pre-existing cert bundle file and use that file with the --ca_file option:
<pre>
  * Certificate - Trust:
      Hostname Validation:               OK - Subject Alternative Name matches
      Mozilla NSS CA Store (04/2015):    FAILED - Certificate is NOT Trusted: unable to get local issuer certificate
      Microsoft CA Store (04/2015):      FAILED - Certificate is NOT Trusted: unable to get local issuer certificate
      Java 6 CA Store (Update 65):       FAILED - Certificate is NOT Trusted: unable to get local issuer certificate
      Custom --ca_file CA Store (N/A):   OK - Certificate is trusted
      Apple CA Store (OS X 10.10.3):     FAILED - Certificate is NOT Trusted: unable to get local issuer certificate
      Certificate Chain Received:        ['host']
</pre>
Maybe someday you can find some time to implement some checks to do this automatically :)

**Comment by nabla-c0d3** [comment]
This seems like a lot of work and I think it's just better (and easy anyway?) to return the proper certificate chain to the clients, who also may not be browsers (mobile Apps, etc.). I will close this issue for now but if you have time, I would be curious to know what SSL Labs (https://www.ssllabs.com/ssltest/) says about the chain (valid VS invalid).
Thanks!

**Comment by henshin** [comment]
You're right and after further investigation, I conclude if a server doesn't send the complete chain, this should be reported as a misconfiguration, otherwise we are encouraging lazy sys admins because a properly configured server should always send the complete chain. There's actually a issue open on BugZilla that goes back to 2007 where this problem is being discussed in detail (https://bugzilla.mozilla.org/show_bug.cgi?id=399324). After reading some comments, I also agree that the browser/client shouldn't be responsible for fetching intermediate certs.
Thanks for the support.
