### ISSUE TITLE
only the client certificate is loaded and not the chain provided in the certFile

### ISSUE THREAD

**Issue by lindererik** [nabla-c0d3/sslyze#92]
HI,
I'm trying to run your great tool against a server which requires a client certificate but the client has to also provide the subCA of the certificate. thus the TLS client need to load a certificate chain and not just a certificate.

I think I traced it to 

./nassl/SslClient.py:        self._ssl.use_certificate_file(certFile, certType)

which only loads the first certificate in certFile. 

I'm using the following command line: python sslyze.py --timeout=1 --resum --reneg --cert=s.pem --key=k.pem

**Comment by nabla-c0d3** [comment]
The corresponding commit in nassl is at https://github.com/nabla-c0d3/nassl/commit/1d4915228fde0da9040e7165fa65aedbd0ae6984
Thanks for the feedback!
