### ISSUE TITLE
I have created a XSLT stylesheet for sslyze

### ISSUE THREAD

**Issue by Archstacker** [nabla-c0d3/sslyze#93]
I have created a XSLT stylesheet to generate a HTML report according the XML report generated by sslyze : https://github.com/Archstacker/sslyze-html . Issue refer : iSECPartners/sslyze#42

I do it according to the https://sslcheck.globalsign.com/ , and I don't know whether it's suitable or not.

What's your opinions about it?

**Comment by nabla-c0d3** [comment]
This seems *very* cool as a lot of people have been asking about HTML reports! I will have a look as soon as I some free time.

**Comment by Archstacker** [comment]
Now I have wrapped the sslyze to a web server with the help of tornado and this XSLT stylesheet : https://github.com/Archstacker/sslyze-web
