### ISSUE TITLE
Ignore default trust store when providing custom --ca_file

### ISSUE THREAD

**Issue by glestel** [nabla-c0d3/sslyze#96]
Hello,

For securing our intranet network at work, we are using our own PKI. Providing the path to our .pem work well, but SSLyze is still checking against its default trust store that will inevitably fail.
Is there a way to deactivate default trust stores verification to avoid these errors?

Thanks.

**Comment by nabla-c0d3** [comment]
Hi,
Why do you want to specifically disable these errors, instead of ignoring them?

**Comment by glestel** [comment]
I use the XML report as data to parse in another tool (a plugin I wrote for [Mozilla's Minion](https://github.com/mozilla/minion)). It checks for each "path_validation" raise an issue if an error is found. I could always add a condition in my tool to check only some specific trust store but that's less generic.
I get your point of view, so that would be more of a feature request if ever other people have the same need.
Thanks for your quick reply

**Comment by nabla-c0d3** [comment]
For now I will not implement this as I can see a use case for having the validation result of both a custom trust store and the regular ones; if more people ask for this I will look into it. Thanks for feedback!
