### ISSUE TITLE
Weird behavior with new Google standards 

### ISSUE THREAD

**Issue by glestel** [nabla-c0d3/sslyze#99]
Hello,

Google will be rolling out a new policy regarding TLS http://googleonlinesecurity.blogspot.fr/2015/09/disabling-sslv3-and-rc4.html 
I wanted to try sslyze with their new test https://cert-test.sandbox.google.com/ but sslyze is taking long time to process the because of timeout with TLS v1 and TLS v1.1 Do you know why it is in time-out rather than in "rejected" ?

On a side note, their certificate is rejected by the OS X trust store but accepted by others. 

Edit: regarding https://github.com/nabla-c0d3/sslyze/issues/85 I've tried with just `--tlsv1` and `--tlsv1_2` and it also triggers timeout. But `--tlsv1_2` is working spot on

**Comment by nabla-c0d3** [comment]
Thanks for the feedback
